### ISSUE TITLE
Add executable comments in SequenceableCollection - sorting shuffling split protocol

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5450] opened 2020-01-07 08:01 UTC
There are a lot of opportunities to improve the comment using executable comments in the collection hierarchy and in particular SequencableCollection 

"#(a b c) allButFirst >>> #(b c)"

**Comment by juliendelplanque** [comment] 2020-01-31 08:46
Looks like it was fixed in #5461 so we can close it?

**Comment by LaurineDargaud** [comment] 2020-02-28 09:55
There are no executable comments, so the issue is still valid.

**Closed as completed** 2020-03-04 09:19 UTC
Labels: Easy
