### ISSUE TITLE
UndefinedObject>>#DoIt is calling deprecated method

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16006] opened 2024-01-21 21:56 UTC
```
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method Metaclass>>#uses:instanceVariableNames: called from UndefinedObject>>#DoIt has been deprecated. Use #trait:slots: instead.

*** Warning: Deprecation: Automatic deprecation code rewrite: The method Metaclass>>#uses:instanceVariableNames: called from UndefinedObject>>#DoIt has been deprecated. Use #trait:slots: instead.
DeprecationPerformedNotification: Automatic deprecation code rewrite: The method Metaclass>>#uses:instanceVariableNames: called from UndefinedObject>>#DoIt has been deprecated. Use #trait:slots: instead.
```

**Comment by MarcusDenker** [comment] 2024-01-22 07:40
see https://github.com/pharo-project/pharo/issues/15733

**Comment by MarcusDenker** [comment] 2024-01-24 11:52
I close this as a duplicate of https://github.com/pharo-project/pharo/issues/15733

**Closed as completed by MarcusDenker** 2024-01-24 11:52 UTC
