### ISSUE TITLE
Why class compilation accept multiply defined shared variables?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15335] opened 2023-11-13 09:14 UTC
Note that the following happens and that the class is compiled (at least I pressed command S) and used the menu item accept. So this is not like I'm editing the buffer when I press command S multiple time I get a black flash.

```
Object << #Grb
	slots: { #point . #point2 };
	sharedVariables: { #C3 . #C1 . #C2 . #C2};
	tag: '';
	package: 'Refactoring-Junk'
```

looks bogus to me. 

This one too

```
Object << #Grb
	slots: { #point . #point2 };
	sharedVariables: { #C2. #C3 . #C1 . #C2 . #C2};
	tag: '';
	package: 'Refactoring-Junk'
```

**Comment by Ducasse** [comment] 2023-11-13 09:20
This is really a problem because it breaks the node navigation. 
When I want to use the refactorings the source menu is displayed only on some occurrences of the variables.

**Comment by Ducasse** [comment] 2023-11-13 09:24
Note that source pop up is working after careful retest on all the duplicates and removing one occurrences via a refactoring is removing all the occurrences so it looks like a UI glitch.

**Comment by Ducasse** [comment] 2023-11-13 09:25
So it looks related to https://github.com/pharo-project/pharo/issues/15334 and is probably be the same issue.

**Comment by MarcusDenker** [comment] 2023-11-15 06:56
I tried this in the last Pharo12 and for me, the Browser is correctly refreshed and shows just one variable.

**Comment by MarcusDenker** [comment] 2023-11-15 06:57
technically, as the sharedPool is dictionary, multiple entries with the same key are not possible on that level.

so if you see this, is means that the tab is not refreshed.

**Comment by MarcusDenker** [comment] 2023-11-15 07:03
Duplicate of https://github.com/pharo-project/pharo/issues/15334

**Closed as completed by MarcusDenker** 2023-11-15 07:03 UTC
Labels: Version: Pharo 12, Priority: High
