### ISSUE TITLE
Why the debugger select all the occurrences of a message 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4459] opened 2019-08-31 20:10 UTC
Because the selection makes more difficult to spot the actual sender.

**Comment by Ducasse** [comment] 2019-08-31 20:11
![Screenshot 2019-08-31 at 22 10 18](https://user-images.githubusercontent.com/432549/64068721-345b1800-cc3c-11e9-9e2a-d6bb749ddaea.png)

**Comment by Ducasse** [comment] 2019-08-31 20:11
And I see this in fact 


![Screenshot 2019-08-31 at 22 11 20](https://user-images.githubusercontent.com/432549/64068726-4dfc5f80-cc3c-11e9-8014-737ad02899f1.png)

**Comment by dupriezt** [comment] 2019-08-31 21:27
It's the standard behaviour of selection in a RubScrolledTextMorph: the morph used as text editor for both the debugger and other things like calypso.
In my opinion the more general question is: why does the debugger use text selection to show what the execution is about to do, and not some dedicated static highlight like the red bands that are displayed on 'self halt':
![image](https://user-images.githubusercontent.com/32486709/64069269-78531a80-cc46-11e9-99cb-f6ae95bff769.png)
Using text selection for this means that when the user selects another part of the code, the debugger does not show anymore what the execution is about to do, and this means the "where is?" button is necessary to set the selection back to what the execution is about to do.

If a static highlight of a different colour was used, there would be no interference with normal text selection by the user, and we could remove the "where is?" button from the interface.

**Comment by dionisiydk** [comment] 2019-08-31 22:33
@dupriezt. That's sound like a good idea and it's probably not difficult to do.

**Comment by dupriezt** [comment] 2019-09-03 06:39
The issue is that I don't really know where to start.
Also, unlike the code browser, the debugger does not show the red bands from halts for some reason.

**Comment by dionisiydk** [comment] 2019-09-03 07:35
Yes, it looks simple on the level of raw text widget but not on the level
of gt framework.
I would not spend time on gtdebugger as it is going to be replaced.


вт, 3 сент. 2019 г., 7:39 dupriezt <notifications@github.com>:

**Comment by MarcusDenker** [comment] 2019-09-27 12:27
I checked and one solution would be to remove the method #debugHighlightStart from RBMessageNode. This explicitly sets the start to the start of the selector, the inherited default is the start of the receiver....

**Comment by StevenCostiou** [comment] 2021-01-15 14:57
Fixed by https://github.com/pharo-project/pharo/pull/8359

**Closed as completed by StevenCostiou** 2021-01-15 14:57 UTC
Labels: Project: Debugger
