### ISSUE TITLE
Iceberg fails to commit to git

### ISSUE THREAD

**Issue by lopezca** [guillep/pharo-core#11517] opened 2022-08-12 20:43 UTC
**Bug description**
When doing a commit, `MCDefinitionIndex>>definitionLike:ifPresent:ifAbsent` receives `nil` in the definition and then fails to extract a description.

**To Reproduce**
If working on main branch and move to a different branch, then come back to main.

**Expected behavior**
It should do the commit.

**Screenshots**

![image](https://user-images.githubusercontent.com/27969022/184441856-9560d6bf-e44f-46cb-858f-b2242f944573.png)

**Version information:**
 - OS: Windows 10 
 - Pharo Version 10 521.

**Comment by Ducasse** [comment] 2022-08-13 08:03
Thanks carlos. 
I know that we fixed one similar problem in P11.
This is difficult to debug like that. 
Can you to down the stack to give us more information?
If you have a chance to fileout your package and load it in Pharo 11?

**Comment by lopezca** [comment] 2022-08-15 04:14
I tried getting this error on pharo 11 and I can't reproduce it.

On my Pharo 10 image, I found an untracked class.st file looking in the git repository, I removed that file and resetted the git repo and the image to the last commit, now it doesn't happen any more.

I've tested the same steps as before, but can't get the error anymore, so I don't know why it was triggered.

I can close this issue and come back if it happens again (please let me know or feel free to close it).

**Comment by Ducasse** [comment] 2022-08-15 07:01
Thanks a lot for trying. It really helps. 
Because we are often in the dark to fix bugs that we cannot reproduce.

**Comment by Ducasse** [comment] 2022-08-15 07:01
I will close it and if you get a reproducible case (that we can reproduce)  let us kow

**Comment by guillep** [comment] 2022-08-18 09:39
This issue is fixed in Pharo 11, we should check to backport it to P10. It's important.

**Comment by guillep** [comment] 2022-08-18 09:40
It's a duplicate of https://github.com/pharo-project/pharo/issues/11370

**Closed as completed by guillep** 2022-08-18 09:40 UTC
Labels: Type: Bug
