### ISSUE TITLE
Emergency evaluator while debugging some code

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3371] opened 2019-05-17 14:08 UTC
In a playground I tried to debug this code:

```Smalltalk
1 to: 10 do: [ :e | 1halt. e log ]
```

And in the debuggeur I only did step through all the time. After a while (when I go on the halt) I get an emergency evaluator.

It happens in Pharo 8.

**Comment by Ducasse** [comment] 2019-05-19 20:26
Thanks Cyril.

**Comment by dupriezt** [comment] 2019-08-05 09:59
Same issue when stepping **over** a halt message.

**Comment by dupriezt** [comment] 2019-08-05 10:12
I dug a bit (I started from another example, but the issue is the same).
Full report: [SteppingOverASelfHaltOpensAnEmergencyEvaluatorInP8.pdf](https://github.com/pharo-project/pharo/files/3467083/SteppingOverASelfHaltOpensAnEmergencyEvaluatorInP8.pdf)
Basically, the issue is in `GTGenericStackDebugger>>#setDebuggerToFirstNonFilteredContext` when a debugger for the halt that is stepped over is opened. The stack only contains one context: `Object>>#halt`, which is filtered out because the method has the #debuggerCompleteToSender pragma. So the filtered stack is empty, and #setDebuggerToFirstNonFilteredContext sends #first to this empty collection.

The question is why the unfiltered stack for the halt that is stepped over only contains one context and nothing else.

**Comment by MarcusDenker** [comment] 2019-10-07 10:20
I added a empty check to the setDebuggerToFirstNonFilteredContext method. Now there is no DNU

**Comment by MarcusDenker** [comment] 2019-10-07 10:20
(was merged as part of another PR)

**Comment by MarcusDenker** [comment] 2020-07-10 11:58
This now works fine in Pharo9

**Closed as completed by MarcusDenker** 2020-07-10 11:58 UTC
Labels: Project: Debugger
