### ISSUE TITLE
Rename a protocol is breaking

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8223] opened 2021-01-04 10:42 UTC
```
buildSearchMorph
	^ searchMorph := SearchMorph new
			model: self;
			acceptSelector: #searchAccept:;
			updateSelector: #searchUpdate:;
			searchList: self class searchList;
			keystrokeSelector: #searchKeystroke:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
			yourself.	
```

**Comment by dupriezt** [comment] 2021-01-08 00:34
This looks like a duplicate of issue #8173

**Closed as completed** 2021-01-08 16:11 UTC
Labels: Type: Bug
