### ISSUE TITLE
Pharo 9. Ubuntu 20.04.2 Diacritics are not displayed correctly on editor panels

### ISSUE THREAD

**Issue by pgonzalezc** [guillep/pharo-core#9721] opened 2021-08-01 18:06 UTC
**Bug description**
Diacritics are not displayed correctly on editor panels

**Expected behavior**
Pharo 8 works correctly with this type of characters

**Screenshots**
![disacriticsInPharo9](https://user-images.githubusercontent.com/6128848/127780959-bba4b0d0-0ed1-46d3-965e-5e75982ad7ca.png)

i vowel should be &iacute;

**Version information:**
 - OS: Ubuntu
 - Version: 20.04.2
 - Pharo Version: 9

**Comment by joao-pedro-braz** [comment] 2021-08-02 16:22
I'm using KDE Plasma 5.22.3, with the same base image, but I can not reproduce the behavior you mentioned.
![image](https://user-images.githubusercontent.com/37230465/127893079-2698f041-c503-4418-9359-b76f14d71a6e.png)

**Comment by pgonzalezc** [comment] 2021-08-07 12:41
i was using build 1538, installed build 1542 of Pharo 9.0.0 and the problem persists.

**Comment by Ducasse** [comment] 2021-08-07 20:10
Thanks for the report. 
We are busy fixing other bugs :) and we will come back to this issue.

**Comment by tesonep** [comment] 2021-08-11 15:12
Hi @pgonzalezc, I have tried with the latest Pharo version and the latest VM and it is working.
![Screenshot 2021-08-11 at 17 08 43](https://user-images.githubusercontent.com/355455/129055053-d240122a-f61b-4f67-9cfe-604a4f71d66f.png)

Can you update the VM or telling us which version are you using? 
From the menu you can choose System / System Reporter

![image](https://user-images.githubusercontent.com/355455/129055383-d0bd3614-ea47-4254-8ddb-620875773ceb.png)

**Comment by pgonzalezc** [comment] 2021-08-15 16:33
This is the system report requested:
![SystemReportPharo](https://user-images.githubusercontent.com/6128848/129485562-d85475fe-91b1-4d0f-8253-8f72b59f646e.png)

**Comment by Ducasse** [comment] 2021-08-15 19:52
Thanks. What you see is that you are using a VM from february 2020. 
You should update your virtual machine. It is nearly two years old. 
We tested on the latest VM and it works. It took us two hours to be able to do a copy and paste on ubuntu so we are quite sure that it works.

**Comment by Ducasse** [comment] 2021-08-15 19:53
Thanks for the report. I will close the issue because we found the problem.

**Closed as completed by Ducasse** 2021-08-15 19:53 UTC
Labels: Type: Bug
