### ISSUE TITLE
LinkedList #after: hangs image when list is circular

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#3079] opened 2019-03-29 12:53 UTC
I wanted to create a circular list so that I can wrap around getting the next value. When I do this however, #next: seems to hang the image.  (Cmd + . doesn't work)

I did the following:

```
list := LinkedList withAll: #($n $e $s $w).
list lastLink nextLink: list firstLink.
list after: $n.
```

I also notice that if you evaluate the first two lines, and then try to use "debug it" (context menu) to see why it hangs (in a new image), that this seems to hang the image before the debugger appears as well.

**Comment by kasperosterbye** [comment] 2019-09-23 10:34
The problem is that `do:` goes into infinite loop when you make the list circular.
It is a relative easy fix to make sure each element only gets visited once.

```Smalltalk
do: aBlock
	"I execute aBlock for each element in the list. If I am circular I only visit each element once"
	| aLink |
	self ifEmpty: [ ^ self ].
	aLink := firstLink.
	[ aBlock value: aLink value.
	aLink = lastLink | aLink nextLink isNil
		ifTrue: [ ^ self ].
	aLink := aLink nextLink ] repeat
```

However, I am not sure if circular lists should be subclasses of SequenceableCollection, as it leads to strange interpretations of non-unique indexes for the same element, remove etc.

I do not really think LinkedList should be made circular. As far as I am concerned Circular Linked Lists is a slight optimisation over normal linked lists in that one can do away with one of linkage pointers. 

I suggest to close the issue.

**Comment by kasperosterbye** [comment] 2021-02-01 09:41
I still suggest to close this issue.

**Closed as completed** 2021-02-01 09:41 UTC

**Comment by macta** [comment] 2021-02-01 10:04
But wasn't the point that cmd . Doesn't work? You should not be able to crash your image with a coding error?

**Comment by kasperosterbye** [comment] 2021-02-01 14:43
As far as I know there are many situations where "cmd ." do not stop a closed loop. So while annoying, it is not unknown.

**Comment by macta** [comment] 2021-02-01 15:57
Yes - but cmd . is supposed to cleanly interrupt - so this is a perfect test case, which was half my point in raising it - its a real time waste to crash your image from a simple coding error
