### ISSUE TITLE
CI of pull request

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#5556] opened 2020-01-22 20:15 UTC
The automatic tests of pull requests could be better. This is a picture of the Pull requests on January 22nd at 9PM. All red crosses mean that something did not pass the CI Tests. It looks like editing a comment will fail. 

I am afraid this will discourage contribution.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/17723745/72930359-0e095680-3d5c-11ea-9b66-62a90c77456e.png">

**Comment by MarcusDenker** [comment] 2021-02-01 10:32
Duplicate of https://github.com/pharo-project/pharo/issues/3876

**Closed as completed by MarcusDenker** 2021-02-01 10:32 UTC
