### ISSUE TITLE
Arrow toolip in Spotter is broken

### ISSUE THREAD

**Issue by welblaud** [guillep/pharo-core#8375] opened 2021-01-15 14:53 UTC
**Describe the bug**
The tooltip (or some other graphical element) which emerges after I hover over the arrows on the right side of Spotter is broken.

**To Reproduce**
Open Spotter, hover over the blue arrow (for any row).

**Expected behavior**
There should be something instead of the broken balloon.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/8298610/104741575-b2449400-5749-11eb-9d82-6cda0c23b289.png)

**Version information:**
 - OS: Xubuntu 20.04
 - Version: 8.0

**Comment by dupriezt** [comment] 2021-01-29 09:52
Edit: my OS is Windows 10

I can't reproduce this issue in Pharo 9 Light Theme.
I'll try with the Dark Theme and Pharo 8.
![image](https://user-images.githubusercontent.com/32486709/106259920-21c58380-6220-11eb-80cf-a20c36ea4edf.png)

Edit: Also works in Pharo 9 Dark Theme
![image](https://user-images.githubusercontent.com/32486709/106260027-41f54280-6220-11eb-9709-dcbe0ea99da2.png)

Edit: Also works in Pharo 8 Dark Theme
![image](https://user-images.githubusercontent.com/32486709/106260652-ea0b0b80-6220-11eb-8bb0-e543b1078b64.png)

Edit: Also works in Pharo 8 Light Theme
![image](https://user-images.githubusercontent.com/32486709/106260898-36564b80-6221-11eb-8669-1399a5680d36.png)

**Comment by dupriezt** [comment] 2021-01-29 10:05
Maybe this issue was fixed by another pull-request in the meantime?
Or it's OS-specific?

@welblaud 
Do you recall doing anything a bit special in your image before the issue happened?
Could you try again in a fresh image to see if you still have the issue?

**Comment by welblaud** [comment] 2021-01-31 19:18
@dupriezt 
 Thank you, I tried it again, and in version 9 it works as expected. In version 8, it happens also with the light theme:
 
![obrazek](https://user-images.githubusercontent.com/8298610/106395236-66f4db80-6401-11eb-8e20-f41f5a9224ba.png)

I guess if it works in version 9, we could consider it as solved, right?

**Comment by MarcusDenker** [comment] 2021-02-01 08:16
yes, if it is not an absolute show stopper fixing in Pharo9 is the way to go. I close the issue

**Closed as completed by MarcusDenker** 2021-02-01 08:16 UTC
Labels: Type: Bug
