### ISSUE TITLE
Browsing in the Debugger always shows FullBlockClosure

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7698] opened 2020-11-09 07:32 UTC
**Describe the bug**
Browsing of method/receiver in the Debugger stack always shows only implementation of  FullBlockClosure

**To Reproduce**
1. evaluate `self halt`
2. RMB on any stack entry
3. Browse - method or Browse - receiver
4. the Browser with FullBlockClosure is always opened

![mLXIHbO0EC](https://user-images.githubusercontent.com/572494/98512147-22283100-2266-11eb-8a0a-1edd786eb95f.gif)

**Comment by Ducasse** [comment] 2020-11-10 09:07
We have to wait that the command use the new symbol extractor.

**Comment by MarcusDenker** [comment] 2020-12-14 15:34
This is not related to the symbol extractor, the problem is in the upper menu of the context.

I found what need to be fixed in StDebugger:

1) #doBrowseClass needs to send #value to evaluate the block, else it will always browse the the class of the context of the returned block:

```Smalltalk
doBrowseClass

	self systemNavigation browse: self stackSelectionMethodContext value
```

This will make it work for context of methods, but not blocks.
	
2) #stackSelectionMethodContext needs to make sure that, if it it is in a block, that it goes to the method that the block is defined in: (else it will always just browse CompiledBlock when in a blockContext). For this, can always call #home 

```Smalltalk
stackSelectionMethodContext
	^ [ stackTable selection selectedItem home method ]
```

**Comment by MarcusDenker** [comment] 2020-12-14 15:41
#doBrowseReceiverClass needs the #value, too:


```Smalltalk
doBrowseReceiverClass

	self systemNavigation browse: self stackSelectionReceiverClassContext value
```

**Comment by MarcusDenker** [comment] 2020-12-14 16:13
I added this as a pull request for NewTools: https://github.com/pharo-spec/NewTools/pull/142

**Closed as completed** 2020-12-15 09:17 UTC
Labels: Type: Bug, Project: Debugger
