### ISSUE TITLE
How people can contribute to Pharo if some of the tests on the base image are not passing?

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5227] opened 2019-11-26 10:07 UTC
I do not know how people can contribute to a system with tests that are continuously red?
For a newcomer to this community, all the tests passing means that the code he wrote is ok and his PR could be merged. But if the base image has already some flaws in it, how can he differentiate his failing tests from the base ones?

On the last week, more than half of the build of Pharo 8.0 were failing. It should be unlikely to happen if the imposed rules of the PR are followed (at least one review, green tests, and benchmarks): almost none of the PR have been merged without a full green check.

![image](https://user-images.githubusercontent.com/4706329/69617695-dff7e680-1038-11ea-8cba-47c9c3f189d5.png)

![image](https://user-images.githubusercontent.com/4706329/69618535-5517eb80-103a-11ea-8e61-96c4727dcce1.png)

Is it planned to enforce the rules on the PR or should we continue as it is now?

I can concede that some changes are critical and could be passed without all the checks but they should be marginals.

**Comment by MarcusDenker** [comment] 2019-11-26 10:52
The problem is that the tests are *not* red because of that PR. They are red because of other problems.

What we do is that we check the failing tests and if the fail is not related, we merge. 

Yes, this is not good. But the alternative is to not merge anything.

**Comment by MarcusDenker** [comment] 2019-11-26 10:53
It would be nice to fix the problems.

The first step is to remove the benchmark run because for the case that the rests are green (which already happens not often) the benchmark is always red.

**Comment by VincentBlondeau** [comment] 2019-11-26 11:55
Thanks Marcus! So first we may need to solve those deeper problems. Could you link those issues so we can fix them in priority? 

I think that the stability of the testing environment is very important.

For the benchmark, it could be still triggered and reported but not flagged as an issue for the test?

**Comment by MarcusDenker** [comment] 2019-11-26 13:08
I already added a board for the CI: https://github.com/orgs/pharo-project/projects/11

We can use that to have an overview.



<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 40 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>

**Comment by MarcusDenker** [comment] 2021-03-16 08:45
This has gotten better, we still have some problems with the CI... nevertheless, I will close this issue, as we should put dedicated issues for the problems we see on the CI

**Closed as completed by MarcusDenker** 2021-03-16 08:45 UTC

**Comment by Ducasse** [comment] 2021-03-17 06:55
Vincent you are right but this is not that simple :).
Yes we should open real issues for the real roots. Because the tests of Pharo are most of the time green and around 99% of them. Now the building environment is also pushing flakiness. And when we work on something we do not work on something else. We are really super super super busy. For example, Pablo is fixing old architecture problem linked to the drop of nativeBoost. So it was working but in some cases well not anymore. So he is fixing FFI mixed with pluging initialization that unfortunately is leading to strange unexpected crashes. Frankly I cannot fix this kind of problems. 
Nor am I able to produce a new JIT.
Please remember that at the end of the day we have 2 paid full time engineers. Guille is not working full time on Pharo. Christophe is working on COVID app since 6 months now. So we are about 2.5 engineers. And I think that they deliver massively. 
You should always consider that a small company has at least 3 times more full time engineers than us. 
So this is why we need help closing issues.
