### ISSUE TITLE
Debugger: Why the inspector does not have scrollbars

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6972] opened 2020-07-24 15:02 UTC
<img width="790" alt="Screenshot 2020-07-24 at 16 57 42" src="https://user-images.githubusercontent.com/432549/88405354-6d115c00-cdcf-11ea-8bc9-d99eb1a9e362.png">

**Comment by Ducasse** [comment] 2020-07-24 15:03
I had to enlarge de pane to see the state of the object

**Comment by estebanlm** [comment] 2020-07-24 15:09
In fact it seems there are scrollbars, just they are not visible, it seems a bug on the layout logic.

**Comment by StevenCostiou** [comment] 2020-08-06 12:14
@estebanlm this looks like a spec problem, it's possible to scroll even though we don't see the scrollbar, unless we enlarge the window then it appears.
I will check my layout and try to reproduce a minimal example.

**Comment by estebanlm** [comment] 2020-08-09 07:14
it is. But as I said... is not that if does not have, it is not visible due to a bug while calculating the box layout.
(Still a bug, but in SpBoxLayout and not in StInspector) ;)

**Comment by MarcusDenker** [comment] 2021-03-19 11:34
seems to be fixed now

**Closed as completed by MarcusDenker** 2021-03-19 11:34 UTC
Labels: Type: Bug, Project: Debugger
