### ISSUE TITLE
Context Menu (Right mouse menu) in Method-Sourcecode does not work

### ISSUE THREAD

**Issue by hoemac** [guillep/pharo-core#9250] opened 2021-05-05 15:53 UTC
**Bug description**
ContextMenu in SourceCode of arbitrary Method in SystemBrowser does not work. 

**To Reproduce**
1. Downloaded latest Pharo 9 image  May 5th 2021 
2. Open a System Browser
3. Browse arbitrary method and put cursor anywhere in the source code 
4. Click right mouse button 

**Expected behavior**
Context menu dows not work,  appears with debug information after running into an exception (see screenshot)  

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38470493/117168931-e6ab9100-adc8-11eb-87cf-cde6c23543aa.png)

![grafik](https://user-images.githubusercontent.com/38470493/117169560-7bae8a00-adc9-11eb-959b-8b1e57ac4686.png)

**Version information:**
 - OS: Windows
 - Version: 10
  - Pharo Version [ Pharo 9.0.0
Build information: Pharo-9.0.0+build.1390.sha.6e3dceda6ba1cfea9bfd09147470dfd1c23164e7 (64 Bit)]

**Additional context**
Showstopper for Pharo 9 (on Windows 10) for me if if no copy/paste etc is possible.

**Comment by rolandbernard** [comment] 2021-05-05 17:51
I also encountered this issue. It is caused by the changes made with #9103.
The AND-operation in `SycDeprecateClassCommand class>>canBeExecutedInContext:` should probably be lazy (i.e. `and: [...]`).

**Comment by MarcusDenker** [comment] 2021-05-06 18:45
This is fixed by merging the PR (I checked the latest version)

**Closed as completed by MarcusDenker** 2021-05-06 18:45 UTC
Labels: Type: Bug
