### ISSUE TITLE
there are 13 selectors with messages sent but not implemented in Athens

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#14923] opened 2023-10-08 03:07 UTC
```
| selectors |
selectors := SystemNavigation new allSentNotImplementedSelectors.
selectors select: [ :each | each package name beginsWith: 'Athens' ].
```

Operating System Details
------------------------
Debian GNU/Linux 11 \n \l

Linux version 5.10.0-18-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.140-1 (2022-09-02)

Operating System/Hardware
-------------------------
unix linux-gnu x86_64

Image
-----
/home/vonbecmann/Pharo/images/pharo-development/pharo-development.image
Pharo12.0.0
Build information: Pharo-12.0.0+build.861.sha.2bc94ea977cc1954a0f8f486975562a7960db00f (64 Bit)
Unnamed

**Comment by MarcusDenker** [comment] 2023-10-17 11:23
duplicate of https://github.com/pharo-project/pharo/issues/10834

**Closed as completed by MarcusDenker** 2023-10-17 11:23 UTC
Labels: Type: Enhancement
