### ISSUE TITLE
spec2 list filters cause #hasElementAt: DNU

### ISSUE THREAD

**Issue by j-brant** [guillep/pharo-core#10203] opened 2021-10-20 12:29 UTC
**Bug description**
Using a filter on a list in spec2 causes a OrderedCollection DNU #hasElementAt: sent from SpMorphicLIstDataSource>>hasElementAt:. The SpListPresenter>>prepareForFilteredDataSourceWith: method is assigning the collection to the model object instead of setting the value of the model. 

**To Reproduce**
1. Open "Spec2 Examples" from Help menu.
2. Select the Lists example.
3. In the Icons/Filter list, type anything in the filter.

**Expected behavior**
It shouldn't crash and the list should be filtered by the input.

**Screenshots**

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1564.sha.f5f541cb35c8609abfec418e35d5506715c7987d (64 Bit)

**Additional context**
Just changing the SpListPresenter>>prepareForFilteredDataSourceWith: to send #collection: to the model with the items fixes the crash, but deleting the filter text doesn't restore the previous items.

**Comment by Ducasse** [comment] 2021-10-20 14:00
@estebanlm

**Comment by estebanlm** [comment] 2021-10-20 15:52
well, first I couldn't reproduce it :) 
Second, the real error is that it still has a filter there (this is old and deprecated functionality), the real error is that demo is still using deprecated and to remove stuff, instead the new one.
I will close this while adding the correct issue here: https://github.com/pharo-spec/Spec/issues/1184

**Closed as completed by estebanlm** 2021-10-20 15:52 UTC
Labels: Type: Bug
