### ISSUE TITLE
Memory corruption 2

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#5163] opened 2019-11-19 09:25 UTC
On a Linux CI when saving we often get this error `CompiledMethod(Object)>doesNotUnderstand: key`.  This is turn leads to a `SmallInteger(Object)>doesNotUnderstand: run:with:in:`, which eventually leads to a segmentation fault. Any ideas how to debug this? It looks like an int is found instead if a compiled method. Happens with the latest Pharo 8 image and stable pharo 8 vm in 64 bit.

```
0xf2b9fe8 s SmallInteger(Object)>doesNotUnderstand: run:with:in:
         0xf2ba0c0 s MessageNotUnderstood>defaultAction
         0xf2ba1d8 s UndefinedObject>handleSignal:
         0xf2ba368 s Context>handleSignal:
         0xf2ba290 s MessageNotUnderstood(Exception)>signal
         0xf2ba420 s SmallInteger(Object)>doesNotUnderstand: run:with:in:
         0xf2ba4f8 s MessageNotUnderstood>defaultAction
         0xf2ba610 s UndefinedObject>handleSignal:
         0xf2ba7a0 s Context>handleSignal:
         0xf2ba6c8 s MessageNotUnderstood(Exception)>signal
         0xf2ba858 s SmallInteger(Object)>doesNotUnderstand: run:with:in:
         0xf2ba930 s MessageNotUnderstood>defaultAction
         0xf2baa48 s UndefinedObject>handleSignal:
         0xf2babd8 s Context>handleSignal:
         0xf2bab00 s MessageNotUnderstood(Exception)>signal
         0xf2bac90 s SmallInteger(Object)>doesNotUnderstand: run:with:in:
         0xf2bad68 s MessageNotUnderstood>defaultAction
         0xf2bae80 s UndefinedObject>handleSignal:
         0xf2bb010 s Context>handleSignal:
         0xf2baf38 s MessageNotUnderstood(Exception)>signal
         0xf2bb0c8 s SmallInteger(Object)>doesNotUnderstand: run:with:in:
         0xf2bb1a0 s Dictionary>scanFor:
         0xf2bb268 s Dictionary(HashedCollection)>findElementOrNil:
         0xf2bb320 s Dictionary>at:ifAbsent:
         0xf2bb3d8 s WorkingSession>accessMode
         0xf2bb4b0 s WorkingSession>isReadOnlyAccessMode
         0xf2bb568 s File>checkWritableFilesystem
         0xf2bb620 s File>basicOpenForWrite:
         0xf2bb6e8 s File>openForWrite:
         0xf2bb7a0 s File>openForWrite
         0xf2bb858 s File>writeStream
         0xf2bb910 s [] in SmalltalkImage>openLog
         0xf6a1f98 s BlockClosure>on:do:
         0xf6a2090 s SmalltalkImage>openLog
         0xf6a2188 s [] in SmalltalkImage>logDuring:
         0xf6a2240 s BlockClosure>ensure:
         0xf6a2368 s SmalltalkImage>logDuring:
         0xf6a2448 s SmalltalkImage>logError:inContext:
         0xf6a25d8 s StartupUIManager(UIManager)>logError:
         0xf6a27b8 s StartupUIManager(CommandLineUIManager)>handleError:log:
         0xf6a2aa8 s StartupUIManager>handleError:log:
         0xf6a2d20 s StartupUIManager(UIManager)>handleError:
         0xf6a2fc0 s [] in WorkingSession>runList:do:
         0xf6a34d0 s BlockClosure>cull:
         0xf6a36f8 s Context>evaluateSignal:
         0xf6a3868 s Context>handleSignal:
         0xf6a2938 s MessageNotUnderstood(Exception)>signal
         0xf6a2500 s CompiledMethod(Object)>doesNotUnderstand: key
         0xf6a2690 s SystemDictionary(IdentityDictionary)>scanFor:
         0xf6a2870 s SystemDictionary(HashedCollection)>findElementOrNil:
         0xf6a2b60 s SystemDictionary(Dictionary)>at:ifAbsent:
         0xf6a2dd8 s SystemDictionary(Dictionary)>at:
         0xf6a3078 s ClassSessionHandler>registeredClass
         0xf6a3588 s ClassSessionHandler>startup:
         0xf6a37b0 s [] in WorkingSession>runStartup:
         0xf6a3920 s [] in WorkingSession>runList:do:
         0xf6a29f0 s BlockClosure>on:do:
         0xf6a2c18 s [] in WorkingSession>runList:do:
         0xf6a2eb8 s Array(SequenceableCollection)>do:
         0xf6a3130 s WorkingSession>runList:do:
         0xf6a3418 s WorkingSession>runStartup:
         0xf6a3640 s WorkingSession>start:
         0xefcec70 s SessionManager>launchSnapshot:andQuit:
         0xefcef90 s [] in SessionManager>snapshot:andQuit:
         0xefcf240 s [] in BlockClosure>newProcess
```

**Comment by pavel-krivanek** [comment] 2019-11-19 18:48
as soon as you get `SmallInteger(Object)>doesNotUnderstand: run:with:in:`, it means that your object memory is corrupted and the image is useless. It probably happens during the snapshot primitive. As a workaround, I run at startup of the image 10 times GC. If the object memory is corrupted, it crashes immediately which is better than if it crashes randomly

**Comment by akgrant43** [comment] 2019-11-20 12:00
Hi Pavel,

This sounds like the VM crash that I'm currently trying to track down.  The issue is https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/444 

The earliest corruption I'm seeing is that the Frame Pointer for the currently executing process isn't being updated when the `BlockClosure` is being moved during garbage collection, resulting in a call stack looking like:

```
(gdb) call printCallStack()
    0x7ffffffe3f70 I SessionManager>launchSnapshot:andQuit: 0x1508860: a(n) SessionManager
    0x7ffffffe3fe0 I [] in SessionManager>snapshot:andQuit: 0x1508860: a(n) SessionManager
    0x7ffffffe4020 I [] in INVALID RECEIVER>newProcess 0x118a728 is in new space
```

Have you looked in to this in any depth and have you got any other insights to offer (I'm making slow progress, so any help is appreciated).

Thanks,
Alistair

**Comment by pavel-krivanek** [comment] 2019-11-20 15:22
I do not get this crash during the image life-time. To reproduce it, we have this script:
```
20 timesRepeat: [ClyFullBrowser openOnMethod: SourceSansProRegular class>>#fontContents.
    World doOneCycle ].

1 to: 20 do: [ :i | self inform: i asString. World doOneCycle. Smalltalk snapshot: true andQuit: false.
    ].
```
It is too high-level to be useful. We do 10-times GC before image saving and then 10-times GC after it. If I will have some time, I will try to find some more low-level script to reproduce it.

**Comment by Ducasse** [comment] 2019-11-21 08:20
Alistair 

What this test is showing is that we do not need large images to get a crash. 
This is what I reported on the mailing-list.
Stef

**Comment by akgrant43** [comment] 2019-11-21 09:14
> What this test is showing is that we do not need large images to get a crash.

Right, I'm starting with a minimal image (13M) and it's crashing at around 54M.

**Comment by Alisu** [comment] 2019-11-26 15:15
Maybe unrelated but yesterday during a refactor i deleted the image file resulting in some methods being 'corrupted'. By corrupted, i mean that i couldn't inspect them or call them.
I dunno the implementation of the snapshot but if it deletes and then recreates the image file may be the problem is here.

**Comment by MarcusDenker** [comment] 2022-04-29 11:26
Is this still happening? It looks a bit like one of the memory issues that where fixed in the VM..

**Comment by chisandrei** [comment] 2022-04-29 12:51
Most likely it is fixed. We did not encountered this any more.

**Comment by MarcusDenker** [comment] 2022-04-29 12:52
Thanks, I closed the issue

**Closed as completed** 2022-04-29 12:52 UTC
