### ISSUE TITLE
We should revisit definitionForNautilus 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2279] opened 2019-01-20 20:28 UTC
We can ask a class its definition and definition for nautilus. 
The definition returns old format
 'Object subclass: #Point
	instanceVariableNames: ''x y''
	classVariableNames: ''''
	poolDictionaries: ''''
	category: ''Kernel-BasicObjects'''

and definitionForNautilus

'Object subclass: #Point
	instanceVariableNames: ''x y''
	classVariableNames: ''''
	package: ''Kernel-BasicObjects'''

which is a lot better. 

Now it would be good make sure that changersorter and other tools can load the new version 
and rename definitionForNautilus into definition and definition in oldDefinition

**Comment by MarcusDenker** [comment] 2019-01-21 09:03
The problem is that changing #defintion breaks monticello and I did not yet manage to find out why.

**Comment by MarcusDenker** [comment] 2019-01-21 13:00
see: https://pharo.fogbugz.com/f/cases/14063/clean-up-definitionForNautilus

I will close the issue there.

**Closed as completed** 2019-05-24 14:41 UTC
Labels: Type: Bug
