### ISSUE TITLE
Debugger gets stuck

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#13724] opened 2023-05-14 10:23 UTC
I encounter a problem in which the debugger seems to get ‘stuck’. The following video demonstrates it, I repeatedly ‘debug’ `Transcript show: '?'`, the first two times there’s no problem, but the third time, clicking ‘Over’ seems to do nothing:

https://github.com/pharo-project/pharo/assets/1611248/da3e9901-c31b-4d1a-b546-2b201b482094

Build information: Pharo-11.0.0+build.689.sha.8986777f96ab65cba515d005d13487e0375fa85c (64 Bit)

**Comment by Rinzwind** [comment] 2023-05-14 10:56
When repeating the scenario (after reopening the image), I also had a case in which the debugger shows a stack drawing error:

<img width="400" src="https://github.com/pharo-project/pharo/assets/1611248/525539d1-3c2a-42e7-bdc9-05edd1b45110">

**Comment by Ducasse** [comment] 2023-05-14 19:49
Thanks for the report. The red square is a problem with thread and fonts :(

**Comment by MarcusDenker** [comment] 2023-05-15 07:24
This one might be 

https://github.com/pharo-spec/NewTools/pull/513

We merged the image part of the fix, but not the newtools part (and there we have to take care to merge it in both Pharo11 and Pharo12)

**Comment by uNouss** [comment] 2023-05-26 12:32
This bug is not reproducible in pharo12 neither in pharo11

**Comment by guillep** [comment] 2023-05-26 12:34
Thanks @uNouss, let's reopen this if this appears again

**Closed as completed by guillep** 2023-05-26 12:34 UTC
Labels: Type: Bug

**Comment by Rinzwind** [comment] 2023-05-29 09:42
This may have been VM-related: since posting this issue, I updated the 110-x64 VM in Pharo Launcher, I can now not reproduce this issue in the Pharo 11 build 689 image while I could easily reproduce it before. Sorry, hadn’t thought to check that.

**Comment by guillep** [comment] 2023-05-30 07:06
Could be strange that this is VM related, but who knows. In any case, good news you cannot reproduce it either!
