### ISSUE TITLE
Subclasses of Morph and Model should use self theme 

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2592] opened 2019-02-18 18:08 UTC
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22631
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 5 November 2018 3:43:59 pm
	
Description:
	
Instead of hardcoding `Smalltalk ui theme`. 

We should also add a rule and release test.

**Comment by jecisc** [comment] 2019-08-18 12:52
Still valid.

**Comment by hilaire** [comment] 2019-09-13 09:33
Duplicate of #2404

**Comment by MarcusDenker** [comment] 2019-09-17 12:53
#2404 has been merged, so this one is done, too?

**Closed as completed by MarcusDenker** 2019-09-17 12:53 UTC
