### ISSUE TITLE
Remove Text-Edition package

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5936] opened 2020-03-18 20:22 UTC
Because now it is duplicated of Rubric and we are nearly there to remove it with the pluggable text morph and friends.

**Comment by Ducasse** [comment] 2020-03-18 20:26
But PluggableListMorph is still used.

**Comment by guillep** [comment] 2020-03-18 20:28
This is related to https://github.com/pharo-project/pharo/pull/5020
But I don't get @jecisc to answer me :)

**Comment by MarcusDenker** [comment] 2021-01-27 12:21
This is a duplicate of https://github.com/pharo-project/pharo/issues/2717
(cleaning up text editor)

**Closed as completed by MarcusDenker** 2021-01-27 12:21 UTC
Labels: Type: Cleanup, Project: Graphics
