### ISSUE TITLE
Pharo 7/8 on Mac Mouse/Touchpad Left/Right scroll performs incorrect function

### ISSUE THREAD

**Issue by wyattbiker** [guillep/pharo-core#4432] opened 2019-08-27 00:18 UTC
Pharo both 7 and 8 (also Squeak)
Mac OS X Mojave and older versions

For any pane (e.g. method code, comments, playground, transcript, etc), when you use side scroll (left/right) with trackpad (2 fingers left/right) or mouse (such as Magic Mouse), the behavior **should NOT highlight** the text under the cursor. In addition if it is a list such as classes it scrolls the highlight up/down.

The behavior should be to ONLY scroll the pane/window data left/right if it has a horizontal scroll bar (Or whatever the default Mac behavior is).

![image](https://user-images.githubusercontent.com/930478/63730997-bcf04780-c83b-11e9-8a7f-dd5c66e0302c.png)

**Comment by StephanEggermont** [comment] 2019-09-17 08:36
That is likely related to the way we get events from the vm. There have been lots of discussions about that, and some clean up work. I don't know what the exact status is

**Comment by wyattbiker** [comment] 2019-09-17 13:36
Is this a Mac OS X issue only?

**Comment by Ducasse** [comment] 2019-09-17 14:31
It is fixed with the forth coming headless vm. 
We can close this issue. We waited for years to got events right :)

**Comment by Ducasse** [comment] 2019-09-17 14:32
Once we have the new VM will check what is wrong. Right now this is not possible since we do not get the correct events. I would close the issue for now. And reopen it if it is needed on the headless vm.

**Comment by MarcusDenker** [comment] 2023-02-03 13:44
Can you check with the current version? I can not reproduce it

**Closed as completed by MarcusDenker** 2023-02-03 13:44 UTC
