### ISSUE TITLE
Random >> nextInt should fail early when argument is FloatInfinity

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#3434] opened 2019-05-29 06:19 UTC
Truncated refuse to truncate infinite number and throws an error.

Either this method should fail early or it should have a different way to handle float infinity 

```smalltalk
Random >> nextInt: anInteger
    "Answer a random integer in the interval [1, anInteger].
    Handle large numbers too (for cryptography)."

    anInteger strictlyPositive ifFalse: [ self error: 'Range must be positive' ].
    anInteger asFloat isInfinite
        ifTrue: [^(self privateNextValue asFraction * anInteger) truncated + 1].
    ^ (self privateNextValue * anInteger) truncated + 1
```

**Comment by kasperosterbye** [comment] 2019-09-13 13:50
I have not been able to reproduce this problem in any other way than passing #nextInt: a `Float infinity` as argument. 

The argument kind of expects an integer, so I do not see a problem.

Could you provide an example of what might input cause the program to fail?

One could add a test `anInteger isInfinite ifTrue: [ self error: 'Infinity not allowed as argument' ]`.

**Comment by hogoww** [comment] 2019-09-13 14:04
I agree on both your statements.
I just think the computation is useless, since it fails in the next method. 
Hence the method could either be simplified, or as you said add an error statement as you did

**Comment by kasperosterbye** [comment] 2019-09-13 16:36
Pharo libraries are rather inconsistent in their view on checking or failing on violated preconditions. That seems to be the case with most large legacy frameworks (that inconsistency).

In the concrete situation the `anInteger asFloat isInfinite` happens when `anInteger` is larger than `Float fmax`. 

I could make a PR where which include said test:
`anInteger isInfinite ifTrue: [ self error: 'Infinity not allowed as argument' ]`

**Comment by hogoww** [comment] 2019-09-14 05:52
"In the concrete situation the anInteger asFloat isInfinite happens when anInteger is larger than Float fmax."
If it's just a way to check that, a comment might be enough.

**Comment by kasperosterbye** [comment] 2021-02-01 10:02
The comment has been added back in 2019 (by me) - I suggest to close it now.

**Closed as completed** 2021-02-01 10:04 UTC
