### ISSUE TITLE
Embedded argument names are lost and break FFI

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5876] opened 2020-03-10 16:55 UTC
To reproduce the problem
- remove sources and changes file
- call github api.

**Comment by MarcusDenker** [comment] 2020-03-11 07:19
yes: https://github.com/pharo-project/pharo/issues/5129

If we would not have iceberg being an external project, I would have just done the change... like this is waits for someone who knows how to do it.

**Comment by guillep** [comment] 2020-03-11 09:04
This is then a duplicate, I'll close it.

Is this then broken since the beginning of november?
And it was left broken on purpose?

This is a clear example that the "let's integrate this now, fix it later" does not work.
Because if the original PR author or the merger do not take responsibility for the further action, the "fix it later" means "fix it never".

We should stop integrating half baked issues.
Yes, it seems a nice pattern, but it is only good if the people involved takes responsibility of the further step.

Now the problem is that we have 4-5 months of distance between the original issue, and this, plus a Pharo8 release in the middle. The more time it takes to fix these kind of issues, the more complicated it becomes to fix them.

> If we would not have iceberg being an external project, I would have just done the change... like this is waits for someone who knows how to do it.

This is no excuse. Everybody is able to do PRs to iceberg. Moreover, the issue and the fix were apparently identified. So there is no archeology to be done, no much more understanding.
Merges should not happen if we do not understand the reach of the changes.
That's a recipe for disaster: we integrate things we do not know/do not understand/do not control.

**Closed as completed by guillep** 2020-03-11 09:04 UTC
Labels: Status: Duplicate
