### ISSUE TITLE
Spotter does not close when clicking on the cross

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#13166] opened 2023-03-28 07:30 UTC
**Bug description**
Spotter does not close when clicking on the cross

**Comment by MarcusDenker** [comment] 2023-03-28 07:43
This PR is related:

https://github.com/pharo-spec/NewTools/pull/421

**Comment by MarcusDenker** [comment] 2023-03-28 09:24
"
The input field is now light gray (or whatever according to the smalltalk theme), so it is obvious that the x cross belongs to the input field (and clears it) and does not belong to the whole modal window (and mistaken to a close button).
"

**Comment by MarcusDenker** [comment] 2023-03-28 09:33
There is https://github.com/pharo-project/pharo/issues/10993, too

**Comment by MarcusDenker** [comment] 2023-03-31 10:30
As this is a duplicate of https://github.com/pharo-project/pharo/issues/10993 (a fix is proposed there), I close this

**Closed as completed by MarcusDenker** 2023-03-31 10:30 UTC
Labels: Type: Bug
