### ISSUE TITLE
Use faster string primitives

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3156] opened 2019-04-10 11:47 UTC
VMMaker.oscog-sk.2367
Author: sk
Time: 19 April 2018, 12:02:35.661622 pm
UUID: 0c2401e3-1450-4f73-8e81-958f50171595
Ancestors: VMMaker.oscog- nice.2366

** new primitive to compare strings (slang + JIT)
answers negative smi, 0 or positive smi (instead of 1, 2 or 3 in the MiscPlugin)

* Slang (primitiveCompareWith)
order is optionnal. 
comparison loop performed in rawCompare: string1 length: strLength1 with: string2 length: strLength2 accessBlock: accessBlock

* JIT (genPrimitiveStringCompareWith)
the JIT primitive does not take order as parameter (assumed asciiOrder)
quick jump if one of the strings is empty

**Comment by Ducasse** [comment] 2019-04-10 11:47
we should not use anymore 

compare: string1 with: string2 collated: order
	"Return 1, 2 or 3, if string1 is <, =, or > string2, with the collating order of characters given by the order array."

	| len1 len2 c1 c2 |
	<primitive: 'primitiveCompareString' module: 'MiscPrimitivePlugin'>
	
	<var: #string1 declareC: 'unsigned char *string1'>
	<var: #string2 declareC: 'unsigned char *string2'>
	<var: #order declareC: 'unsigned char *order'>

	len1 := string1 size.
	len2 := string2 size.
	1 to: (len1 min: len2) do:
		[:i |
		c1 := order at: (string1 basicAt: i) + 1.
		c2 := order at: (string2 basicAt: i) + 1.
		c1 = c2 ifFalse: 
			[c1 < c2 ifTrue: [^ 1] ifFalse: [^ 3]]].
	len1 = len2 ifTrue: [^ 2].
	len1 < len2 ifTrue: [^ 1] ifFalse: [^ 3].

**Comment by Ducasse** [comment] 2019-04-10 12:10
Hi Stephane,
If you google 'vm-dev VMMaker.oscog-sk.2367'
and click one of the first hits https://marc.info/?l=squeak-vm-dev&m=152413936110744&w=2

you'll see the changes from Sophie:
The new InterpreterPrimitives>>primitiveCompareWith should be linked to primitive 158.
(and only for ByteString comparison).

**Comment by jecisc** [comment] 2022-02-02 17:08
Is there any news on this change?
It's a great performance improvement. I tried to integrate it some years ago but I remember someone else in the team wanted to do it but it seems that the code in Pharo 9 is still using the old primitive.

**Comment by astares** [comment] 2022-02-02 18:04
This addition is from 2018:

https://clementbera.wordpress.com/2018/02/17/massive-string-comparison-performance-boost-up-coming-in-the-cog-vm/

**Comment by jecisc** [comment] 2022-02-06 01:19
I tried to use primitive 158 but it end up in a primitive failure. Is this primitive still in the Pharo VM?

**Comment by jecisc** [comment] 2022-02-06 01:25
I see my error. 
I tried to reproduce what was done in https://github.com/pharo-project/pharo/pull/6419/files
But the new primitive needs to be instance side and not class side.

<blockquote><img src="https://avatars.githubusercontent.com/u/21278554?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/6419">[WIP] String primitive update by hogoww · Pull Request #6419 · pharo-project/pharo</a></strong></div></blockquote>

**Comment by jecisc** [comment] 2022-02-06 01:35
I succeed to add the primitive on ByteString instance side but when I try to use it to replace the old primitive in the comparison of the String class my image becomes unresponsive. 
Maybe this can only be done by updating the text files by hand and regenerating a new image?

**Comment by jecisc** [comment] 2022-02-06 01:47
I found my problem. ByteSymbols are also considered as ByteString and thus also need to implement the primitive for the change to be able to work.

**Comment by jecisc** [comment] 2022-02-06 01:50
I have an image with the change applied and things seem to work. 

I'll probably not have the time to do the PR now but I'll try to do it at some point.

**Comment by Ducasse** [comment] 2023-02-09 11:32
Nice to see some work on it.

**Comment by MarcusDenker** [comment] 2023-02-09 11:34
The code is in, to allow easier debugging of the remaining problems, see merged PR
https://github.com/pharo-project/pharo/pull/12504

**Comment by jecisc** [comment] 2023-02-09 11:55
We fixed the failing case we found with @PalumboN in the VM! When the vm will be released we’ll be able to try again to use it. 
Also, since Pablo wants to CI to build with the latest VM, we’ll also be able to try to do a PR before the new VM is released :)

**Comment by jecisc** [comment] 2023-02-09 12:12
```st
"Current comparison"
[ ByteString compare: 'Test' with: 'Tast' collated: ORDER ] bench  "'17531863.082 per second'"

"New comparison with collated parameter"
[ ('Test' compareWith: 'Tast'  collated: ORDER)] bench. "'53961901.878 per second'"

"New version without the collated parameter (uses AsciiOnder by default)"
[ ('Test' compareWith: 'Tast')] bench. "'92902843.231 per second'"
```

**Comment by MarcusDenker** [comment] 2023-03-20 14:44
DONE

**Closed as completed by MarcusDenker** 2023-03-20 14:44 UTC
