### ISSUE TITLE
When compiling a classside method, we get back to instance side...

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#12280] opened 2023-01-08 20:14 UTC
Quit annoying. 
- compiled a class side method
- and you get back on the instance side if you want to read what you compiled!

**Comment by hernanmd** [comment] 2023-01-23 09:39
I couldn't reproduce it in latest P11:
![class_side](https://user-images.githubusercontent.com/4825959/214006561-1829ebef-07e1-4c71-80ef-040a53beb67b.gif)

What happens instead is that 2 class side tabs are opened, besides the one which contain the new class method. I will open a new issue for this problem.

**Comment by ValentinBourcier** [comment] 2023-01-30 10:56
I cannot reproduce @Ducasse issue's either, I get the same result as @hernanmd.
What about closing this issue or linking it to : https://github.com/pharo-project/pharo/issues/12408 ?

**Comment by guillep** [comment] 2023-01-30 11:01
Yes @ValentinBourcier , I agree. Thanks for the review.
When we have a better way to reproduce this issue we will manage it :)

**Closed as completed by guillep** 2023-01-30 11:01 UTC
Labels: Type: Bug, Priority: Critical
