### ISSUE TITLE
In place edition of inspector fails

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5991] opened 2020-03-25 11:17 UTC
**Describe the bug**
In the inspector I wanted to do an in place edition (shift + click on a value, update it and save).

It fails: 

```Smalltalk
UndefinedObject(Object)>>doesNotUnderstand: #selectedClassOrMetaClass
UndefinedObject>>doesNotUnderstand: #selectedClassOrMetaClass
CompletionEngine>>openMenu
[ editor atCompletionPosition ifTrue: [ self openMenu ] ] in [ (Delay forMilliseconds: NECPreferences popupAutomaticDelay) wait.
UIManager default defer: [ editor atCompletionPosition ifTrue: [ self openMenu ] ] ] in CompletionEngine>>resetCompletionDelay in Block: [ editor atCompletionPosition ifTrue: [ self openM...etc...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycle
WorldMorph class>>doOneCycle
[ [ WorldMorph doOneCycle.
Processor yield.
false ] whileFalse: [  ] ] in MorphicUIManager>>spawnNewProcess in Block: [ [ WorldMorph doOneCycle....
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
```

 - Version: Pharo 8.0

**Comment by Ducasse** [comment] 2020-03-25 14:41
Does it fail in P9

**Comment by MarcusDenker** [comment] 2020-03-25 14:42
I think this was fixed in P9, I will check

**Comment by Ducasse** [comment] 2020-03-27 13:57
Cyril does it fail in P9 because I could really understand how to reproduce it.

**Comment by MarcusDenker** [comment] 2020-03-27 13:59
No, I fixed it in P9 long time ago and the PR is a back port fo that fix

**Comment by MarcusDenker** [comment] 2020-04-07 09:47
this is done: fix was backported

**Closed as completed by MarcusDenker** 2020-04-07 09:47 UTC
