### ISSUE TITLE
A new method gets make when you try to use the debugger to make a new class 

### ISSUE THREAD

**Issue by ghost** [guillep/pharo-core#9956] opened 2021-09-14 09:56 UTC
**Bug description**
When I have a test and it uses `aNewClass new`   the new class and also a new method is made 

**To Reproduce**
1.  make a test which uses  setUp with `myClass := aNewClass new in it
2.  Press on the dot to run the tests. 
3.  the debugger pops up that the class and a new method cannot be understood
4.  press create 

**Expected behavior**
Only the class schould be made 

**Version information:**
 - OS: Windows 10
 - Version: 
 - Pharo Version  9

**Comment by jordanmontt** [comment] 2021-09-14 10:05
We were discussing this on the Discord channel. Actually the tests passes but the first time a debugger is opened because a `new` method is created on the **instance** side with `shouldNotBeImplemented` code.

The expected behaviour should be that if you have `var := NonImplementedClass new`. The debugger should be smart enough to not create the new method. And not creating it on the instance side.

You can reproduce the error if you
1) file-in this class
2) run the test
3) create a class using the debugger
4) click ok when it ask you the name of the protocol (this is wrong, it shouldn't ask anything).

Actually in the 4th step if you click `cancel` the `new` method is not created and everything is ok. This is not intuitive for the user.

[ABSTest.st.zip](https://github.com/pharo-project/pharo/files/7160889/ABSTest.st.zip)

**Comment by gypsydave5** [comment] 2021-09-15 12:02
Been having a crack at fixing this... tried testing whether the new class responds to the original message in the `createMissingClass` method:

```smalltalk
StDebugger >> createMissingClass

	| message exception variableNode |
	self flag: #DBG_MISSINGTEST.
	message := self interruptedContext tempAt: 1.
	exception := self interruptedContext tempAt: 2.
	variableNode := exception variableNode.
	[ 
	| newClassBinding |
	self halt.
	newClassBinding := OCUndeclaredVariableWarning new
		                   node: variableNode;
		                   defineClass: variableNode name.
	(newClassBinding value respondsTo: message selector) ifFalse: [ 
		self createMissingMethodFor: message in: newClassBinding value ] ]
		on: Abort
		do: [ ^ self ].

	self debuggerActionModel restartContext: self interruptedContext
```

This works _somewhat_ as it does prevent the call to `createMissingMethodFor:` in here (yay!) but the debugger will still go on to attempt to define the missing method on the instance anyway; it goes instead to `#new was sent to nil`

![image](https://user-images.githubusercontent.com/5469544/133429513-f1ebaa6d-fbc3-45f6-8cb0-0ce3ef1bac29.png)

so it's like the reference to `nil` isn't getting updated to the created class in the running process? Not sure how to handle that... @StevenCostiou if you've got five minutes I'd appreciate a bit of mentoring!

**Comment by StevenCostiou** [comment] 2021-09-15 12:14
Your solution looks a good starting point.
Normally, the context should be updated by the call to `restartContext:` (at the end of the method).
Possibly, it does not update the context correctly, or there is a strange case with the `DynamicMessageImplementor` (whose job is to create new methods from the debugger).

When you get there (your screenshot), what  is the result of inspecting `AngryAssssHat`? Is this a class, and does it understand `new` (it should)?

**Comment by StevenCostiou** [comment] 2021-09-15 12:25
Ok it looks like it is because the method on the stack is not updated: the undefined variable is still undefined in the compiled method.
Restarting one context before in the stack properly works.
@MarcusDenker how to handle this undefined variable case? (provided my analysis is correct)

**Comment by gypsydave5** [comment] 2021-09-15 12:39
> When you get there (your screenshot), what is the result of inspecting `AngryAssssHat`? Is this a class, and does it understand `new` (it should)?

Maybe not the best class name... I'm getting through them quickly.

Yes, `AngryAssssHat` is defined. And if I evaluate the code in the debugger again I actually get the expected result - another debugger opens with the failed assertion.

**Comment by gypsydave5** [comment] 2021-09-17 13:00
> Ok it looks like it is because the method on the stack is not updated: the undefined variable is still undefined in the compiled method.
> Restarting one context before in the stack properly works.
> @MarcusDenker how to handle this undefined variable case? (provided my analysis is correct)

I concur with this analysis, and I'm afraid I know too little about Pharo to get much further.

But I'm still quite enjoying blindly groping around in the dark

**Comment by ghost** [comment] 2021-09-22 05:41
@StevenCostiou  @MarcusDenker  any news on this matter ?

**Comment by MarcusDenker** [comment] 2021-09-22 07:17
Not yet... too many things on the plate... I will block time I hope friday afternoon for this

**Comment by ghost** [comment] 2021-09-22 11:55
oke, thanks for the message.

**Comment by ghost** [comment] 2021-10-16 10:50
any news here ? @MarcusDenker

**Comment by StevenCostiou** [comment] 2021-10-23 15:34
Bugfix here https://github.com/pharo-spec/NewTools/pull/309
I have not found a way to do the PR against Pharo, so I did it against NewTools.
@estebanlm could you backport it to Pharo9 if it gets merged to NewTools?

**Comment by estebanlm** [comment] 2021-10-24 05:42
because is NewTools. To do a PR "against pharo", you do a PR against Pharo10 branch in NewTools :)

**Comment by estebanlm** [comment] 2021-10-24 05:46
and you have one failing test: testDoBrowseSendersOfClassNameShouldNotFindIfNotInEnvironment

**Comment by StevenCostiou** [comment] 2021-10-24 10:50
Hm, I'll try to do a PR against Pharo 10.
About the test, it is odd, it does not seem related to my changes and it works in my image.
I will investigate.

**Comment by StevenCostiou** [comment] 2021-11-15 15:43
Is there a way to trigger the tests again?

**Closed as completed** 2021-11-24 09:45 UTC
Labels: Type: Bug
