### ISSUE TITLE
Fonts are blurry under high resolution screen

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#10656] opened 2021-12-13 17:35 UTC
**Bug description**
Left ok. Right blurry
![image](https://user-images.githubusercontent.com/4706329/145859960-64968eb4-feb9-4cc5-8a98-277a11320117.png)

The issue appears at the same time than fixing #10319 and likely to be related to #8688.

**To Reproduce**
1. Go to huge screen where the scale of the screen is more than 100%
2. Open Pharo
3. See that the font is blurry

**Expected behavior**
No blurry font and scaling correct

**Screenshots**
See above

**Version information:**
 - OS: Win10
 - Pharo Version Pharo 9.0.0
Build information: Pharo-9.0.0+build.1573.sha.0e09d756fc99383cbb498565200d9e5e9841ce11 (64 Bit)

**Expected development cost**
High

**Additional context**
Lifeware tagged

**Comment by astares** [comment] 2021-12-13 23:03
@VincentBlondeau / @tesonep / @guillep 

Yes - we had a solution originally:
- ISSUE: Pharo 9 looked bad on Windows HiDPI Devices (Microsoft Surface)
   https://github.com/pharo-project/pharo/issues/9715 
- PR: it was fixed with a PR: https://github.com/pharo-project/pharo/pull/9716


Later it got reverted through
- ISSUE: OSSDL2BackendWindow>>#fetchDPI seems broken
   https://github.com/pharo-project/pharo/issues/10319
- PR: 10319-OSSDL2BackendWindowfetchDPI-seems-broken
   https://github.com/pharo-project/pharo/pull/10325   
   
If you check the comments in https://github.com/pharo-project/pharo/pull/10325 I already pointed out that new proposed changes this will revert the original fix and @tesonep replied that there will be a setting. I guess this setting is still missing/pending.

**Comment by sonibla** [comment] 2021-12-23 10:36
By looking quickly it seems Pharo can't support HiDPI because `OSWorldRenderer>>actualScreenSize` takes into account screen scale, on HiDPI devices it means `OSWorldRenderer>>actualScreenSize` will return a too low value.
For example on my device `OSWorldRenderer>>actualScreenSize` returns (1920@1138) while the widow size (in pixels displayed on the physical screen) is (3840@2275)
Then the too small extent goes to OSWindowFormRenderer, and all the morphs are computed based on this value.
It's not that simple to fix it however, modifying `OSWorldRenderer>>actualScreenSize` to return the correct pixel number will break the mouse position and the scaling
From Lifeware side it's already better to have a correct scale but blurry screen (after https://github.com/pharo-project/pharo/pull/10325), than having a too small scale and still a blurry screen after setting a custom scale in Pharo appearance settings (before https://github.com/pharo-project/pharo/pull/10325)
The issue is that having a blurry screen is an incentive not to use Pharo

**Comment by svenvc** [comment] 2021-12-23 10:43
I also think this is an important and sensitive issue: it gives a really bad first impression.

**Comment by Ducasse** [comment] 2021-12-23 12:18
May be adapting and providing a specific startup preferences can help.
For the HDPI we need at least 6 months of work and we do not have them now.

**Comment by sonibla** [comment] 2021-12-23 14:15
@VincentBlondeau how did you get the non blurry example on the left of your image?

This is pharo 7, 8, 9, 10, they all look the same for me
![blurry fonts](https://user-images.githubusercontent.com/49032546/147252132-3b9b936a-59e3-4301-9736-11591728649b.PNG)

**Comment by fmqa** [comment] 2022-08-15 21:35
A temporary workaround can be achieved by patching `OSWorldRenderer>>screenScaleFactor` like this (just replace `self windowScaleFactor` with 1 or comment it out). This works for me on a 2560x1440 2K display, so YMMV. Also, note that I am using the native libSDL2 (i.e. `libsdl2-2.0-0 2.0.20+dfsg-2ubuntu1.22.04.1`) provided by my distribution instead of the Pharo-Bundled version.

It's possible to fix this, but I'm not well-versed in Pharo's code deeply enough to guarantee a correct solution. Also, unfortunately I do not have an non-hidpi display to test against.   

![Screenshot](https://user-images.githubusercontent.com/7354509/184721081-4e8c15a2-5b47-4e10-8cfe-a1cdaeac0da1.png)

**Comment by fmqa** [comment] 2022-08-16 19:29
The following patch works for me on 2K/1440p display as well as an older laptop with an 1080p FHD monitor:
Not very well-versed in Pharo's code and I don't any Retina display to test with, so YMMV

```patch
--- orig/src/OSWindow-Core/OSWorldRenderer.class.st	2022-08-16 21:16:39.763266326 +0200
+++ src/OSWindow-Core/OSWorldRenderer.class.st	2022-08-16 21:20:33.905443917 +0200
@@ -278,7 +278,7 @@
 
 { #category : #'scale factor' }
 OSWorldRenderer >> windowScaleFactor [
-	^ osWindow ifNil: [ 1 ] ifNotNil: [ osWindow screenScaleFactor max: 1 ]
+	^ osWindow ifNil: [ 1 ] ifNotNil: [ osWindow screenScaleFactor min: 1 ]
 ]
 
 { #category : #accessing }
```

![Screenshot](https://user-images.githubusercontent.com/7354509/184966053-907ad8da-e77d-427b-a0f2-cd4b592fcd3c.png)

**Comment by Ducasse** [comment] 2022-08-17 04:34
We should really push the HPDI....

**Comment by uchuugaka** [comment] 2022-09-11 08:54
Nothing would make me happier and more willing to give Pharo (or Squeak) a real serious go.

**Comment by Ducasse** [comment] 2022-09-11 08:57
Us too. Where can I find the code? 
Ok seriously this is not because we do not want that Pharo is not in HDPI. 
First this is a question of resources, second this is a question of resources and third this is a question of speed (because we have a running version but it is slow to move windows and we need to see how to optimise it).
So the more the people help for other tasks the more chance we have that we can calmly have a look.

**Comment by uchuugaka** [comment] 2022-09-11 09:57
Where in the code needs a look? I can look for macOS, but know nothing about for Windows or Linuxes or BSDs.
I suspect the handling will be more or less branching along those lines (if it does not already).

**Comment by Ducasse** [comment] 2022-09-11 10:08
No we do not branch :) this is not like an case statement. 
Now we can ask Pablo and Carolina and you can try the version we have. @tesonep @carolahp

**Comment by uchuugaka** [comment] 2022-09-11 10:12
hmm, seems like things rely on SDL2 which is in C and I am sure supports HiDPI for a long time  now :) 
Is Pharo using an FFI to interact with SDL2 calls?

**Comment by Ducasse** [comment] 2022-09-11 10:46
Yes Pharo is using SDL2 as back-end. The key point is how to rerender an object trees fast enough so that you can move a window with animations inside and that animations are smooth.

**Comment by Ducasse** [comment] 2022-09-11 10:47
This is just oh let us do a simple FFI call. We are not that stupid.

**Comment by Ducasse** [comment] 2022-09-11 10:54
Let us wait that Pablo and Carolina tell us where the code is.

**Comment by uchuugaka** [comment] 2022-09-11 11:43
Makes sense. 
part of me wonders if the abstraction layering is where some trouble is. Like if it were a true VM, all major OS platforms have hypervisor APIs today… that would streamline a lot be also limit other things and literally be an OS. 
If the classic SmallTalk image were not used but rather became more of a cross platform API using like Qt or Tk or something similar, it could also be a very powerful thing. 
but that’s me thinking out loud. Neither of those would be simple and really solve different problems.

**Comment by Ducasse** [comment] 2022-09-11 12:11
indeed and doing is often more demanding :)
You have to have an execution engine and this is what we are doing. And Pharo should be versatile.

**Comment by PierreLouisPAUGAM** [comment] 2023-01-30 14:14
Hello, I tried opening Pharo on a 3840x2160 screen with Windows scaling set to 150% and found out everything was blurry :

![Exemple](https://user-images.githubusercontent.com/58030198/215500437-2c0eaee8-c1f5-444e-be36-db3f561629f9.png)

I don't open a new issue as I think this is related to this one, has a solution been found since then @Ducasse or should I switch to another screen for now ?

**Comment by hernandp** [comment] 2023-11-26 03:09
what is the status of this?  I'm using Pharo 11 with 4K display and suffering blurry text.

**Comment by Ducasse** [comment] 2023-11-26 17:40
We have the same problems.
You can check and report two projects Rinzwind and form-scene-graph see below

## Rinzwind
You can check the following check @Rinzwind 

https://github.com/pharo-project/pharo/pull/15561 parts pasted below

I updated, and made two small improvements to, the ‘Retina display’ scaling experiment from earlier pull requests: commits 1cdeaf1, 0ff236a and 139a5bb (which are not included in this pull request).

If you want to try it out:

- Create an image in Pharo Launcher using Pharo 12 build 1128 as the template
- Close the ‘Welcome’ window
- Repair the repository ‘pharo’ by cloning from GitHub using ‘Rinzwind’ as the ‘Owner name’ and ‘pharo’ as the ‘Project name’
- Check out the branch ‘scaling-canvas-tryout-14’ from ‘origin’
- Close the ‘Repositories’ window (its icons will be broken at this point, but just click the usual location of the closing button)
- Open the extra world by doing OSWorldRendererScalingCanvas example; or, to use ScalingCanvas for drawing the main world:

-Do OSWorldRendererScalingCanvas isApplicable: true, and save and quit the image
-Open the image again and do World scaleFactor: 0.5

To revert, do World scaleFactor: 1 and OSWorldRendererScalingCanvas isApplicable: false, then save and reopen the image

**Comment by Ducasse** [comment] 2023-11-26 17:45
## Form-scene-graph

You can also check the code of 

- https://github.com/carolahp/form-scene-graph
- Check the comment of the original forked project https://github.com/desromech/form-scene-graph
and report if it is working for you.

So we are concerned about it and the form-scene-graph was already a long effort that we paid with our team money.

Now if people want to put money on the table to change our effort we are all ears open. 


<blockquote><img src="https://opengraph.githubassets.com/2958b78e3bf8c7b51cc29699b91c7838736f1d5e0f2ec66bca818b8298435ac9/carolahp/form-scene-graph" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/carolahp/form-scene-graph">GitHub - carolahp/form-scene-graph: A Gtk Scene Graph inspired rendering framework for Pharo</a></strong></div><div>A Gtk Scene Graph inspired rendering framework for Pharo - GitHub - carolahp/form-scene-graph: A Gtk Scene Graph inspired rendering framework for Pharo</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/963239c9d6da2bfb0c47c0c206e24c2f31bcc36396add6e89af479ec67dae4a3/desromech/form-scene-graph" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/desromech/form-scene-graph">GitHub - desromech/form-scene-graph: A Gtk Scene Graph inspired rendering framework for Pharo</a></strong></div><div>A Gtk Scene Graph inspired rendering framework for Pharo - GitHub - desromech/form-scene-graph: A Gtk Scene Graph inspired rendering framework for Pharo</div></blockquote>

**Comment by Rinzwind** [comment] 2023-12-04 09:20
Instead of following the instructions from pull request #15561 pasted above, in the latest Pharo 12 builds, in which pull request #15647 was merged, you can just set the ‘canvas scale factor’ setting:

<p align="center">
<img width="500" alt="287102659-d08cb129-9fec-4e70-9c49-e2d17c36459d" src="https://github.com/pharo-project/pharo/assets/1611248/49940078-fde5-4ba0-a1dc-c0dcf9f196ce">
</p>

Note that I use a MacBook and don’t have a Windows or Linux machine, except virtual ones, so I’m not entirely sure what the effect is on those platforms, but please do try it out!

**Comment by Rinzwind** [comment] 2024-04-23 18:39
There’s a setting now to let the canvas scale factor be set automatically (since Pharo 12 build 1494):

<p align="center">
<img width="487" src="https://github.com/pharo-project/pharo/assets/1611248/65532ddd-95b9-41c8-a4df-73a0580f2bc0">
</p>

As mentioned in pull request #16479, it may need some further testing, especially on Windows and Linux, so please do leave some feedback when you’ve given it a try!

**Comment by ccfontes** [comment] 2024-04-28 03:19
Trying to find that 1494 build to no avail.
Not here yet right?: https://pharo.org/download

<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo.org/download">Pharo - Download</a></strong></div></blockquote>

**Comment by Rinzwind** [comment] 2024-04-28 08:25
If you want to try build 1494 specifically, you can get [‘Pharo12.0-SNAPSHOT.build.1494.sha.6e47d25.arch.64bit.zip’](https://files.pharo.org/image/120/Pharo12.0-SNAPSHOT.build.1494.sha.6e47d25.arch.64bit.zip) from the [directory ‘120’ within ‘image’ on ‘files.pharo.org’](https://files.pharo.org/image/120/). Later Pharo 12 builds include the setting as well, so you can also just get the latest one through [Pharo Launcher](https://pharo-project.github.io/pharo-launcher/) using the template ‘Pharo 12.0 - 64bit (stable)’.

The link ‘64bit (default)’ for ‘Pharo image’ in the section ‘Pharo standalone’ on the website’s ‘Download’ page is currently broken, I have opened [pharo-website pull request #71](https://github.com/pharo-project/pharo-website/pull/71) to fix that.

**Comment by ccfontes** [comment] 2024-04-28 09:33
Thanks! Also, ended up fetching the image using the New icon in the launcher. Btw, total newbie here.
Anyways, font issue is fixed (macOS Sonoma here).
Now I can get started with Pharo without my eyes hurting. 💯

**Comment by macta** [comment] 2024-05-27 13:43
Can this be closed now? There is a setting in Pharo 12 under - World renderer canvas scaling - Canvas Scale Factor.

Setting this to 2 on my mac with a retina screen makes it clear (and the same on a large screen).

<img width="458" alt="image" src="https://github.com/pharo-project/pharo/assets/5553623/8c3a9ed8-be30-4287-b7c4-fdd0bcf8bb1d">

**Closed as completed** 2024-07-12 10:50 UTC
Labels: Type: Bug
