### ISSUE TITLE
Strange behaviour in 'ProfStef next' command

### ISSUE THREAD

**Issue by stephensmith9** [guillep/pharo-core#2360] opened 2019-01-27 18:54 UTC
On latest Win64 build, hitting Ctrl-D on 'ProfStef next' also moves the highlight down by one in the tree control in the main Welcome window. On each Ctrl-D the highlight continues to move down, until it reaches the last one (Getting Help), where it remains.

![pharo7-64-win-behaviour](https://user-images.githubusercontent.com/7142084/51805400-b57fa600-223a-11e9-9805-69b4868f6200.png)

**Comment by Ducasse** [comment] 2019-01-27 20:02
Thanks. This is a super strange and unexpected behavior.

**Comment by pavel-krivanek** [comment] 2019-01-27 20:28
A long time ago I looked at a similar issue related to the next message in the ProfStef and I must say that it is not unexpected behavior for me :-) The way how it works is really ugly hacked and does not work outside of the very specific conditions. Unfortunately, it is not easy to fix too.

**Comment by Ducasse** [comment] 2019-01-27 20:58
Ok then in that case it may be better to rewrite it use Spec2 :)

**Comment by Psy-Kosh** [comment] 2019-02-01 05:10
I just discovered this issue too and came to submit report before finding it here.

A bit of experimentation suggests it affects more than the welcome window. I can confirm it also affects the help browser... but it's a bit weird how. Specifically, it seems it will affect whichever window, with such an index menu, is the one most recently on top prior to profstef being on top.

So if I have the help browser and the welcome window open, then which one gets advanced depends on which one was last on top prior to be clicking on the profstef window.

Also, the effect happens with ProfStef previous. having the effect of moving either of those in the other direction.

**Comment by maxbareis** [comment] 2019-08-02 13:38
Did not get the point why this is a strange behaviour. In ProfStef>>next the next message is explicitely sent to the helpBrowserWindow:
next

	self helpBrowserWindow 
		ifNotNil: [:window | window model next ].

**Comment by guillep** [comment] 2020-03-27 09:51
Yes, the problem is that prof stef was (seemingly?) originally built to work within a help window.
And to make it magically work, instead of being a model of the window, it grabs *a* help window by iterating all windows in the system. This means it will use the first one it finds.

ProfStef should be rewritten using spec probably, or just not using any global state.

**Comment by gcorriga** [comment] 2021-01-04 13:22
@guillep should this issue be closed and replaced with another one specifying what to do exactly? Or at least change the title.

**Comment by astares** [comment] 2022-12-12 17:05
Welcome window and Help packages have been removed from Pharo 11:
see https://github.com/pharo-project/pharo/issues/11994 

We can close the issue

**Comment by Ducasse** [comment] 2022-12-12 17:25
Thanks for the report.

**Closed as completed** 2022-12-13 07:14 UTC
Labels: Type: Enhancement, Project: Tools
