### ISSUE TITLE
Dialog does not show it button

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16540] opened 2024-04-27 20:53 UTC
![Capture 2024-04-27 at 22 52 49](https://github.com/pharo-project/pharo/assets/432549/88f174c3-902e-4aac-a513-0152e457062e)

**Comment by hernanmd** [comment] 2024-05-31 15:56
I cannot reproduce it in latest Pharo 13.

![Screenshot 2024-05-31 at 17 56 03](https://github.com/pharo-project/pharo/assets/4825959/d8bb8593-64d3-4526-83f4-4fd1882f0cfe)

Feel free to close it.

**Closed as completed** 2024-05-31 17:10 UTC
