### ISSUE TITLE
Debugger should show breakpoints

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#9770] opened 2021-08-12 13:48 UTC
In the debugger, the source code pane does not show breakpoints (as does the code browser).
It should be nice to show breakpoints so that we know if we will break or not when we proceed

**Comment by StevenCostiou** [comment] 2021-09-07 17:41
Duplicate of https://github.com/pharo-project/pharo/issues/5211.
Notes:
- showing could be easy (depend on the spec code presenter)
- modifying breakpoints will be hard

**Closed as completed by StevenCostiou** 2021-09-07 17:41 UTC
Labels: Type: Enhancement, Project: Debugger
