### ISSUE TITLE
[Debugger] could we have browse on a variable browse the class of the variable

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7073] opened 2020-08-10 16:58 UTC
I did a videos but I do not know how to upload it. 
How do you produce your animated gif?

![Screenshot 2020-08-10 at 18 55 53](https://user-images.githubusercontent.com/432549/89808917-28a9ee00-db3b-11ea-8fbf-8c96ac83ac67.png)

In essence selecting aProgramNodeVisitor and doing browse should open the class in the code pane. 
This is so useful.
And this is super boring to have to type 

aProgramNodeVisitor class and browse
And worse is that aProgramNodeVisitor browse is actually working.

**Comment by StevenCostiou** [comment] 2020-08-10 17:49
Solving this problem requires a refactor of the spec edition commands hierarchy.
This is a duplicate of #6973 where I have put a more detailed comment.

**Comment by MarcusDenker** [comment] 2021-01-13 10:15
yes, duplicate, I close this one

**Closed as completed by MarcusDenker** 2021-01-13 10:15 UTC
Labels: Type: Enhancement, Project: Debugger
