### ISSUE TITLE
Right click in empty Iceberg pane gives #build was sent to nil

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#13712] opened 2023-05-12 18:12 UTC
Pharo 12:

- open Iceberg
- right click into the empty repository pane

![image](https://github.com/pharo-project/pharo/assets/5980033/4e5e6725-faa5-4e02-80ae-08f412746774)

**Comment by MarcusDenker** [comment] 2023-05-15 12:56
Maybe related to 

Half of a fix fix for when right-clicking on an empty Iceberg panel
https://github.com/pharo-vcs/iceberg/pull/1698

**Comment by MarcusDenker** [comment] 2023-05-15 12:58
Yes, this seems to be fixed in Pharo11 already

**Comment by Gabriel-Darbord** [comment] 2023-05-26 09:33
Can confirm that this is not reproducible in Pharo12.

**Comment by MarcusDenker** [comment] 2023-05-26 09:59
Great! I close the issue

**Closed as completed by MarcusDenker** 2023-05-26 09:59 UTC
Labels: Type: Bug
