### ISSUE TITLE
[Calypso] Browsing of trait users causes DNU

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#12108] opened 2022-12-14 16:10 UTC
**Bug description**
Browsing of trait users stopped to work. It is possible to see the list of them but the browser raises a DNU because the query browser context is (correctly) used but the method expects a full browser

**To Reproduce**
1. Go to `TObservable` trait in Calypso 
2. from a context menu, select `Show trait users`
3. click on some of the provided options in the query browser

It worked in build 353

**Version information:**
Pharo 11.0.0
Build information: Pharo-11.0.0+build.383.sha.421dbef721c2c2bf771fab5c999a9a0260225096 (64 Bit)

**Comment by pavel-krivanek** [comment] 2022-12-14 16:17
A funny and super interesting fact. If you get this error, do this:
1. restart the method
2. do "Step Through" until the end of the methd 
3. it passes the DNU point without noticing
4. at the end of the method do Proceed 
5. repeat it for the next DNU you will see
6. the browser is correctly shown

**So, stepping through hides the error!**

**Comment by pavel-krivanek** [comment] 2022-12-14 16:18
(it is not the case for stepping over)

**Comment by fmqa** [comment] 2022-12-16 18:42
Unfortunately, this was caused by 77f3873e9a24dde3aa32fe5a4b41cbb4ff22db4f

The method expects `ClyClassEditorToolMorph>>#isValidInContext` a full browser and calls `#metaLevelScope` to determine whether the tool is valid for the given context. `#metaLevelScope` exists only on the full browser however.

This can be fixed by providing a no-op `ClySystemBrowserContext>>#metaLevelScope` that just returns `nil` but I'm not sure whether this is a clean fix.

**Closed as completed** 2022-12-20 11:14 UTC
Labels: Type: Bug
