### ISSUE TITLE
autocompletion of a method parameter when typing in a method should be higher

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2855] opened 2019-03-17 09:00 UTC
when faced with a method like:
```
executeShould: aBlock inScopeOf: anExceptionalEvent withDescriptionContaining: aString
	^[aBlock value.
 	false] on:  <cursor here>
		do: [:ex | ex return: (ex description includesSubstring: aString) ]
```

And your cursor is after the on: - if you start to type "anE" - the exception parameter is not your first item in the list (its the third, after some letter matching in some un-related classes). I would argue that matching method parameters should always be first in the list - as other wise you always have to scroll down the list, or type more, to easily autocomplete the most commonly used variables?

![image](https://user-images.githubusercontent.com/5553623/54487845-a5776080-4892-11e9-8633-f2a87f42c407.png)

**Comment by ofi** [comment] 2019-03-17 16:46
I completely agree and support this point. The sequence of the completion list should be grouped by scope in an order like { local/parameter > class > package > global [> deprecated]} with lexically sorted symbols in each group. This relates to #2849 as well.

An optional browser setting enabling the actual fuzzy in-pattern search vs. a case-ignoring start-index-based pattern search would be a bonus feature. ;-)

**Comment by Ducasse** [comment] 2019-03-28 14:51
Do you know if it is a regression that happens recently?

**Comment by jecisc** [comment] 2019-03-28 14:53
It happened between Pharo 6 and 7.

**Comment by MarcusDenker** [comment] 2019-03-28 15:14
The globals are in the list first... I think this can be fixed by moving the adding from #initializeSelectors to #addVariables

**Comment by MarcusDenker** [comment] 2019-03-28 15:40
the reason why we did not see it is that the code completion limited the found completions so early that classes where never found. (it just added the first 100 or so).

e.g. you could type Ord  in the playground and it would *not* show you OrderedCollection....

**Comment by MarcusDenker** [comment] 2019-03-28 16:01
I added 

Smalltalk globals keysDo: [ :symbol  | 
					(symbol includesSubstring: narrowString caseSensitive: NECPreferences caseSensitive)
						ifTrue: [entries add: (NECGlobalEntry contents: symbol) ]].

to addVariables and removed it from initializeSelectors , but that now makes the experience in the playground useless: type Ord... and it shows selectors first.

**Comment by bergel** [comment] 2019-03-29 13:51
Alejandro and I are working on this right now

**Comment by bergel** [comment] 2019-03-29 14:56
PR here: https://github.com/pharo-project/pharo/pull/3096
Ready to be reviewed

**Comment by MarcusDenker** [comment] 2019-03-29 14:57
Does it really fix the problem? it sorts Class Variables nicer, but Globals will still come first?

**Comment by alejandroinfante** [comment] 2019-03-29 15:29
We made that variables are now at the beginning of the list, instead of globals. Now the example looks  as expected, the local variable first and the globals later.

In the workspace, since there are no variables, it works normally placing globals at the beginning.

**Comment by MarcusDenker** [comment] 2019-03-29 15:55
ah, nice

**Comment by bergel** [comment] 2019-03-29 15:58
The the algorithm can be significantly improved. For example, you probably do not want to have at the beginning of the list some classes that are very remote to the project in which you are working on.

**Closed as completed** 2019-03-29 18:03 UTC

**Comment by bencoman** [comment] 2019-03-30 04:11
If this was a regression from Pharo 6 to 7 as Cyril indicates, can it seems be backported ?
