### ISSUE TITLE
Error on UITheme newDropListIn:

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5947] opened 2020-03-20 22:12 UTC
UITheme *newDropListIn: aThemedMorph for: aModel list: listSel getSelected: getSel setSelected: setSel getEnabled: enabledSel useIndex: useIndex help: helpText* gives an error in some cases, for example when entering on settings because the first parameter is not a Morph

To reproduce:
Download the latest image of pharo 9 enter setting and click on any option to exand it.

I've made locally this change and solves the problem:

```smalltalk
cornerStyle: ((aThemedMorph isKindOf: Morph) ifTrue: [  aThemedMorph  preferredCornerStyle] ifFalse:[#squared]) ;
```

![imagen](https://user-images.githubusercontent.com/7849541/77210040-3ca77180-6b00-11ea-8b55-078564a25fc8.png)

But I almost sure, that there will be a cleaner a better solution.

**Comment by guillep** [comment] 2020-03-23 08:40
This is a duplicate of #5939.
It apparently got fixed. I'll check before closing this one.

**Comment by guillep** [comment] 2020-03-23 08:46
Ok, it seems that

```smalltalk
PickOneSettingDeclaration >> inputWidget
	| widget row |
	row := self theme newRowIn: self for: {
				widget := (self theme 
						newDropListIn: self
						for: self
						list: #domainValuesLabels
						getSelected: #index
						setSelected: #index:
						getEnabled: #enabled
						useIndex: true
						help: self description)
						extent: 1 @ 30}.
	widget hResizing: #rigid.
	widget width: (self maxNameWidthForFont: widget font) + 50.
	^ row
```

Was replaced by

```smalltalk
PickOneSettingDeclaration >> inputWidget
	| widget row |
	row := self theme newRowIn: self currentWorld for: {
				widget := (self theme 
						newDropListIn: self currentWorld
						for: self
						list: #domainValuesLabels
						getSelected: #index
						setSelected: #index:
						getEnabled: #enabled
						useIndex: true
						help: self description)
						extent: 1 @ 30}.
	widget hResizing: #rigid.
	widget width: (self maxNameWidthForFont: widget font) + 50.
	^ row
```

Which seems a good solution because the settings declaration is no morph and (sometimes) a morph is required as first argument.
I'll close this one.

**Comment by guillep** [comment] 2020-03-23 09:24
I can confirm the issue is still there.
I'll fix it this morning.

**Comment by guillep** [comment] 2020-03-23 10:15
Some more input. From the message browser (senders/implementors) this seems to work correctly. So the it is something related to Calypso browser itself.

**Comment by guillep** [comment] 2020-03-23 10:22
I checked the stacks from the two cases above and they seem similar.

Also, I've noticed that changing protocol and changing package seem to work differently => although both seem to do the same, one has the bug the other does not.

![image](https://user-images.githubusercontent.com/708322/77306749-64f9c080-6cf8-11ea-9c9b-c52cdc2d9215.png

**Comment by guillep** [comment] 2020-03-23 10:24
Seems both do different things :(. Package selection is implemented from scratch repeating all the logic from the other one...

**Comment by guillep** [comment] 2020-03-23 10:33
It seems also that clicking on the Edit button (the little pencil) works well. While clicking on the label, creates the problem.

This seems to boil down to a problem managing the events.

@myroslavarm could you help me confirming my assumptions?
 - clicking on the "Extension" checkbox works well
 - clicking on the pencil to edit the protocol works well
 - clicking on the label to edit the protocol generates the issue

**Comment by myroslavarm** [comment] 2020-03-23 10:38
@guillep yes, i confirm it's exactly the same, it only breaks when clicking the label itself.

P.S. was just about to report that the DNU from https://github.com/pharo-project/pharo/issues/5939 is not fully gone for me, for example if you go to Settings and search for 'completion' in the search bar and click enter, you get the error again. is it the same for you too?

**Comment by myroslavarm** [comment] 2020-03-23 10:39
Or in fact the error is not gone for the Settings browser in general.

**Comment by guillep** [comment] 2020-03-23 10:42
Yes, that's why this issue is still open (this issue is from the settings error, not from the popup in calypso, I did a mistake :) )

**Closed as completed** 2020-03-23 12:15 UTC
Labels: Type: Bug, Project: Graphics
