### ISSUE TITLE
[CI] SocketStreamTest failing on CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16119] opened 2024-02-08 10:29 UTC
**Bug description**
some tests in SocketStreamTest are failing:

on Mac:

- testFlushOtherEndClosed – MacOSX64.Network.Tests.SocketStreamTest
- testNextPutAllFlushOtherEndClosed – MacOSX64.Network.Tests.SocketStreamTest

on Linux:
-  testFlushLargeMessageOtherEndClosed – Unix64.Network.Tests.SocketStreamTest

**Comment by Rinzwind** [comment] 2024-03-23 15:44
These tests were added in pull request #15984 which was merged in commit 9a4b8d5cd9a4b193.

That commit was used in builds [1336](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/1336/), [1337](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/1337/) and [1338](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/1338/) of the ‘Pharo12’ Jenkins job. Those all had `#testFlushOtherEndClosed` fail on macOS and `#testFlushLargeMessageOtherEndClosed` on Linux.

In build [1442](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo12/1442/), `#testFlushOtherEndClosed` and `#testNextPutAllFlushOtherEndClosed` failed on macOS, and `#testFlushLargeMessageOtherEndClosed` failed on Linux.

@daniels220: Could you check what the cause of those failures might be and how that can be fixed?

**Comment by daniels220** [comment] 2024-03-25 20:04
This is fixed in #16172, which is a redo of a close follow-on to #15984. I meant to remind about getting it merged, but I've been unexpectedly busy. It would be great if it could be merged in time for Pharo 12—like I said, it's a really close follow-on to #15984, that just got roadblocked by a mistake on my part with the Semaphore API and then I never got back around to it. But, I understand if this is outside the scope of what's acceptable after code freeze. In that case I can move over the specific change that fixes the test, which is just adding a wait in an appropriate spot.

@guillep sounded like you were going to look at #16172, but it looks like it fell through the cracks?

**Closed as completed** 2024-05-07 08:31 UTC
Labels: Project: CI
