### ISSUE TITLE
WeakAnnouncerTest and friends fail on the CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2471] opened 2019-02-08 16:15 UTC
osx-32 / Tests-osx-32 / testNoDeadSubscriptions – MacOSX32.Tests.SystemChangeNotification.SystemAnnouncerLiveTest
nix-32 / Tests-unix-32 / testNoDeadWeakSubscriptions – Unix32.Announcements.Tests.Core.Tests.WeakAnnouncerTest
osx-32 / Tests-osx-32 / testNoDeadWeakSubscriptions – MacOSX32.Announcements.Tests.Core.Tests.WeakAnnouncerTest
windows-32 / Tests-windows-32 / testNoDeadSubscriptions – Windows32.Tests.SystemChangeNotification.SystemAnnouncerLiveTest
windows-32 / Tests-windows-32 / testNoDeadWeakSubscriptions – Windows32.Announcements.Tests.Core.Tests.WeakAnnouncerTest
unix-32 / Tests-unix-32 / testNoDeadSubscriptions – Unix32.Tests.SystemChangeNotification.SystemAnnouncerLiveTest

**Comment by MarcusDenker** [comment] 2019-03-01 12:49
not anymore

**Comment by MarcusDenker** [comment] 2019-03-27 15:59
Happens again regularly.

They are all related to the PragmaCollector:

Got an Array(a WeakAnnouncementSubscription(a WeakMessageSend(#classRemovedEventOccurs: -> nil)) a WeakAnnouncementSubscription(a WeakMessageSend(#removedEventOccurs: -> nil)) a WeakAnnouncementSubscription(a WeakMessageSend(#addedEventOccurs: -> nil)) a WeakAnnouncementSubscription(a WeakMessageSend(#removedEventOccurs: -> nil)) a WeakAnnouncementSubscription(a WeakMessageSend(#classRemovedEventOccurs: -> nil)) a WeakAnnouncementSubscription(a WeakMessageSend(#modifiedEventOccurs: -> nil)) a WeakAnnouncementSubscription(a WeakMessageSend(#addedEventOccurs: -> nil)) a WeakAnnouncementSubscription(a WeakMessageSend(#modifiedEventOccurs: -> nil))) instead of #().

**Comment by alejandroinfante** [comment] 2019-03-29 15:40
Using the `pointersTo` and traversing the object graph we noticed that those weak announcements are being held by the SystemAnnouncer registry.

To clean that we executed:
```
registry := SystemAnnouncer uniqueInstance subscriptions.
subs := WeakSet withAll: registry subscriptions.
registry reset.
5 timesRepeat: [ Smalltalk garbageCollect ].
subs do: [ :elem | registry add: elem ].
```
After executing that, the tests are green again. But the original cause of why those announcers are being held by the SystemAnnouncer is still unknown.

**Comment by guillep** [comment] 2019-04-01 14:34
Actually, it seems that finalization was not executed.
A more compact script that does the cleanup is the following:

```smalltalk
WeakAnnouncementSubscription allInstances
    select: [ :sub | sub subscriber isNil ]
    thenDo: #finalize.
```

**Comment by guillep** [comment] 2019-04-01 14:53
A bit more digging shows:

 - The hanging subscriptions that can be obtained from:

```smalltalk
WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ].
```

 - Are not in the weak registry:

```smalltalk
(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil and: [ | ala |
	ala := WeakRegistry default instVarNamed: 'valueDictionary'.
	ala values anySatisfy: [ :finalizerItem | finalizerItem executor = sub ] ] ]).
```

While they should be:

```smalltalk
(WeakAnnouncementSubscription allInstances select: [ :sub | | ala |
	ala := WeakRegistry default instVarNamed: 'valueDictionary'.
	ala values anySatisfy: [ :finalizerItem | finalizerItem executor = sub] ]).
```

**Comment by guillep** [comment] 2019-04-01 15:05
Looking at all the users of these, there are only two methods where something strange is happening.
Those two methods are removing subscriptions from the WeakRegistry by hand, preventing the subscriptions to be correctly finalized (and thus cleaned up).
Funny thing that the code that says "avoiding memory leaks" seems to actually produce them :P.

Looks like these are the possible culprits, still investigating:

```smalltalk
SystemAnnouncer >> reset

	"unregister all current weak subscriptions because it can cause a memory leak"
	announcer subscriptions subscriptions
 		select: [:each | each isKindOf: WeakAnnouncementSubscription] 
		thenDo: [:each | each weakRegistry remove: each subscriber ifAbsent: []]. 
	Smalltalk garbageCollect.
		
	announcer := nil.
```

and

```smalltalk
ToolRegistry >> resetAnnouncer

	"unregister all current weak subscriptions because it can cause a memory leak"
	announcer subscriptions subscriptions
 		select: [:each | each isKindOf: WeakAnnouncementSubscription] 
		thenDo: [:each | each weakRegistry remove: each subscriber ifAbsent: []]. 
	Smalltalk garbageCollect.
		
	announcer := nil.
```

**Comment by guillep** [comment] 2019-04-01 15:32
More digging, the default image comes with 20 broken subscriptions, which are 5 sets of the following 4 messages:

- #removedEventOccurs:
- #classRemovedEventOccurs:
- #modifiedEventOccurs:
- #addedEventOccurs:

Which are only defined in PragmaCollector

**Comment by guillep** [comment] 2019-04-02 07:46
Also, the issue is already present in the minimal image

```bash
$ ./pharo Pharo8.0-SNAPSHOT-metacello-64bit-44833f1.image eval"(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ]) size."
4
```

But it goes away automatically by saving a couple of times

```bash
$ ./pharo Pharo8.0-SNAPSHOT-metacello-64bit-44833f1.image eval --save "(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ]) size."
0
```

**Comment by guillep** [comment] 2019-04-02 08:44
The same in the latest image does not clean anymore:

```bash
$ ./pharo Pharo8.0-SNAPSHOT-64bit-44833f1.image eval "(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ]) size."
23
$ ./pharo Pharo8.0-SNAPSHOT-64bit-44833f1.image eval "(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ]) size."
23
$ ./pharo Pharo8.0-SNAPSHOT-64bit-44833f1.image eval --save "(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ]) size."
23
$ ./pharo Pharo8.0-SNAPSHOT-64bit-44833f1.image eval --save "(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ]) size."
24
$ ./pharo Pharo8.0-SNAPSHOT-64bit-44833f1.image eval --save "(WeakAnnouncementSubscription allInstances select: [ :sub | sub subscriber isNil ]) size."
20
```

**Comment by Alisu** [comment] 2019-09-13 11:52
It seems the test pass in the lastest images (maybe in relation with recent fixes by Jecisc on WeakValueDictionary). 
May be we should consider remove the skip on those tests and see if the problem reappears.

**Comment by guillep** [comment] 2020-03-27 10:41
This is not an issue anymore since some time. I'll close it, please reopen it if still valid.

**Comment by jordanmontt** [comment] 2024-04-12 13:36
I still have issue on Pharo12. In a fresh image, it does not happen, but when you use the image for a moment, (defining methods, committing to iceberg), the test `testNoDeadWeakSubscriptions` is failing with this message.

> an Array(a WeakAnnouncementSubscription (nil subscribes to IceAnnouncement) a WeakAnnouncementSubscription (nil subscribes to IceRepositoryAnnouncement)) should have been empty

Should l open another issue since only the test `testNoDeadWeakSubscriptions` that is failing?

**Comment by pavel-krivanek** [comment] 2024-04-26 21:08
The new issue would be better, the current title is now misleading because CI is not involved.

**Comment by astares** [comment] 2024-12-17 07:46
As suggested by @pavel-krivanek I opened a new issued https://github.com/pharo-project/pharo/issues/17535
and we will close this one here

**Closed as completed** 2024-12-17 07:46 UTC
