### ISSUE TITLE
[Debugger]Fuel out stack happens silently

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2963] opened 2019-03-21 18:31 UTC
The file is just empty...
![DO23bQwV9V](https://user-images.githubusercontent.com/4706329/54776195-e1eae980-4c0f-11e9-901d-7ccc76d9f641.gif)

**Comment by StephanEggermont** [comment] 2019-03-26 10:23
Caused by #2789

**Comment by fortizpenaloza** [comment] 2019-05-23 00:42
Which version of Pharo are you using @VincentBlondeau ? I'm found the same issue on 7.0.3

**Comment by VincentBlondeau** [comment] 2019-05-23 07:51
It is actually working under Pharo 8 and 7, but it happens silently... Can a toast be added?

**Comment by fortizpenaloza** [comment] 2019-05-24 13:51
Good idea, but I would be great to have the stack serialization working first and then add the toast

**Comment by VincentBlondeau** [comment] 2019-05-24 14:10
It is working and saved into the image folder. Could you check on your side?

**Comment by guillep** [comment] 2020-04-16 15:13
So an action to fix this would be to add a toast/Growl (see GrowlMorph).

**Comment by MarcusDenker** [comment] 2020-12-16 08:24
The new debugger has this not yet, I close this issue and will open an issue for that in the newtools repo

**Closed as completed by MarcusDenker** 2020-12-16 08:24 UTC
Labels: Type: Enhancement, Easy, Project: Debugger

**Comment by MarcusDenker** [comment] 2020-12-16 08:26
I added: https://github.com/pharo-spec/NewTools/issues/148
