### ISSUE TITLE
FFI issue leading to image crash using SQLite on Windows

### ISSUE THREAD

**Issue by rko281** [guillep/pharo-core#11019] opened 2022-03-21 09:23 UTC
I'm hitting an FFI issue in SQLite on Pharo 9 and 10 on Windows 10 (64 bit image and VM, updated today) which causes the image to crash and exit. It can be demonstrated as follows:

```smalltalk
Metacello new
    repository: 'github://pharo-rdbms/Pharo-SQLite3/src';
    baseline: 'SQLite3';
    load.
    
conn := SQLite3Connection on: 'test.db'.
conn open.
conn execute: 'drop table if exists test'.
conn execute: 'create table test(num integer, name varchar(32));'.

stmt := conn prepare: 'insert into test(num,name) values(?,?)'.
stmt execute: #(1 'a').
stmt execute: #(2 'b').
```

On Windows the image hangs briefly then exits in the final statement; the crash looks to be happening in `SQLite3Library>>apiClearBindings:on:` 

The code runs successfully on Mac (Intel), and also succeeds on Windows when using the OldFFIBackend:

```smalltalk
FFIBackend classPool at: #Current put: OldFFIBackend new.
"Repeat test - succeeds"
````

Due to the error being specific to Windows and the TFFIBackend I suspect this to be an FFI/VM issue rather than SQLite, so logging this here rather than at pharo-rdbms/Pharo-SQLite3.

**Comment by Ducasse** [comment] 2022-03-21 09:44
Thanks a lot John for this report!!! 
We will check it.

**Comment by astares** [comment] 2022-03-21 13:31
I can confirm the crash

**Comment by astares** [comment] 2022-03-28 07:56
it already crashes when one runs the SQLite3 test suite

**Comment by astares** [comment] 2022-06-08 18:29
Please be aware that OldFFIBackend is not part of Pharo 10 so I guess the problem seems to be an TFFI/VM
issue which could not be solved without the help of @tesonep / @guillep 

So Windows users will be lost once again which is frustrating ...

**Comment by astares** [comment] 2022-06-08 18:36
![image](https://user-images.githubusercontent.com/5980033/172691142-65aaaa10-c18f-49c5-bd84-a5119ddd40ed.png)

![image](https://user-images.githubusercontent.com/5980033/172691249-9e5b981d-ab38-48ea-a793-c4e53431c264.png)

Strange - it does not even accept the sqlite3.dll on my machine now...

**Comment by astares** [comment] 2022-06-14 07:59
Has been fixed in SQLite3 by including:   https://github.com/pharo-rdbms/Pharo-SQLite3/commit/333aa9b5bd287f634a56a479d0aaba6d176d26f4 

Still I'm think it was a problem of UFFI/TFFI compatibility. Not sure if we should close.

**Closed as completed** 2022-06-14 07:59 UTC
Labels: Type: Bug
