### ISSUE TITLE
Epicea cannot apply class creation

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5914] opened 2020-03-17 10:23 UTC
I got an image that crashed without being able to save. I took a new image and wanted to use Epicea to bring back my changes. The problem is that all the changes started with new classes created and my I try to apply the changes I get info popup saying that the class is missing in the system.

**Comment by Ducasse** [comment] 2020-03-27 09:33
Cyril can you reproduce this issue because I cannot
- I created a new class
- quit without saving
When I open epicea I get 

![Screenshot 2020-03-27 at 10 32 15](https://user-images.githubusercontent.com/432549/77742165-51ab6580-7016-11ea-94ae-5fad21f31cc0.png)

**Comment by Ducasse** [comment] 2020-03-27 09:48
And I could apply so may be this is the superclass that was missing. 
Could you have a reproducible case?

**Comment by Ducasse** [comment] 2020-03-27 09:51
Because we could create a stub for the superclass but it can be vicious because the user may think that everything is working while it is not. 
So I will close this issue for now and feel free to reopen it.

**Closed as completed by Ducasse** 2020-03-27 09:51 UTC
Labels: Status: Unable to reproduce
