### ISSUE TITLE
Certain Finder searches hang entire application/image

### ISSUE THREAD

**Issue by Nezteb** [guillep/pharo-core#13153] opened 2023-03-27 01:54 UTC
**Bug description**
If you use Finder to search for `'aojfwepoqprjiowjoiajwojfoecmiaowejc' . $w` (any sufficiently long string does it), Finder will cause the entire image to hang. Clicking the red X doesn't work. On Mac I have to force quit the entire application.

**To Reproduce**
1. Open Finder.
2. Select "Examples" to search.
3. Search for something like `'aojfwepoqprjiowjoiajwojfoecmiaowejc' . $w`.
4. Notice that the entire image hangs and clicking the red X does nothing.

**Expected behavior**
This shouldn't hang the entire image. Worst case scenario it should just return an error.

**Screenshots**
<img width="983" alt="Screenshot 2023-03-26 at 6 47 46 PM" src="https://user-images.githubusercontent.com/3588798/227822025-ab32bed9-6c81-4223-8f5f-f8116801aa1f.png">

**Version information:**
 - OS: mac OS
 - Version: Ventura 13.2.1
 - Pharo Version: 12.0 64 bit

**Expected development cost**
I'm still a Pharo noob, so I have no idea. I'm willing to help do any additional testing that is needed!

**Comment by jordanmontt** [comment] 2023-03-27 09:46
This is maybe because it is executing all unary methods of `String` and `ByteString` and checking if the results is a `$w`. And there are methods that take long time to be executed.

**Comment by jordanmontt** [comment] 2023-03-27 11:57
And I confirm that this hangs my image. I let it run for 2 hours and it is still hanged

**Comment by astares** [comment] 2023-03-27 13:22
Would be good to know which is the message that finally blocks by tracing the methods called. If I remember correctly the Finder has an internal collection of "dangerous selectors" to exclude when performing/trying selectors.

**Comment by privat** [comment] 2023-03-27 13:29
It could also be possible to 'time-out' these individual calls

**Comment by astares** [comment] 2023-03-27 16:07
@privat No - some could kill the image and a timeout would not make sense. So they get explicity excluded like for instance #become:

**Comment by privat** [comment] 2023-03-27 16:13
@astares obviously, I'm just considering the calls that are presumably safe but slow; or might loop infinitely for some arguments

**Comment by jecisc** [comment] 2023-03-28 13:13
SequenceableCollection>>#combinations time increases exponentially depending on the length of the string. So I think it might be the culprit.

I like the idea of @privat to timeout such cases

**Comment by jecisc** [comment] 2023-03-28 13:13
While keeping also the list of things to exclude of course

**Comment by jordanmontt** [comment] 2023-03-28 13:19
Yes, +1 to the idea of @privat 

but also add some kind of feedback to the user saying which messages timed out

**Comment by MarcusDenker** [comment] 2023-04-03 06:47
as the problem described in the issue is fixed, I close this.

The finder implementation of course is extremely naive...

**Closed as completed by MarcusDenker** 2023-04-03 06:47 UTC
Labels: Type: Bug
