### ISSUE TITLE
SpStringTableColumn beEditable and acceptAction has not effect

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#8416] opened 2021-01-24 14:06 UTC
The action specified by `SpStringTableColumn>>onAcceptEdition:` is not activated even if `beEditable` is called.

The problem is seen in that there is no senders for `SpStringTableColumn>>acceptEdition`.

The situation can/should be corrected in method 'SpMorphicTableCellBuilder>>visitStringColumn:'. 

It is a bit unclear (due to lacking implementation) what parameters the `acceptAction` block should accept. My guess is that culling the block with `item` and the newly typed text would be appropriate.

**Comment by kasperosterbye** [comment] 2021-01-26 05:25
I can make this myself, I have the solution - in Spec2. Just got sidetracked. Will do it on Friday Jan 29 at the sprint
But there are a couple of design issues I am uncertain about.
Besides the acceptAction, there is an issue of the `text:` method in `SpAbstractTextPresenter`. As it is now, it ignores the cases where the original or the assigned value is a Text (as opposed to a String), loosing formating in inconsistent ways.

**Comment by estebanlm** [comment] 2021-01-26 08:52
This is by design: Spec2 does not understand Text objects, since this is Morphic.
It is not inconsistent, for Spec2 there will just be strings. 
Now, if you still want to use Text you can workaround the issue extending `SpTextPresenter` and adding an adapter capable to work with Text objects (it would be fairly trivial to implement). 
Now, such a presenter will not be portable (the Gtk backend and others in the future will not understand it), but this is not a problem if you are not expecting to make your application portable.

**Comment by kasperosterbye** [comment] 2021-01-26 10:06
OK - I do consider it bad to name methods which are not intended to handle Text to be named `text:`. It is not helping understanding.

**Comment by estebanlm** [comment] 2021-01-26 10:08
well, the problem in fact is -again- about the morphic backend.
The "Text" name is a common name in widget frameworks, and I followed that convention ;)

**Comment by MarcusDenker** [comment] 2021-06-21 10:59
does this mean we can close this issue?

**Closed as completed** 2021-06-21 11:01 UTC
Labels: Type: Bug
