### ISSUE TITLE
Losing code while loading Microdown dev in P12 vs. P11

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15930] opened 2024-01-07 13:17 UTC
I discovered a problem when loading microdown in P11 vs. P12.

https://github.com/pillar-markup/Microdown/issues/671

Steps to reproduce:
- take an image.

```
	IceRepository registry 
	detect: [ :each | #('Microdown' 'NewTools-DocumentationReader') includes: each name ]
	ifFound: [ :aRepository | aRepository forget ].

#( 'BeautifulComments' 'BaselineOfBeautifulComments' 'BaselineOfMicrodownDev' 'BaselineOfMicrodown' 'Microdown' 'Microdown-Tests' 'Microdown-MicrodownRichTextComposer' 'Microdown-ResolvePath' 
'Microdown-ResolvePath-Tests' 'NewTools-DocumentationReader-Tests' 'BaselineOfNewToolsDocumentationReader' 'Microdown-RichTextComposer' 'Spec2-Microdown'
'NewTools-DocumentationReader') do: [ :each | 
	(RPackageOrganizer default packageNamed: each ifAbsent: [ nil ]) 
		ifNotNil: [ :aPackage | aPackage removeFromSystem ] ]
```

then 

```
Metacello new
	baseline: 'Microdown';
	repository: 'github://pillar-markup/Microdown:dev/src';
	onConflict: [ :e | e useIncoming ];
	onUpgrade: [ :e | e useIncoming ];
	ignoreImage;
	load.
```

In P12 MicRichTextComposer is empty and inherits from Object
In P11 it inherits from MicrodownVisitor.

**Comment by Ducasse** [comment] 2024-01-07 13:20
in P11 Adding 

```
ClassDescription >> protocolNames
	"Return the list of all the protocol names included in this class."

	^ self protocols collect: [ :protocol | protocol ]
```
![Capture 2024-01-07 at 14 20 04](https://github.com/pharo-project/pharo/assets/432549/86ef9478-c3a3-4bde-8871-6e295c20b1de)

I get a green bar

**Comment by astares** [comment] 2024-01-08 01:50
RPackageOrganizer is deprecated in P12, no?

I tried it with using "Object packageOrganizer" instead and got correctly "MicrodownVisitor << #MicRichTextComposer"

```Smalltalk
	IceRepository registry 
	detect: [ :each | #('Microdown' 'NewTools-DocumentationReader') includes: each name ]
	ifFound: [ :aRepository | aRepository forget ].

#( 'BeautifulComments' 'BaselineOfBeautifulComments' 'BaselineOfMicrodownDev' 'BaselineOfMicrodown' 'Microdown' 'Microdown-Tests' 'Microdown-MicrodownRichTextComposer' 'Microdown-ResolvePath' 
'Microdown-ResolvePath-Tests' 'NewTools-DocumentationReader-Tests' 'BaselineOfNewToolsDocumentationReader' 'Microdown-RichTextComposer' 'Spec2-Microdown'
'NewTools-DocumentationReader') do: [ :each | 
	(Object packageOrganizer packageNamed: each ifAbsent: [ nil ]) 
		ifNotNil: [ :aPackage | aPackage removeFromSystem ] ]
```
<img width="932" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/ddca1d50-7ba7-4284-93db-0684546a27f1">

**Comment by Ducasse** [comment] 2024-01-08 17:48
I'm redoing the test. My removing script does not remove correctly the RichText. 
So I checked by hand to see. 
And I'm trying with the latest Metacello fix of guille to see. 
So far the fix of guille does not solve my problem.

**Comment by guillep** [comment] 2024-01-09 08:30
I cannot reproduce it in a clean P12 image.
There is something else here, maybe your shared repositories setting? 

<img width="1088" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/b7bfc4c4-e7ca-454a-b109-23774b0f5b6b">

**Comment by Ducasse** [comment] 2024-01-09 10:29
Super strange because I do not use the shared repo in P12 (only in P11)
I will retry as soon as I have a decent internet connection (now on my phone).

**Comment by guillep** [comment] 2024-01-11 16:19
We checked this yesterday personally with Stef, it's not a Pharo nor metacello problem. I'll close it.
Please, do not hesitate to reopen it if necessary.

**Closed as completed by guillep** 2024-01-11 16:19 UTC

**Comment by Ducasse** [comment] 2024-01-11 18:27
Thanks I had on my todo to close it :)
