### ISSUE TITLE
Bootstrap is calling deprecated #asDate a lot

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15156] opened 2023-10-28 00:41 UTC
The method #asDate got deprecated but it is called a lot during the bootstrap.

Example of logs:

```
Deprecation: The method Date class>>#fromString: called from MCWorkingCopy lass>>#infoFromDictionary:cache: has been deprecated. Use Date>>#readFrom:pattern: specifying a concrete pattern instead.
Date class(Object)>>deprecated:
Date class>>fromString:
[Date fromString: (aDictionary at: #date)] in [MCVersionInfo
			name: (aDictionary at: #name ifAbsent: [''])
			id: (UUID fromString: id)
			message: (aDictionary at: #message ifAbsent: [''])
			date: ([Date fromString: (aDictionary at: #date)] onErrorDo: [nil])
			time: ([Time fromString: (aDictionary at: #time)] onErrorDo: [nil])
			author: (aDictionary at: #author ifAbsent: [''])
			ancestors: (self ancestorsFromArray: (aDictionary at: #ancestors ifAbsent: []) cache: cache)
			stepChildren: (self ancestorsFromArray: (aDictionary at: #stepChildren ifAbsent: []) cace: cache)] in MCWorkingCopy class>>infoFromDictionary:cache: in Block: [Date fromString: (aDictionary at: #date)]
FullBlockClosure(BlockClosure)>>on:do:
FullBlockClosure(BlockClosure)>>onErrorDo:
[MCVersionInfo
			name: (aDictionary at: #name ifAbsent: [''])
			id: (UUID fromString: id)
			message: (aDictionary at: #message ifAbsent: [''])
			date: ([Date fromString: (aDictionary at: #date)] onErrorDo: [nil])
			time: ([Time fromString: (aDictionary at: #time)] onErrorDo: [nil])
			author: (aDictionary at: #author ifAbsent: [''])
			ancestors: (self ancestorsFromArray: (aDictionary at: #ancestors ifAbsent: []) cache: cache)
			stepChildren: (self ancestorsFromArray: (aDictionary at: #stehildren ifAbsent: []) cache: cache)] in MCWorkingCopy class>>infoFromDictionary:cache: in Block: [MCVersionInfo...
[self at: key put: aBlock value] in Dictionary>>at:ifAbsentPut: in Block: [self at: key put: aBlock value]
Dictionary>>at:ifAbsent:
Dictionary>>at:ifAbsentPut:
MCWorkingCopy class>>infoFromDictionary:cache:
MCMczReader>>extractInfoFrom:
MCMczReader>>loadVersionInfo
MCMczReader(MCVersionReader)>>info
MCMczReader(MCVersionReader)>>basicVersion
MCMczReader(MCVersionReader)>>version
[:r | r version] in MCCacheRepository>>loadVersionFromFileNamed: in Block: [:r | r version]
[:s |
			(MCVersionReader readerClassForFileNamed: aString) ifNotNil:
				[:class | aBlock value: (class on: s fileName: (self pathForFileNamed: aString)]] in MCCacheRepository(MCFileBasedRepository)>>versionReaderForFileNamed:do: in Block: [:s |...
[ :stream|
		val := aBlock value: stream ] in MCCacheRepository(MCDirectoryRepository)>>readStreamForFileNamed:do: in Block:[ :stream|...
[ aBlock value: stream ] in FileReference(AbstractFileReference)>>binaryReadStreamDo: in Block: [ aBlock value: stream ]
FullBlockClosure(BlockClosure)>>ensure:
FileReference(AbstractFileReference)>>binaryReadStreamDo:
MCCacheRepository(MCDirectoryRepository)>>readStreamForFileNamed:do:
MCCacheRepository(MCFileBasedRepository)>>versionReaderForFileNamed:do:
MCCacheRepository>>loadVersionFromFileNamed:
MCDirectoryRepository(MCFileBasedRepository)>>loadVersionFromFileNamed:
[
	SystemNotification signal: 'Loading ' , aFileName asString.
	"Use snapshot install instead of load to force loading. Otherwise monticello finds no changes and does not load anything."
	(self localRepository loadVersionFromFileNamed: aFileName) load ] in [
	MCMczReader readingOldExport: true.

	[
	SystemNotification signal: 'Loading ' , aFileName asString.
	"Use snapshot install instead of load to force loading. Otherwise monticello finds no changes and does not load anything."
	(self localRepository loadVersionFromFileNamed: aFileName) load ]
		on: MCMergeOrLoadWarning
		do: [ :warning |
			SystemNotification signal: 'Warning: ' , warning messageText asString.
			warning resume: true ] ] in MonticelloBootstrap>>loadPackageVersion: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:

	MCMczReader readingOldExport: true.
	[
	SystemNotification signal: 'Loading ' , aFileName asString.
	"Use snapshot install instead of load to force loading. Otherwise monticello finds no changes and does not load anything."
	(self localRepository loadVersionFromFileNamed: aFileName) load ]
		on: MCMergeOrLoadWarning
		do: [ :warning |
			SystemNotification signal: 'Warning: ' , warning messageText asString.
			warning resume: true ] ] in MonticelloBootstrap>>loadPackageVersion: in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
MonticelloBootstrap>>loadPackageVersion:

```

**Comment by MarcusDenker** [comment] 2023-10-30 13:43
Duplicate of https://github.com/pharo-project/pharo/issues/15164

**Closed as completed by MarcusDenker** 2023-10-30 13:43 UTC
