### ISSUE TITLE
FileBrowser has troubles with hidden system files on Windows

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#4792] opened 2019-10-02 08:39 UTC
The FileBrowser cannot work correctly with the hidden system files on the Windows platform.
When you try to navigate to the root of the C: drive, you get:
`FileDoesNotExistException: '/C:/hiberfil.sys'`

**Comment by akgrant43** [comment] 2019-10-02 11:27
I think this might be a duplicate of: https://github.com/pharo-project/pharo/issues/3571

**Closed as completed** 2019-10-02 11:27 UTC
