### ISSUE TITLE
The Find dialog is hanging the image

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#2865] opened 2019-03-18 10:34 UTC
The find dialog ends in infinite recursion and the image starts to be unresponsive to user interrupt very soon then.

1. open Playground
2. pres Ctrl+F to open the Find dialog
3. start to write someting

**Comment by StephanEggermont** [comment] 2019-03-26 10:21
Caused by #2789

**Comment by pavel-krivanek** [comment] 2019-03-27 08:09
the stack:
```1
RubTextFieldArea(RubAbstractTextArea)>>privateReplaceFrom:to:with:
2
RubTextFieldArea>>privateReplaceFrom:to:with:
3
RubTextEditor>>zapSelectionWith:
4
RubTextEditor>>replace:with:and:
5
RubTextEditor>>replaceSelectionWith:
6
[ aStrinbeEditableWhile:ifFalse:self deselect ] ] ] in RubTextFieldArea(RubAbstractTextArea)>>updateTextWith:
7
BlockClosure>>ensure:
8
RubTextFieldArea(RubAbstractTextArea)>>beEditableWhile:
9
[ self  beEditableWhile:ifFalse:self deselect ] ] ] in RubTextFieldArea(RubAbstractTextArea)>>updateTextWith:
10
RubTextFieldArea(RubAbstractTextArea)>>handleEdit:
11
RubTextFieldArea(RubAbstractTextArea)>>updateTextWith:
12
RubTextScrollPane>>updateTextWith:
13
RubPluggableTextFieldMorph(RubScrolledTextMorph)>>updateTextWith:
14
RubPluggableTextFieldMorph>>update:
15
MorphChanged>>deliverTo:
16
RubPluggableTextFieldMorph(Morph)>>handleUpdate:
17
MessageSend>>value:
18
MessageSend>>cull:
19
MessageSend>>cull:cull:
20
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver:
21
BlockClosure>>on:do:
22
BlockClosure>>on:fork:
23
AnnouncementSubscription>>deliver:
24
[ "Ensure delivery to remaining announcements" subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt:
25
BlockClosure>>ifCurtailed:
26
SubscriptionRegistry>>deliver:to:startingAt:
27
SubscriptionRegistry>>deliver:to:
28
SubscriptionRegistry>>deliver:
29
Announcer>>announce:
[8:39] Pavel:
RubFindReplaceDialogWindow(Morph)>>doAnnounce:
31
RubFindReplaceDialogWindow(Morph)>>changed:
32
RubFindReplaceDialogWindow>>findPolicyChanged
33
RubFindReplaceDialogWindow>>update:
34
[ :aDependent | aDependent update: aParameter ] in RubFindReplaceService(Model)>>changed:
35
DependentsArray>>do:
36
RubFindReplaceService(Model)>>changed:
37
RubFindReplaceService>>findPolicyChanged
38
RubFindReplaceService>>findText:
39
RubFindReplaceDialogWindow>>findText:
40
RubPluggableTextFieldMorph>>acceptTextInModel
41
RubPluggableTextFieldMorph(RubScrolledTextMorph)>>acceptContents
42
RubPluggableTextFieldMorph(RubScrolledTextMorph)>>textChanged
43
RubPluggableTextFieldMorph(RubTextFieldMorph)>>textChanged
44
RubPluggableTextFieldMorph>>textChanged
45
RubTextScrollPane>>textChanged
46
RubTextFieldArea(RubAbstractTextArea)>>paragraphReplacedTextFrom:to:with:
47
textArea paragraphReplacedTextFrom: start to: stop with: aText ] in RubParagraph>>replaceFrom:to:with:
48
BlockClosure>>ensure:
49
RubParagraph>>disableDrawingWhile:
50
RubParagraph>>replaceFrom:to:with:
51
Message>>sendTo:
52
[ aMessage sendTo: next ] in RubOpeningClosingDelimiterDecorator(RubParagraphDecorator)>>doesNotUnderstand: #replaceFrom:to:with:
53
BlockClosure>>on:do:
54
RubOpeningClosingDelimiterDecorator(RubParagraphDecorator)>>doesNotUnderstand: #replaceFrom:to:with:
55
Message>>sendTo:
56
[ aMessage sendTo: next ] in RubExtraSelectionDecorator(RubParagraphDecorator)>>doesNotUnderstand: #replaceFrom:to:with:
57
BlockClosure>>on:do:
58
RubExtraSelectionDecorator(RubParagraphDecorator)>>doesNotUnderstand: #replaceFrom:to:with:
59
RubTextFieldArea(RubAbstractTextArea)>>privateReplaceFrom:to:with:
```

the DNU i  #replaceFrom:to:with: is a standard way how the decorator works, the problem is in incompatility of the `RubFindReplaceService`

When you disable code in `RubFindReplaceService>>#findPolicyChanged` then it does not hang, however it of course does not highlight the text and at the end it raises `Error: This block accepts 1 argument, but was called with 0 arguments.`

My personal assumption is that this shitty find replacement service is trying to do the thing that it did all the time - to highlight the text being searched in all active Rubric editors. The problem is that now even the entry field of the search box is a Rubric editor so it starts to loop...

**Comment by MarcusDenker** [comment] 2019-11-20 09:57
was merged

**Closed as completed by MarcusDenker** 2019-11-20 09:57 UTC
