### ISSUE TITLE
Slider moves on mouse move without draging

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#6202] opened 2020-04-22 12:09 UTC
**Describe the bug**
The morphic Slider (and the spec and spec2) moves when move mouse over the object even if not dragging.

**To Reproduce**
1. Open the spec or spec2 examples.
2. move the muse over a slider
3. The slider moves even if not dragging.

**Expected behavior**
The slider will move only when dragging

**Version information:**
 - OS: Windows 10 and OSX Catalina
 - Version: [e.g. 1.6.1]

**Expected development cost**
It has to be ported from Pharo 9, It shouldn't take much time.
(If a get free time I will do it, leving a comment indicating that I'm on it).

**Additional context**
This error was corrected in Pharo 9 by me, be aware that also the scrollbar was patched, and @guillep  has done some corrections on Morphic related with "hand".

**Comment by VincentBlondeau** [comment] 2021-04-25 16:21
The bug is still in the last version:
Pharo9.0.0
build: 1354, commit: 1846e54, date: 23 April 2021

The transcript is scrollable only with the wheel and not with the slider on the right. 
![TpQMMYzoGd](https://user-images.githubusercontent.com/4706329/116001042-e5bd7700-a5f2-11eb-87be-fa0636b19845.gif)

**Comment by Ducasse** [comment] 2021-04-25 16:44
Yes I saw this behavior also in calypso (no Spec20) but I could not reproduce it. 
The scroll bar was getting mad , scrolling down and up alone. 
My mac crashed when I tried to record it. Are you able to reproduce it? 
I'm on mac and you on windows so this is good. We may have a glitch in the event handling via SDL20.

**Comment by VincentBlondeau** [comment] 2021-04-25 17:11
Can be reproduced with calypso also:

![02Ip2FcyxB](https://user-images.githubusercontent.com/4706329/116002382-c83fdb80-a5f9-11eb-86e3-738945ee054d.gif)

Steps:
Having a long method (copy paste code from a short one)
Scroll up or down once
Use the Slider to move around

**Comment by VincentBlondeau** [comment] 2021-04-25 17:21
Maybe linked with: https://github.com/pharo-project/pharo/issues/6097 ?

**Comment by Ducasse** [comment] 2021-04-25 20:46
Yes my method was long, I was working on converting help into microdown.

**Comment by Ducasse** [comment] 2021-04-25 20:48
Indeed it looks related to #6097. Certainly an event conversion problem.
I hope that @guillep  will have a look when he is back from vacation in a week.

**Comment by guillep** [comment] 2021-04-30 15:33
I've tried for 30' to reproduce this one with no luck. I should be doing something different from all of you :/

**Comment by Ducasse** [comment] 2021-07-19 19:28
Hi vincent 
Is this issue fixed?
It was my impression. 
S

**Comment by David5i6** [comment] 2021-07-20 09:10
Hi, just tested with paro 9.0 sable and the bug is still there.

⁣Obtener BlueMail para Android ​

**Comment by VincentBlondeau** [comment] 2022-05-23 13:23
Fixed in Pharo 10. Suggesting to close the issue.

**Closed as completed** 2022-05-23 13:43 UTC
Labels: Type: Bug, Priority: Critical, Company: Lifeware
