### ISSUE TITLE
Search senders / implementors is broken

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7288] opened 2020-09-10 13:20 UTC
**Describe the bug**
It is not possible anymore to search for senders implementors if you do not provide the exact selector. ex:: `configuration: with:`
If you provide a selector with a space or an argument in the middle, search will just return an empty list!
ex: `configuration: with:` or `configuration: 'c' with: 'r'`

**To Reproduce**
1. Open a playground
2. type  `configuration: with:` or `configuration: 'c' with: 'r'` and hit CMD+M
2. type  `configuration:with:` and hit CMD+M

**Expected behavior**
Search should be able to detect and ignore spaces and arguments.

**Version information:**
Pharo 9.0.0
Build information: Pharo-9.0.0+build.640.sha.b0ef821d4e6a5756e4221a1897c43e7c305fb8dd (64 Bit)

**Comment by Ducasse** [comment] 2020-09-10 13:29
Yes in the playground and any command use. Super annoying.

**Comment by bergel** [comment] 2020-09-11 17:03
I confirm this bug
I experienced this today:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/393742/92953139-7dee5d80-f461-11ea-8961-d1412b512478.png">

**Comment by Ducasse** [comment] 2020-09-13 06:54
We know it and I was already reported in another bug entry. It is simply due to the fact that the identification should be extracted from the rubric text editor and right now the commands cannot use such symbol extraction.

**Comment by MarcusDenker** [comment] 2020-09-14 12:53
duplicate of https://github.com/pharo-project/pharo/issues/7165

**Closed as completed by MarcusDenker** 2020-09-14 12:53 UTC
Labels: Type: Bug, Status: Duplicate, Priority: Critical
