### ISSUE TITLE
Method history browser is broken

### ISSUE THREAD

**Issue by bouraqadi** [guillep/pharo-core#7283] opened 2020-09-10 09:00 UTC
**Describe the bug**
In Pharo 8 & 9 method history browser has multiple issues :
1. empty package 
2. Author name is missing
3. version timestamp is missing
4. All buttons are broken except for revert!

Compare View from Pharo 8 and 9 to the one from Pharo 7 
![pharo8+9-methodHistory](https://user-images.githubusercontent.com/435343/92706038-80af5c80-f354-11ea-8e3e-9dc4dc315b77.png)

![pharo7-methodHistory](https://user-images.githubusercontent.com/435343/92706502-dab02200-f354-11ea-9076-6f9f838bf7c8.png)

**Comment by sic-f** [comment] 2020-09-26 10:50
I've checked these on the latest stable version (v.8) and all of these aren't present at all.

Does this mean these were not even implemented yet in the first place? Maybe all of these need specs?

**Comment by kasperosterbye** [comment] 2021-02-05 05:29
This is an odd bug in some way. As of today, Pharo 9 (build: 1106, commit: 9afeccc - February 5th-2021) status is that 
* The buttons work
* package is not shown - this is a menace as package can mean iceberg and browser package. I tried to add a class to iceberg, and that did not fill the package column.
* Author and timestamps are not shown (which was the original complaint)
* If new versions are created while the history window is open, these new versions are not added to the list.
* When you select a method from the list, it is unclear what the two code windows shows. Adding labels `previous` and `selected` above the two panes would perhaps help to make clear what is shown.
* (Very minor - the title shows method with symbol syntax `#method` - unlike the browser which do not include `#`.

There was a brief email exchange (http://forum.world.st/pharo-8-method-versions-how-to-see-author-timestamp-td5116685.html) on this issue.
I tend to agree with those authors that author and timestamp are useful with this history.

The class supposedly implementing this tool is class `VersionBrowser`

**Comment by kasperosterbye** [comment] 2021-02-05 07:27
A closer look at`VersionBrowser` leads me to believe that the problem is in the transition from Spec1 to Spec2 (I am comparing Pharo7 and Pharo9 implementations), and in particular the usage of`MessageBrowser`. 

In Spec1 (Pharo7), tables was build by the row whereas in Spec2 they are build by the column. In Spec1`MessageBrowser` could be used by`VersionBrowser` as they both had three columns, but just build completely different rows. 
See methods `VersionBrowser>>browseForList:` and `MethodBrowser>>wrapItem:`/`MethodBrowser>>initializeWidgets`.

In Pharo9, `VersionBrowser` and `MethodBrowser` both depend on `MessageList`. But tables in Spec2 are column based, and`MessageList` defines the columns for`MethodBrowser`, not for`VersionBrowser`.

**Comment by kasperosterbye** [comment] 2021-02-05 10:22
Based on recent comments from Esteban in the [above mentioned forum conversation](http://forum.world.st/pharo-8-method-versions-how-to-see-author-timestamp-td5116685.html), I suggest to close this issue.

**Comment by MarcusDenker** [comment] 2021-02-05 10:24
This is fixed. We still have a problem, but it is another one (when you select source in the dropdown)

**Closed as completed by MarcusDenker** 2021-02-05 10:24 UTC
Labels: Type: Bug
