### ISSUE TITLE
Regression: DropListMorph content is now selectable

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3013] opened 2019-03-26 09:57 UTC
With recent Rubric changes, DropListMorph changed to use rubric instead of pluggable text morph. This causes a regression because now the text is selectable. 

This cause multiple problems such as it is now harder to open the list or RSOD if you select the text and change for a shorter option.

**Comment by VincentBlondeau** [comment] 2019-03-26 10:18
@estebanlm said it was fixed in Spec but the issue related was closed because it is noisy: 
https://github.com/pharo-project/pharo/issues/2962#issuecomment-476405731

**Comment by jecisc** [comment] 2019-03-26 10:20
This is a different issue. 

Your issue is with the list, mine is with drop list morph.

**Comment by StephanEggermont** [comment] 2019-03-26 10:21
Caused by #2789

**Comment by jecisc** [comment] 2019-03-26 10:21
I found the problem. I'm doing a PR.

**Closed as completed** 2019-03-29 18:10 UTC
