### ISSUE TITLE
Removing a method shows "the message: #xxxx has YY sender" (missing an s)

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2567] opened 2019-02-15 12:31 UTC
Small issue, but the prompt for refactor remove is grammatically incorrect - if more than 1 sender, it should add an s.

**Comment by bencoman** [comment] 2019-02-16 01:32
Can you isolate which method to fix this in?
For example this displays four candidates...
```
SystemNavigation default browseAllSelect: [ :m | 
	{ 'the' . 'message' . 'has' . 'sender' } 
		allSatisfy: [ :s | m sourceCode includesSubstring: s ]
	]
```

**Comment by macta** [comment] 2019-02-20 10:55
@bencoman nice compact query for searching... I'm pretty sure its
```SystemNavigation>>confirmRemovalOf:on: ```

I'll queue up a moment to propose a fix unless someone beats me to it.

**Comment by macta** [comment] 2019-02-20 20:39
It turns out this is in Calypso code - ClyBrowserMorph>>requestRemoveMethodStrategyFor: so need to fork their instead.

And there is a strong similarity to SystemNavigation>>confirmRemovalOfSelectors: aCollection on: aClass

So not sure if the latter needs to go away as Calypso replaces it (no senders?). I think that is a seperate pr though.

**Comment by macta** [comment] 2019-02-20 23:04
Not sure why the PR doesn't get auto referenced here - https://github.com/pharo-project/pharo/pull/2673

**Comment by Ducasse** [comment] 2019-02-22 13:19
Please use Fixes: #number so that the issue is closed automatically when the PR is merged :)

**Closed as completed by Ducasse** 2019-02-22 13:19 UTC
