### ISSUE TITLE
Missing class side variable after reloading a Trait which used another Trait, from GitHub + image unstability and crashs

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#14749] opened 2023-09-22 16:34 UTC
**Bug description**
Class side variable of a Trait is removed after reloading the Trait.
Due to this problem, my Pharo image is unstable and a lot of crashes can appears.
When I'm reloading the package manually, the var is appears! But the system is not stable 

The Trait on [GitHub](https://github.com/OpenSmock/Molecule/blob/dev-99/Molecule-Tests/MolDirtyType.trait.st) (look at `anInstanceVariable`) : 
```smalltalk
Trait {
	#name : #MolDirtyType,
	#classInstVars : [
		'anInstanceVariable'
	],
	#traits : 'MolComponentType',
	#classTraits : 'MolComponentType classTrait',
	#category : #'Molecule-Tests-Resources - Contracts'
}
```

The Trait after loading the project into Pharo : 
![image](https://github.com/pharo-project/pharo/assets/49183340/896d4451-37ff-4665-acdd-e144ec0399da)
Look at the red methods which are using `anInstanceVariable`.

The Trait after re-loading manually the package : 
![image](https://github.com/pharo-project/pharo/assets/49183340/ceb5470e-b1b5-461e-a826-0e92853f2552)
![image](https://github.com/pharo-project/pharo/assets/49183340/31663a34-6a4c-4282-a2a5-2baab401f50c)
Red methods are always here.
![image](https://github.com/pharo-project/pharo/assets/49183340/15bbd460-6def-4e51-aa1c-f7bfddd2afbf)
![image](https://github.com/pharo-project/pharo/assets/49183340/1a00568c-e7ac-449c-b4eb-2010b19c0f7d)
The image is always unstable, var is here but not considered.

**To Reproduce**
1. Create a Trait1
2. Define another Trait2 which uses Trait1
3. Define a class side variable into Trait2
4. Publish the code into GitHub
5. Create a new image
6. Reload the project : the var in Trait2 is missing

The problem is present when loading manually (Add button) or from a baseline script.

**About crashes and unstability**
The image is unstable at the moment of a Trait1 with a class side var uses a Trait2, or at the moment of we create a class side var in a Trait 1 uses Trait 2.

**Expected behavior**
Variable should be exists, but missing.

**Screenshots**

**Version information:**
 - OS: Windows 11 Pro 64 bits & Windows 10 Pro 64 bits
 - Version: Pharo 12 & Pharo 11 & Pharo 10

**Comment by jecisc** [comment] 2023-09-22 16:38
There was some updates in loading code in Pharo 12 but if it also happens in Pharo 11 it is probably not related to that. I'll try to find some time next week to look into it since I recently learned more about the code managing loading classes and traits,

**Comment by labordep** [comment] 2023-09-23 11:26
Thanks @jecisc :) this problem is impacting our architecture framework at the core of all our applications :(

**Comment by Ducasse** [comment] 2023-09-24 17:31
Pierre do I guess correctly that it was working correctly in P10?

**Comment by Ducasse** [comment] 2023-09-24 17:33
This is really strange because Moose is heavily using traits and they do not experience this problem so I'm really curious. 
May be this is a metaclass level problem.

**Comment by labordep** [comment] 2023-09-24 17:55
> Pierre do I guess correctly that it was working correctly in P10?

I have tested to load my project in Pharo 10, you can try with this script : 

```smalltalk
Metacello new
   baseline: 'Molecule';
   repository: 'github://OpenSmock/Molecule:dev-99';
   load.
```

And this is the same problem :/ 

![image](https://github.com/pharo-project/pharo/assets/49183340/6c3f58c1-3b7d-440e-b31e-cf3cbcca52cf)

And on GitHub : 

![image](https://github.com/pharo-project/pharo/assets/49183340/d0576fec-d5f5-4622-bd63-6dc70b9ebfa0)

Very strange! And the commit window is curious because it seams that the system know there is a difference but it cannot show it correctly : 

![image](https://github.com/pharo-project/pharo/assets/49183340/4171ad0f-da64-4125-be07-0c1cad91de86)

**Comment by labordep** [comment] 2023-09-24 18:01
May be Molecule can impact in a way this bug, can you reproduce this problem ?
=> No (see below)

**Comment by labordep** [comment] 2023-09-24 18:10
I writted a project to reproduce :  https://github.com/labordep/Project14749
Add manually the project with the "Add" button works and my Trait is not yet using another Trait.

<blockquote><img src="https://opengraph.githubassets.com/6a866052684ccf1214f5ff5d1597b23ee5a8f9a2839bbbbae132936a5b0bbeb9/labordep/Project14749" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/labordep/Project14749">GitHub - labordep/Project14749: Test project to reproduce issue 14749</a></strong></div><div>Test project to reproduce issue 14749. Contribute to labordep/Project14749 development by creating an account on GitHub.</div></blockquote>

**Comment by labordep** [comment] 2023-09-24 18:14
Ok I reproduced it clearly !

![image](https://github.com/pharo-project/pharo/assets/49183340/5a6de32e-88c5-49e9-81ae-dc9a45906fbe)

I update my issue, the problem appears when the Trait uses another Trait.
The image **was instable and crash at the instant of my Trait (with a class side var) uses another Trait.**
I update my issue with this information.

**Comment by jecisc** [comment] 2023-09-25 10:02
I found the problem but I do not know yet how to fix it. 

The problem is that for traits we have MCTraitDefinition and MCClassTraitDefinition in Monticello. 

Things such as class slots and managed by MCTraitDefinition and are installed correctly. But the class trait composition is set by MCClassTraitDefinition afterward and this removes anything else configured in the class side. 

I don't understand why we have both those classes and not just one. I need to talk to Pablo to see if we can unify. But anyway, knowing the root of the problem I'll at least be able to produce a workaround.

**Comment by jecisc** [comment] 2023-09-25 14:08
So I did a workaround for Pharo 11: https://github.com/pharo-project/pharo/pull/14768

And for Pharo 12 I have a PR on Pharo and a PR on Tonel with a better cleaning and both are passing:
https://github.com/pharo-project/pharo/pull/14766
https://github.com/pharo-vcs/tonel/pull/112

I am now waiting for reviews and this should fix your problem

**Comment by labordep** [comment] 2023-09-25 14:31
> So I did a workaround for Pharo 11: #14768
> 
> And for Pharo 12 I have a PR on Pharo and a PR on Tonel with a better cleaning and both are passing: #14766 [pharo-vcs/tonel#112](https://github.com/pharo-vcs/tonel/pull/112)
> 
> I am now waiting for reviews and this should fix your problem

Thanks @jecisc! Keep me informed :)

**Comment by labordep** [comment] 2023-09-25 18:35
It looks good!
But a lot of crashs :/

![image](https://github.com/pharo-project/pharo/assets/49183340/0df0a93f-19a7-4408-9616-5f353dfbbb8e)

**Comment by jecisc** [comment] 2023-09-25 18:43
This should also be fixed in Pharo12 tomorrow

**Comment by labordep** [comment] 2023-09-25 18:48
> This should also be fixed in Pharo12 tomorrow

I have a lot of crashs in P11 :/ 
Especially when I'm playing with Iceberg, for example to load/view/explore/just select a branch with this specific Trait.

**Closed as completed** 2023-09-26 10:13 UTC
Labels: Type: Bug, Company: Thales

**Comment by jecisc** [comment] 2023-09-26 10:18
Note: The crashes are coming from a VM that is too old probably

**Comment by jecisc** [comment] 2023-09-26 10:19
@labordep This issue should be fixed in Pharo 12 too now

**Comment by labordep** [comment] 2023-09-27 11:31
> Note: The crashes are coming from a VM that is too old probably

Thanks @jecisc, I check this problem and if necessary open a new issue.

**Comment by labordep** [comment] 2023-09-29 09:10
@jecisc we cannot change the VM because of that : https://github.com/pharo-project/pharo/issues/13726

**Comment by labordep** [comment] 2023-10-01 10:08
@jecisc this is ok in the lastest VM from my Home, I haven't crashes 👍 .
At work we need to solve #13726. 
Thanks for the fix !
