### ISSUE TITLE
Browse does not bring the class

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#10733] opened 2022-01-15 07:53 UTC
- type BaselineOfDocumentationReader in a playground
- Press cmd-B
- you get a pop to select a class
- select BaselineOfNewToolsDocumentationReader
=> nothing

**Comment by Ducasse** [comment] 2022-01-15 07:53
![Capture 2022-01-15 at 08 52 27](https://user-images.githubusercontent.com/432549/149614287-7573e3aa-325f-4a4b-8402-684b581d015b.png)

**Comment by Ducasse** [comment] 2022-01-15 09:30
```
openMenuIn: aBlock
	| alternatives labels actions lines caption choice name interval requestor |
	
	"Turn off suggestions when in RubSmalltalkCommentMode
 	This is a workaround, the plan is to not do this as part of the exception"
 	requestor := compilationContext requestor.
 	((requestor class name = #RubEditingArea) and: [
 		requestor editingMode class name = #RubSmalltalkCommentMode])
 					ifTrue: [ ^UndeclaredVariable named: node name ].
	
	interval := node sourceInterval.
	name := node name.
	alternatives := self possibleVariablesFor: name.
	labels := OrderedCollection new.
	actions := OrderedCollection new.
	lines := OrderedCollection new.
	name first isLowercase
		ifTrue: [ 
			labels add: 'Declare new temporary variable'.
			actions add: [ self declareTempAndPaste: name ].
			labels add: 'Declare new instance variable'.
			actions add: [ self declareInstVar: name ] ]
		ifFalse: [ 
			labels add: 'Leave variable undeclared'.
			actions add: [ self declareUndefined ].
			lines add: labels size.
			labels add: 'Define new class'.
			actions
				add: [ 
					[ self defineClass: name ]
						on: Abort
						do: [ self openMenuIn: aBlock ] ].
			labels add: 'Declare new global'.
			actions add: [ self declareGlobal ].
			compilationContext requestor isForScripting ifFalse: 
				[labels add: 'Declare new class variable'.
				actions add: [ self declareClassVar ]].
			labels add: 'Define new trait'.
			actions
				add: [ 
					[ self defineTrait: name ]
						on: Abort
						do: [ self openMenuIn: aBlock ] ] ].	
	lines add: labels size.
	alternatives
		do: [ :each | 
			labels add: each.
			actions
				add: [ 
					self substituteVariable: each atInterval: interval.
					(ReparseAfterSourceEditing new newSource: self requestor text) signal ] ].
	lines add: labels size.
	labels add: 'Cancel'.
	caption := 'Unknown variable: ' , name , ' please correct, or cancel:'.
	choice := aBlock value: labels value: lines value: caption.
	^choice ifNotNil: [ self resume: (actions at: choice ifAbsent: [ compilationContext failBlock value ]) value ]
```

**Comment by Ducasse** [comment] 2022-01-15 09:36
Placing a halt in 

```
        labels add: 'Cancel'.
	caption := 'Unknown variable: ' , name , ' please correct, or cancel:'.
	choice := aBlock value: labels value: lines value: caption.
         self halt.
	^choice ifNotNil: [ self resume: (actions at: choice ifAbsent: [ compilationContext failBlock value ]) value ]
```
and executing in the debugger `(actions at: choice ifAbsent: [ compilationContext failBlock value ]) value`
raises: StPlaygroundInteractionModel does not understand correctFrom:to:with: in the following

```
substituteWord: correctWord wordInterval: spot offset: o
	"Substitute the correctSelector into the (presuamed interactive) receiver."

	self requestor correctFrom: (spot first + o)
					to: (spot last + o)
					with: correctWord.

	^ o + correctWord size - spot size
```

**Comment by Ducasse** [comment] 2022-01-15 09:43
`correctFrom:to:with: ` is implemented on RubTextEditor and RubTextArea. 
I do not know how to got from a `StPlaygroundInteractionModel` to such object.

**Comment by Ducasse** [comment] 2022-01-15 09:46
The owner is a `SpCodePresenter`

**Comment by MarcusDenker** [comment] 2022-01-17 06:59
CMD-B is fundamentally broken. See https://github.com/pharo-project/pharo/issues/8515

**Comment by MarcusDenker** [comment] 2022-01-17 07:03
The problem is that it compiled code, which already is not a good idea. Then it does this in *interactive* mode, which can not work as the "fix" code is not meant to work for this case (you do not want cmd-b to correct the code in the editor, ever).

The whole idea that cmd-b just evaluates code is too naive.

**Comment by MarcusDenker** [comment] 2022-01-20 14:57
First step:  

 https://github.com/pharo-spec/NewTools/pull/334

This adds the missing method. This is just a first step: After this we are in the same state as described in https://github.com/pharo-project/pharo/issues/10695

**Comment by MarcusDenker** [comment] 2022-01-21 08:32
Spec fix is merged

**Closed as completed by MarcusDenker** 2022-01-21 08:32 UTC
Labels: Type: Bug, Priority: Critical
