### ISSUE TITLE
Another bug with browse and implementor.... argh

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9993] opened 2021-09-19 09:47 UTC
![Capture 2021-09-19 at 11 46 42](https://user-images.githubusercontent.com/432549/133922942-50159b12-ab88-46ca-b1ab-638b68f28fde.png)

**Comment by Ducasse** [comment] 2021-09-19 09:48
I just selected metacelloPlatformAttributes and press implementors. 
I get a bug every 10 min.... 
There is something really wrong in the way we work.

**Comment by Ducasse** [comment] 2021-09-19 09:49
senders are broken too in latest image. 
How is it possible?

**Comment by MarcusDenker** [comment] 2021-09-20 06:39
this seems to the same problem as https://github.com/pharo-project/pharo/issues/9943

**Comment by MarcusDenker** [comment] 2021-09-20 08:29
(I close this as it is a duplicate)

**Closed as completed by MarcusDenker** 2021-09-20 08:29 UTC
Labels: Type: Bug

**Comment by astares** [comment] 2021-09-20 09:21
Yes - it is a duplicate of #9943. Same issue
