### ISSUE TITLE
Instance of ClyQueryBrowser did not understand #metaLevelScope

### ISSUE THREAD

**Issue by labordep** [guillep/pharo-core#12120] opened 2022-12-17 13:03 UTC
How to reproduce the bug : 

1. Find a Trait, in my example this is `TBlAlignable` trait from Bloc library (https://github.com/pharo-graphics/Bloc)
![image](https://user-images.githubusercontent.com/49183340/208242895-d456707c-b9e0-44ec-95d8-8cd90e45bc79.png)

2. Open the contextual menu to see trait users
![image](https://user-images.githubusercontent.com/49183340/208242915-aeb10b4d-674a-464b-9024-f257c9cd810f.png)

3. The trait users view is opening, in my example there are two users of the trait
![image](https://user-images.githubusercontent.com/49183340/208242960-c1712cf8-4d36-40f6-9470-ce47eb0c57fd.png)

4. Select a user in the list and the bug appears
![Pharo_7FrgEgk0N2](https://user-images.githubusercontent.com/49183340/208243132-f7c6bd4c-ad71-4ec3-9a34-c33e76ec5cfb.gif)

My config : 
- Pharo-11.0.0+build.383
- Windows 11 Pro

**Comment by fmqa** [comment] 2022-12-18 16:06
This is likely a duplicate of #12108 and is also solved by #12119

**Comment by MarcusDenker** [comment] 2022-12-19 08:03
yes, duplicate (I close this)

**Closed as completed by MarcusDenker** 2022-12-19 08:03 UTC
Labels: Type: Bug, Company: Thales
