### ISSUE TITLE
UITheme class is missing methods

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2593] opened 2019-02-18 18:09 UTC
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/22645
Status: Work Needed
Project: UI
Original Author: CyrilFerlicot
Date: 8 November 2018 10:18:38 am
	
Description:
	
In the instance side of UITheme, methods from the class side are called but not implemented. (For example #baseColor or #darkBaseColor).

They should be implemented even if they are subclass responsibility.

**Comment by jecisc** [comment] 2019-08-18 12:52
Still valid

**Comment by hilaire** [comment] 2019-09-18 15:59
Duplicate of #2539

**Comment by MarcusDenker** [comment] 2019-09-19 12:13
Closed as Duplicate

**Closed as completed by MarcusDenker** 2019-09-19 12:13 UTC
