### ISSUE TITLE
RBEnvironmentVisitor>>#visitClassEnv: has dead code

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#14433] opened 2023-08-04 12:38 UTC
This might be dead code. Maybe it can interest @balsa-sarenac or @Ducasse

**Comment by Ducasse** [comment] 2023-08-06 19:56
Thanks. I do not even know if this method is used. In fact the environment should be used for more than the refactoring engine.

**Comment by MarcusDenker** [comment] 2023-10-05 11:37
Duplicate of https://github.com/pharo-project/pharo/issues/14721

**Closed as completed by MarcusDenker** 2023-10-05 11:37 UTC
Labels: Type: Cleanup
