### ISSUE TITLE
#description was sent to nil in MCDefinitionIndex

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#10974] opened 2022-03-08 14:54 UTC
**Bug description**
After adding a new Trait to a class when committing from Iceberg there is an error:

<img width="1792" alt="Screenshot 2022-03-08 at 15 24 30" src="https://user-images.githubusercontent.com/3534711/157258030-a9ebdaf3-3869-423a-abf1-edb38ca4cd2b.png">

The change in this case is just adding a trait to a class that has class side methods. The error does not happen if the class has no class side methods.
<img width="1792" alt="Screenshot 2022-03-08 at 15 24 12" src="https://user-images.githubusercontent.com/3534711/157262187-eb9ed397-8c63-48f0-8812-28c115e80274.png">

Seems that this appeared after the fix for https://github.com/pharo-project/pharo/issues/10623

Tested on MacOs.

Image:
Pharo10.0.0 Build information: Pharo-10.0.0+build.471.sha.96da1f9dc627ee412571169a8ab7e9031bf7f7be (64 Bit)

VM:
Pharo 9.0.10 built on Nov 25 2021 19:19:50 Compiler: 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29)
VMMaker versionString v9.0.10 - Commit: db558908 - Date: 2021-11-25 11:12:35 +0100
CoInterpreter * VMMaker-tonel.1 uuid: 87063cbb-028e-0d00-bd44-58660a412f2c Nov 25 2021
StackToRegisterMappingCogit * VMMaker-tonel.1 uuid: 87063cbb-028e-0d00-bd44-58660a412f2c Nov 25 2021

**Comment by seandenigris** [comment] 2022-03-18 15:08
As a workaround, adding this first line to the beginning of the method *seemed* to bypass as I successfully committed the trait addition:
```smalltalk
definitionLike: aDefinition ifPresent: foundBlock ifAbsent: errorBlock
	| definition |
	aDefinition ifNil: [ ^ errorBlock value ]. "this line added"
	definition := definitions at: aDefinition description ifAbsent: [].
	^ definition
		ifNil: errorBlock
		ifNotNil: [foundBlock value: definition]
```

**Comment by hernanmd** [comment] 2023-09-29 13:37
I couldn't reproduce this bug in the latest Pharo 12. Could you confirm or share the exact steps to reproduce it?

<img width="1307" alt="Screenshot 2023-09-29 at 15 39 44" src="https://github.com/pharo-project/pharo/assets/4825959/8b21c331-77fa-4a38-b4bd-f52b7c2c9e36">

**Comment by jecisc** [comment] 2023-09-29 16:09
I've updated code about MC model in Pharo 12. Maybe that fixed the problem?

**Comment by jecisc** [comment] 2023-09-29 16:26
I'll close for now and we can reopen in case we encounter it again

**Closed as completed by jecisc** 2023-09-29 16:26 UTC
Labels: Type: Bug
