### ISSUE TITLE
"ProfileIt" doesn't work

### ISSUE THREAD

**Issue by dmatveev** [guillep/pharo-core#12137] opened 2022-12-20 10:10 UTC
**Bug description**

Trying to profile my code in Playground using the "Profile" it menu, but it doesn't work.

**To Reproduce**

In playground: `1000 timesRepeat: [10 factorial]` -> Profile it -> nothing.

**Expected behavior**

Profiler is open with the profiling results.

**Screenshots**

n/a

**Version information:**

OS: Windows
Version: 11 x86_64
Pharo Version: 10 (Pharo-10.0.0+build.535.sha.f72dfb7a95cb072d485373b28b33e8c256b9a3f2 (64 Bit))

**Expected development cost**

n/a

**Additional context**

Origin: #12125

**Comment by astares** [comment] 2022-12-31 01:31
we can close this one similar to PR#12125 (see PR for details)

**Comment by MarcusDenker** [comment] 2023-01-02 07:13
We closed #12125 to have this issue here without the discussion.

 Huge discussions about un-related things mean that everyone would have to read and understand that discussion before realizing it is unrelated.  Issue tracker entries have to be as simple as possible.

 I would only add "on windows" to the title if it happens *only* on windows...

I changes the name of the issue and removed the Windows part of the description: OS specific problems tend to be of the *very* hard kind, as this implies maybe even VM specific problems. But this is not the case here.

**Comment by hernanmd** [comment] 2023-01-17 23:02
I could reproduce it. 
It doesn't work anymore in Pharo 11 on macOS either.

**Comment by JanBliznicenko** [comment] 2023-12-11 14:25
Well, this might be the reason :)

![CommandIsTODO](https://github.com/pharo-project/pharo/assets/9571633/98208149-bcc2-4553-87ef-c6dd60777c6e)

I believe it was not implemented because TimeProfiler is being discontinued (https://github.com/pharo-project/pharo/issues/12334) and it needs to be implemented using ProfilerPresenter. However, in order to do that, ProfilerPresenter needs to be able to work with blocks: https://github.com/pharo-project/pharo/issues/12840

**Closed as completed** 2023-12-13 12:48 UTC
Labels: Type: Bug
