### ISSUE TITLE
FFICalloutAPITest are often crashing the VM on the CI

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4411] opened 2019-08-23 13:33 UTC
The CI tests are often crashing the Pharo image during test phase.

It often happen while running tests from FFICalloutAPITest.

I saw the problem on OSX and Windows slave at least.

Example of stack:

Window tests:

```
*** Warning: Deprecation: The method SpPresenter>>#newTree called from SpSearchableTree>>#initializeWidgets has been deprecated.

Use #newTreeTable instead

The method SpPresenter>>#newTree called from SpSearchableTree>>#initializeWidgets has been deprecated.
Use #newTreeTable instead


*** Warning: Deprecation: The method SpPresenter>>#newTree called from SpSearchableTree>>#initializeWidgets has been deprecated.

Use #newTreeTable instead

The method SpPresenter>>#newTree called from SpSearchableTree>>#initializeWidgets has been deprecated.
Use #newTreeTable instead


*** Warning: Deprecation: The method SpPresenter>>#newTree called from SpSearchableTree>>#initializeWidgets has been deprecated.

Use #newTreeTable instead

The method SpPresenter>>#newTree called from SpSearchableTree>>#initializeWidgets has been deprecated.
Use #newTreeTable instead


*** Warning: Deprecation: The method SpPresenter>>#newTree called from SpSearchableTree>>#initializeWidgets has been deprecated.

Use #newTreeTable instead

Error in the VM thread

Reason: out of memory



Primitive trace:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

findNextHandlerOrSignalingContext

findNextUnwindContextUpTo:

terminateTo:

**IncrementalGC**



Stack backtrace:

	[FF0763AD] ??? + 0x0 in (null)

	[00000000] ??? + 0x0 in (null)



Smalltalk stack dump:

  0xac9124 M ProvideAnswerNotification(Exception)>receiver 0x160e358: a(n) ProvideAnswerNotification

  0xac913c M ProvideAnswerNotification(Exception)>signal 0x160e358: a(n) ProvideAnswerNotification

  0xac9154 M ProvideAnswerNotification(Exception)>signal: 0x160e358: a(n) ProvideAnswerNotification

  0xac9170 M ProvideAnswerNotification class(Exception class)>signal: 0x221fe58: a(n) ProvideAnswerNotification class

  0xac918c M NonInteractiveUIManager>nonInteractiveWarning: 0x4830020: a(n) NonInteractiveUIManager

  0xac91a8 M NonInteractiveUIManager>debugProcess:context:label:fullView:notification: 0x4830020: a(n) NonInteractiveUIManager

  0xac91d4 M NonInteractiveUIManager(UIManager)>debugProcess:context:label:fullView: 0x4830020: a(n) NonInteractiveUIManager

  0xac91fc M Process>debug:title:full: 0x4832270: a(n) Process

  0xac9220 M Process>debug:title: 0x4832270: a(n) Process

  0xac9240 M Context>cannotReturn: 0x160e438: a(n) Context

  0xac9260 M FFICalloutAPITest(TestCase)>performTest 0x160e498: a(n) FFICalloutAPITest

 0x160e4a8 is not a context
```

**Comment by VincentBlondeau** [comment] 2019-08-30 14:09
I can reproduce the crash with the latest image under Windows 10 x64. Here is the trace. I need to run the test class 3 times to make the image crash though. At the second run, the test is red then it crashes:

[crash.zip](https://github.com/pharo-project/pharo/files/3560225/crash.zip)

**Comment by MarcusDenker** [comment] 2021-03-19 11:15
is this still happening?

**Comment by VincentBlondeau** [comment] 2021-03-23 09:50
I cannot reproduce anymore. I think you can close it Marcus.

**Closed as completed** 2021-03-23 10:03 UTC
