### ISSUE TITLE
Crazy Editor horizontal Scroll

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#6097] opened 2020-04-01 16:43 UTC
**Describe the bug**
In a code editor (rubric) when the horizontal scrollbar is shown, and move mouse arond the text area and scroll area, then scroll goes crazy.

**To Reproduce**
1. Open System Browser
2. Edit some code (not so small)
3. Disable Word Wrap
4. Resize screen to force horizontal scrollbar apear
5. Move the mouse over the horizontal scrollbar

**Expected behavior**
scroll will remain unmodified until drag the horizontal scrollbar.

**Screenshots**
Well, not in movement, but this is one of the cases in wich it happens:
![imagen](https://user-images.githubusercontent.com/7849541/78163018-0515bf00-7448-11ea-88c3-58d93d50c51a.png)

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: Windows 10
 - Version: Pharo 9.0
 - Commit info: Pharo-9.0.0+build.202.sha.2799b9114f70ce3931612334575cd42509315882 (64 Bit)

**Additional context**
I'm working on a Simple LogWindow (something like Transcript) and using Rubric TextModel. It happens here too.

**Comment by guillep** [comment] 2020-04-01 16:59
Hi @David5i6 

Yes, this is an issue with the events. The VM seemingly does not send scrolling events as such to the image. Instead, it sends Ctrl+Arrow key events. Then those events are forwarded to morphic. You can check `HandMorph>>generateKeyboardEvent:` for some archeology :). The relvant piece of code is the following:

```
"This piece of code handles the creation of scrolling events. When a scroll is done by the user, the VM forwards a keystroke event with the up/down key. So we reconvert it to a MouseWheelEvent in that case."
	(type = #keystroke 
	 and: [(buttons anyMask: 16) 
	  and: [{Character arrowUp. Character arrowDown} includes: (charCode asCharacter)]])
		ifTrue: [^ MouseWheelEvent
					fromCharacter: charCode asCharacter
					position: lastMouseEvent cursorPoint
					buttons: buttons
					hand: self
					stamp: stamp].
```

One problem is that the generated VM keyboard events seem to follow some strange pattern that the text editors transform in strange scrolling patterns. Another problem is that this seems to work only with arrow up and arrow down. Maybe handling arrow left and right solves it? Yet another potential problem is that maybe we are not able to differentiate real Ctrl + arrow keys from generated ones?

This may already be fixed in the (beta) headless vm, since it uses another windowing backend that gets scrolling events.
- https://www.youtube.com/watch?v=6iAzRYybY_M
- you can get it and run it from the command line: https://get.pharo.org/64/vmHeadless90

<blockquote><img src="https://i.ytimg.com/vi/6iAzRYybY_M/hqdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=6iAzRYybY_M">Pharo TechTalk: Headless VM</a></strong></div><div> </div></blockquote>
<blockquote></blockquote>

**Comment by David5i6** [comment] 2020-04-01 20:21
Hi ! Just downloaded the headless VM, but the problem in the code editor is still there.

**Comment by jecisc** [comment] 2022-11-29 16:08
I cannot reproduce it

**Comment by MarcusDenker** [comment] 2022-12-01 09:55
I have not seen this for a long time either. I close the issue.

**Closed as completed by MarcusDenker** 2022-12-01 09:55 UTC
Labels: Type: Bug, Project: Graphics, Priority: Critical
