### ISSUE TITLE
Paragraph users should be migrated to RubParagraph 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2851] opened 2019-03-16 19:49 UTC

**Comment by MarcusDenker** [comment] 2019-03-17 08:53
I added a Project board for the Rubric/TextEditor:  https://github.com/pharo-project/pharo/projects/4

This way one can collect all the related issues (and even PRs if needed).

**Comment by Ducasse** [comment] 2019-09-13 09:34
Still valid

**Comment by guillep** [comment] 2020-04-06 15:35
There are 11 references in my pharo 90 image build 215 e49c5d58ced87c0738cd86033f24bb6591b706b1

![image](https://user-images.githubusercontent.com/708322/78576439-f86cde80-782c-11ea-8935-5d4b551823b9.png)

Some of them seem easily fixable.

**Comment by guillep** [comment] 2023-01-27 10:41
Duplicate of https://github.com/pharo-project/pharo/issues/2851

**Closed as completed by guillep** 2023-01-27 10:41 UTC
Labels: Type: Cleanup, Project: Graphics
