### ISSUE TITLE
URL HACKED BY CASINOS GAMES

### ISSUE THREAD

**Issue by ballesta** [guillep/pharo-core#14807] opened 2023-09-28 11:50 UTC
**Bug description**
Several URL in the book have been hacked and display advertising for casino games.

Example : http:// PharoByExample.org/ fr

**To Reproduce**
1. Go to 'Pharo by example' pdf book
2. Click on 'http:// PharoByExample.org/ fr' in PDF BOOK on page 18

**Screenshots**

**Version information:**
 - Version: [e.g. 1.6.1]
 - Pharo Version [e.g 9]

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

**Additional context**

**Comment by MarcusDenker** [comment] 2023-09-28 12:13
The problem is that we did not own the domain, the owner stopped paying without asking us to take over the domain and like it is common in this case, someone else registered it. 

I do not see any way to get the domain back (short of trying to buy it, which I think makes no sense).

This is sad, as it would have been so easy to take over the domain, but I did not even know that there were plans to stop paying for it

**Comment by MarcusDenker** [comment] 2023-09-28 12:22
Thus:

- No hack, they own the domain
- we can do nothing else then removing all mention of that domain everywhere

**Comment by Ducasse** [comment] 2023-09-30 07:45
Thanks for the report. I close it now and if you see the use of such domain from our resources can you point us to it?

**Closed as completed by Ducasse** 2023-09-30 07:45 UTC
Labels: Type: Bug
