### ISSUE TITLE
Text selection is too strict from the mouse location point of view

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13830] opened 2023-05-26 12:57 UTC
In P11 we got a regression.
In the past we could select complete text by double clicking below the text now the mouse should be on the line of the latest character.

![Capture 2023-05-26 at 14 54 04](https://github.com/pharo-project/pharo/assets/432549/8bc193a5-b0fc-4ba3-a040-3fbf9b63145f)

**Comment by Ducasse** [comment] 2023-05-26 12:58
In the past the mouse could be below the last line and double click would select everything. 
Now we have to move the mouse on the line 'package: cat'

**Comment by kevca87** [comment] 2023-05-29 16:02
We found the source of the behavior with @akevalion.
We discover that @guillep change the behavior in [Fix wrong double click when second click outside of original bounds](https://github.com/pharo-project/pharo/commit/7780946856ff1c48bcf0e9ec36eec9b9a33b4bd7)
In the current implementation the `MouseClickState` class handle things outside of its responsibility like the `clickClient containsPoint:`.
It could be solved by changing `containsPoint:` outside of `MouseClickState`
Let us know your thoughts.

**Comment by Ducasse** [comment] 2023-05-29 16:31
Thanks a lot for your time and investigation.
Can you send a PR?

**Comment by guillep** [comment] 2023-05-30 07:01
Hi @kevca87, thanks for looking into this!

Could you give more details? I just patched something (actually two times) after a regression, so if you have a better implementation that solves all 2/3 issues, that's great!

**Comment by akevalion** [comment] 2023-05-30 08:52
Hi, we found that the method `MouseClickState >> #handleEvent:from:` It is too complex, it should be splited into smaller methods. 
About if the MouseClickState should propagate or not click events when they are or not in target morph. I propose that behaviour should be in each client morph, not in MouseClickState.

**Comment by akevalion** [comment] 2023-10-19 13:02
Hi can we close this issue? I because it was merged here:
- https://github.com/pharo-project/pharo/pull/13906

**Closed as completed** 2023-10-19 13:19 UTC
Labels: Type: Bug
