### ISSUE TITLE
Lowercase d in bold font is overprinted

### ISSUE THREAD

**Issue by rillig** [guillep/pharo-core#2581] opened 2019-02-17 19:58 UTC
Pharo-7.0.1+build.148.sha.442fd72baccda88a9a3a72fe8158ebb31bf1b67a (64 Bit)

The word "padded:" is not displayed correctly in the lower part of the window. It's as if the "d" in that black font had the width 0.

![image](https://user-images.githubusercontent.com/3233724/52918380-8f5b9c00-32f6-11e9-9c99-abfdb3eba6e1.png)

**Comment by macta** [comment] 2019-02-18 01:10
You don't say what OS - as on OSX (HighSierra), it looks fine on my 13" macbook pro?

**Comment by akgrant43** [comment] 2019-02-18 09:05
I think this is a known issue: http://forum.world.st/Corrupted-fonts-in-P7-after-loading-Glamorous-Toolkit-td5094198.html
The email thread also has some suggestions for working around the issue.

**Comment by macta** [comment] 2019-02-18 12:06
@akgrant43 good point (as I reported that one) - it would be interesting to know if saving the image with a new name corrects @rillig 's problem (it did for the GT example you reference above - although in my case with that, it was just menu items that were corrupted).

**Comment by macta** [comment] 2019-02-18 12:27
Just to link these two on github - its #2336 that @akgrant43 refers to.

**Comment by rillig** [comment] 2019-02-18 12:40
Hmmm, today, after starting the VM again, all fonts display as they should.

**Comment by macta** [comment] 2019-02-18 12:57
Did that involve saving your image (I'm guessing yes?) - as that it is what fixed #2336 and I was told by @estebanlm that an image save does some form of cache reset (but wasn't clear if you had to save with a new name for this - doubtful though).

**Comment by rillig** [comment] 2019-02-18 16:30
@macta Yes, it did.

**Comment by ofi** [comment] 2019-02-26 18:49
Hi all,
on macOS 10.14.3 with P7.0.1 I had the same symptom today. Activating "Update fonts at startup" in the Settings Browsers Appearance>>Use Free Type... subtree, reopening the image and reselecting the font made it go away (for the time being).

**Comment by astares** [comment] 2019-02-26 19:52
It's a freetype bug that is known but hard to catch/fix. It is unrelated to GT - you can find it even in some standard images.

Often appears in new standard images already built on CI - happens sometimes, sometimes not. 
Happens on other letters too - sometimes they are printed on the same location. It was often reported already on Discord channel by different users.

Workaround for now is to switch the Appearance>>Use Free Type.

If I remember correctly it started to appear when the FT2 VM plugin (FreeType 2 plugin) was replaced with a direct UFFI solution calling the API's directly:
https://github.com/pharo-project/pharo/pull/1142/files

I guess it is somehow an initialization problem.

**Comment by macta** [comment] 2019-03-17 14:47
@astares when you say - switch the "use free type font" , is that turn it off, or on, or toggle it?

**Comment by astares** [comment] 2019-03-18 07:32
@macta: Usually I toggle it

**Comment by guillep** [comment] 2019-04-12 13:35
Hi, finally we have found the cause of this bug (see http://forum.world.st/FreeType-and-the-over-amorous-glyphs-overlapping-td5098109.html).

I'll mark this issue as duplicate of #2336

<blockquote><div><strong><a href="http://forum.world.st/FreeType-and-the-over-amorous-glyphs-overlapping-td5098109.html">Pharo Smalltalk Developers - FreeType and the over amorous glyphs (overlapping)</a></strong></div><div>FreeType and the over amorous glyphs (overlapping). Hello, After checking the problem with Guille, we have the hypothesis of the source of the problem. We have seen that accessing Free Type is not...</div></blockquote>

**Closed as completed by guillep** 2019-04-12 13:35 UTC
Labels: Status: Duplicate
