### ISSUE TITLE
Refactoring context menu in code editor is missing some items

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#16744] opened 2024-06-01 10:27 UTC
**Bug description**
Refactoring menu in Calypso is missing some items, namely `Rename`, `Extract temp`, `Inline method`, `Hierarchical senders/implementors`.

**To Reproduce**
1. Open Calypso on any method with a message send
2. Right click on message send, and open refactoring submenu
3. Notice how `Rename` is missing from there
4. Open implementors of that message, and repeat similar steps, you can find missing entries

**Screenshots**
Refactoring context menu in Calypso:
<img width="912" alt="Screenshot 2024-06-01 at 12 21 30" src="https://github.com/pharo-project/pharo/assets/34557616/05aa7529-c71e-4548-8f6a-57c5396c79fe">

Refactoring context menu in Implementors browser:
<img width="928" alt="Screenshot 2024-06-01 at 12 21 49" src="https://github.com/pharo-project/pharo/assets/34557616/e62904ae-10e9-4348-8a71-e0c94a646b66">

**Version information:**
 - OS: macOS
 - Pharo 13

**Comment by hernanmd** [comment] 2024-06-03 11:45
Could you detail where exactly you've clicked?
I couldn't reproduce it with right-click in the method pane (with and without selection):

<img width="970" alt="Screenshot 2024-06-03 at 13 42 06" src="https://github.com/pharo-project/pharo/assets/4825959/f5d0fc95-9930-4f3b-a78f-12995a20e88c">

**Comment by Ducasse** [comment] 2024-06-03 20:31
The problem is in the code pane: the code editor. Click on a message send.

**Comment by hernanmd** [comment] 2024-06-06 13:09
I'm closing this issue because we checked with Stef and couldn't reproduce the issue in P13 with the latest build.

**Closed as completed by hernanmd** 2024-06-06 13:09 UTC
Labels: Project: Calypso
