### ISSUE TITLE
Dropping a fileout raises an error

### ISSUE THREAD

**Issue by AlexisCnockaert** [guillep/pharo-core#17493] opened 2024-12-03 16:29 UTC
A possible solution is 

```
lookupServiceBasedHandler: aFileReference
	"the file was just droped, let's do our job"
	| services theOne |

	services := (FileServices itemsForFile: aFileReference fullName)
		reject: [:svc | self unwantedSelectors includes: svc selector].

	"no service, default behavior"
	services isEmpty
		ifTrue: [^nil].

	theOne := self chooseServiceFrom: services.
	^theOne
		ifNotNil: [ExternalDropHandler type: nil extension: nil action: [:stream | theOne performServiceFor: aFileReference]]
```

**Comment by guillep** [comment] 2024-12-20 09:30
Duplicate of #17480

**Closed as completed by guillep** 2024-12-20 09:30 UTC
Labels: Type: Bug
