### ISSUE TITLE
nil does not understand updateDamage:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5959] opened 2020-03-22 10:31 UTC
Guille 

I got an emergency debugger with updateDamage:.... but I could not reproduce it nor grab it. 
I will try to reproduce it. 

S.

**Comment by guillep** [comment] 2020-03-22 10:50
Yes, there are a couple of glitches. I'm personally amazed that there are not more :).
I'm planning on working on those issues on background during the week.

If there is some showstopper that cannot be worked around tell me, I'll put priority on that.

**Comment by Ducasse** [comment] 2020-03-22 16:05
It is a pity that I cannot log it. There were some problem with loading the wrong code of newdebugger.

**Comment by Ducasse** [comment] 2020-03-22 18:25
![Screenshot 2020-03-22 at 18 50 00](https://user-images.githubusercontent.com/432549/77257156-e1e25700-6c72-11ea-8b60-15305efc4bc1.png)

**Comment by Ducasse** [comment] 2020-03-22 18:25
![Screenshot 2020-03-22 at 18 49 27](https://user-images.githubusercontent.com/432549/77257162-ed358280-6c72-11ea-9ba3-0595cbff2cf8.png)

**Comment by guillep** [comment] 2020-03-23 14:42
It's super strange, because if you walk up the stack, that variable is being assigned just a bit before :(.
Maybe a race condition?

**Comment by guillep** [comment] 2020-03-24 08:08
@Ducasse: @pavel-krivanek has found a way to reproduce it apparently.
So this issue is now duplicated in https://github.com/pharo-project/pharo/issues/5976.
I'll close this one as the other has a reproduction case.
Let's continue the discussion there.

**Closed as completed by guillep** 2020-03-24 08:08 UTC
Labels: Type: Bug, Status: Duplicate, Project: Graphics
