### ISSUE TITLE
Fluid syntax breaks filein

### ISSUE THREAD

**Issue by kasperosterbye** [guillep/pharo-core#10975] opened 2022-03-08 15:21 UTC
**Bug description**
If I try to file-in a file where a class is defined using the fluid syntax, I get an error:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/17723745/157266899-03df5d1c-6f1e-45c0-bff5-c6c885621a0c.png">

I get the issue in either the filebrowser or drag and drop.

**To Reproduce**
1. Create a fresh image
2. Load file 'FileInFluid.st' attached below. This is its contents:
```smalltalk
Object << #FooBar
	slots: { #aaa };
	package: 'Foo-Bar'!
!FooBar methodsFor: 'somethingtobedone'!
aaa
	^aaa! !
```
The file 'FileInSubclass.st' attached below do not cause this issue:
```smalltalk
Object subclass: #FooBar
	instanceVariableNames: 'aaa'
	classVariableNames: ''
	package: 'Foo-Bar'!
!FooBar methodsFor: 'somethingtobedone'!
aaa
	^aaa! !
```

**Expected behavior**
I think they should both load. I ran across the error as I was using slots in a lot larger package, and filed it out to move it to an other project.

**Version information:**
 - MacOS 11.6
 - Pharo Version 10, build: 471, commit: 96da1f9, date: 8 March 2022

[FileInProblems.zip](https://github.com/pharo-project/pharo/files/8207371/FileInProblems.zip)

**Comment by MarcusDenker** [comment] 2022-03-08 15:25
This might be related too https://github.com/pharo-project/pharo/issues/8082

**Comment by MarcusDenker** [comment] 2022-03-09 10:02
I checked: this is a duplicate of #8082, I close it here and will add some thoughts to the other entry

**Closed as completed by MarcusDenker** 2022-03-09 10:02 UTC
Labels: Type: Bug

**Comment by kasperosterbye** [comment] 2022-03-09 10:04
Quite fine to close!
I added the issue as I searched for problems with fluid, and nothing came up.
