### ISSUE TITLE
Debugger gets corrupted in some cases

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2675] opened 2019-02-21 10:35 UTC
Sometimes when I use the debugger I get a bug and it becomes unusable.

Steps to reproduce:
- Debug in Pharo 7 the test TextPresenterTest>>#testSelectAll
- Click 9 times on "Over" to get at the end of the method
- Click on restart 
- Click on "Over"
- Kaboom

![image](https://user-images.githubusercontent.com/9519971/53162652-c4a10c00-35cc-11e9-9afa-08de05cd89e7.png)

```
Image
-----
/Users/cyrilferlicot/Documents/Pharo/images/Pharo 7.0 - 64bit (development version)-31/Pharo 7.0 - 64bit (development version)-31.image
Pharo7.0.1
Build information: Pharo-7.0.1+build.148.sha.442fd72baccda88a9a3a72fe8158ebb31bf1b67a (64 Bit)
Unnamed

Virtual Machine
---------------
/Users/cyrilferlicot/Documents/Pharo/vms/70-x64/Pharo.app/Contents/MacOS/Pharo
CoInterpreter VMMaker.oscog-eem.2496 uuid: 3e0d74b6-074c-4acf-95f3-fd75b2bc33e9 Dec 21 2018
StackToRegisterMappingCogit VMMaker.oscog-eem.2482 uuid: 7df020b4-6565-4768-9e4a-75bc5464ed95 Dec 21 2018
VM: 201812211409 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Fri Dec 21 09:09:01 2018 CommitHash: 1015842 Plugins: 201812211409 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

Mac OS X built on Dec 21 2018 18:10:05 UTC Compiler: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
VMMaker versionString VM: 201812211409 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Fri Dec 21 09:09:01 2018 CommitHash: 1015842 Plugins: 201812211409 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
CoInterpreter VMMaker.oscog-eem.2496 uuid: 3e0d74b6-074c-4acf-95f3-fd75b2bc33e9 Dec 21 2018
StackToRegisterMappingCogit VMMaker.oscog-eem.2482 uuid: 7df020b4-6565-4768-9e4a-75bc5464ed95 Dec 21 2018
```

**Comment by estebanlm** [comment] 2019-02-21 10:42
yes, it looks green sometimes! (sorry, I couldn't resist it ;) )

**Comment by astares** [comment] 2019-02-21 16:41
Then the color should be fixed too ;)

**Comment by astares** [comment] 2019-08-20 19:15
@jecisc Still valid?

**Comment by guillep** [comment] 2020-03-30 15:11
I cannot reproduce it in latest Pharo 9. Please reopen with new instructions if valid somewhere else.

**Closed as completed by guillep** 2020-03-30 15:11 UTC
