### ISSUE TITLE
AClass compiler evaluate should set AClass as a receiver

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#2519] opened 2019-02-13 13:56 UTC
Following code return nil:
```Smalltalk
Object compiler evaluate: 'self' 
```
I would expect that #compiler should return a compiler instance prepared in class environment. So following compilation should see receiver as self and its class side variables (evaluate: 'classSideVar' returns nil due to undeclared)

**Comment by MarcusDenker** [comment] 2019-02-13 14:06
true. 
The reason is that #evaluate supports to put an explicit receiver and uses that class, which is nil.

I will check...

**Comment by MarcusDenker** [comment] 2019-06-06 12:47
the problem is that the compiler has no clue what the receiver should be: thus it is nil... if the receiver is nil, it feels wrong to compile it with another class as the class...

We could implement #evaluate: on Object:


evaluate: aString
	^self class compiler
		receiver: self; 
		evaluate: aString


and then things like that work:

SmallInteger evaluate: 'minVal'

**Comment by Ducasse** [comment] 2019-06-10 08:36
Denis I do not get it. 

Why 

``` 
Object compiler evaluate: 'self' 
``` 
should return a compiler. Seriously why self would have to be bound to the compiler?
I do not get it and to me this is a good suggestion.

**Comment by dionisiydk** [comment] 2019-06-10 09:48
I agree. It is not valid issue.
Just at one morning my intuition told me that it should work how I described. But it is wrong. 

Not sure about #evaluate: for Object. 
At least #evaluateDoIt: would be better I think. And maybe also #compilerForDoIt to work as I described ( if it is good idea to have)

**Comment by MarcusDenker** [comment] 2019-11-04 13:47
I close this for now... as there is no action to be done

**Closed as completed by MarcusDenker** 2019-11-04 13:47 UTC
