### ISSUE TITLE
Release test for proper tag casing

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2515] opened 2019-02-13 11:39 UTC
In latest image Pharo 8.0.0
Build information: Pharo-8.0.0+build.68.sha.6e1a95fc669ee154eb5ab36d6cd5291ec3bc656f (64 Bit)

we have some packages with class tags that are lowercase while class tags are usually 
starting uppercase.

I fixed the three issues in:
 - https://github.com/pharo-project/pharo/pull/2514
 - https://github.com/pharo-project/pharo/pull/2512
 - https://github.com/pharo-project/pharo/pull/2510

Once they are integrated we should add a release test to enforce that class tags are uppercase
to provide further consistency to the base image.

```Smalltalk
testProperClassTagCasing
|violations|
violations := OrderedCollection new.
Smalltalk packages
	do: [:each | each classTags do: [:ct | ct name first isLowercase ifTrue: [ violations add: (each -> ct) ] ] ].
self assert:  violations isEmpty description: 'Class Tags should be uppercase'
``

**Comment by Ducasse** [comment] 2019-02-14 12:37
We could also make sure that when a tag is defined it is not using a lowercase. This way we cure the cause and not the consequence. and also less work after.

**Comment by astares** [comment] 2019-02-14 13:24
Yes - Calypso wrongly allows lowercase class tags currently - but this is not part of this issue. (to fix Calypso there is: https://github.com/pharo-ide/Calypso/issues/441). 

Calypso is the default place to create a tag - but not the only way to edit/manipulate tags. Even packages with possibly wrong tags can get introduced on other ways (changes in build or package assembly process, next new browser, or other).

So the release test is independently necessary to ensure the level of quality for the base image.
Both issues need to be addressed.

**Comment by dionisiydk** [comment] 2019-02-16 12:22
I am not sure that Calypso command is a right place for this.
Should not it be in lower level? (RPackage methods)

**Comment by Ducasse** [comment] 2019-02-18 12:49
Denis we could start with calypso :)

```
SycAddNewClassTag >> tagName: anObject
	tagName := anObject uppercase
```

**Comment by Ducasse** [comment] 2019-02-18 12:52
else we just need to do it here. 

addClassTag: aSymbol
	"Add the class tag from the receiver, if already added do nothing."
	| tagName newTag |

	"strip package name if needed"
	tagName := (self toTagName: aSymbol) uppercase. "now I'm not sure about the impact"

	
	^ self 
		classTagNamed: tagName
		ifAbsent: [ 
			self class organizer 
				validateCanBeAddedPackage: self
				tagName: tagName.
			newTag := self basicAddClassTag: tagName.
			SystemAnnouncer uniqueInstance classTagAdded: tagName inPackage: self.
			^newTag]

**Comment by astares** [comment] 2019-08-17 14:02
Still valid

**Comment by astares** [comment] 2019-08-17 14:03
Tags are fixed - but we should implement the #testProperClassTagCasing as a release test

**Comment by guillep** [comment] 2020-03-27 10:48
So to summarize, to close this issue, this test should be added?

```smalltalk
ReleaseTest >> testProperClassTagCasing
    |violations|
    violations := OrderedCollection new.
    Smalltalk packages
        do: [:each | each classTags do: [:ct | ct name first isLowercase ifTrue: [ violations add: (each -> ct) ] ] ].
    self assert:  violations isEmpty description: 'Class Tags should be uppercase'
```

**Comment by astares** [comment] 2020-03-27 10:54
@guillep Yes, please

**Comment by Ducasse** [comment] 2020-03-27 10:57
Guille I think that 

```
SycAddNewClassTag >> tagName: anObject
	tagName := anObject uppercase
```
is also a good way to avoid to generate stupid issues in the future

**Comment by astares** [comment] 2020-03-27 11:24
@Ducasse Yes - we should avoid it. But I opened a separate issue for that: https://github.com/pharo-project/pharo/issues/6019

The release test is nonetheless necessary for loaded or manually changed packages.

**Closed as completed** 2020-03-27 16:31 UTC
Labels: Type: Enhancement, Easy
