### ISSUE TITLE
DNU in VMWorldRenderer>>#updateDamage: 

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#5976] opened 2020-03-24 08:02 UTC
**To Reproduce**
1. Open Calypso, go to Text-Core package
2. browse dependencies
3. open left tree

![Pharo_4tbhRU2OWA](https://user-images.githubusercontent.com/572494/77401952-1e669d80-6dae-11ea-8076-6ff494c36551.png)

alternativelly, it opens emergency evaluator

**Comment by guillep** [comment] 2020-03-24 08:07
This is a duplicate of https://github.com/pharo-project/pharo/issues/5959.
I'll keep this one as it has a way of reproducing it.

**Comment by guillep** [comment] 2020-03-24 08:13
I think it may be a race condition of two interleaved / nested "diplayWorld".
I'll try to check it today, but I've my day full of meetings...

**Comment by guillep** [comment] 2020-03-24 09:31
Turns out I was right on the nested display ^^.

I put a breakpoint in `#deferUpdatesDuring:`, to break if it is entering a second time and `deferredUpdateMode` is not nil. This would indicate we were in the middle of a render, and somebody else tried to do a render also.

```smalltalk
deferUpdatesDuring: aBlock

	deferredUpdateMode ifNotNil: [ self haltOnce ].
```
Then I got a debugger with the following stack.

```
VMWorldRenderer(Object)>>haltOnce
VMWorldRenderer>>deferUpdatesDuring:
VMWorldRenderer(AbstractWorldRenderer)>>displayWorldState:ofWorld:
WorldState>>displayWorld:
WorldMorph>>displayWorld
[aWorld displayWorld] in WorldState>>displayWorldSafely: in Block: [aWorld displayWorld]
BlockClosure>>on:do:
BlockClosure>>ifError:
WorldState>>displayWorldSafely:
WorldState>>doOneCycleNowFor:
WorldMorph>>doOneCycleNow
SystemProgressMorph>>refresh
SystemProgressMorph>>update:
MorphChanged>>deliverTo:
SystemProgressMorph(Morph)>>handleUpdate:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[action cull: anAnnouncement cull: announcer] in AnnouncementSubscription>>deliver: in Block: [action cull: anAnnouncement cull: announcer]
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt: in Block: [ subscription deliver: anAnnouncement ]
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:
SubscriptionRegistry>>deliver:
Announcer>>announce:
JobProgressMorph(Morph)>>doAnnounce:
JobProgressMorph(Morph)>>changed:
```

What happens is that we are "invoking a render within a render". So the nested one exits and cleans up some variables, breaking the outer render.

I'll try to fix it today.

**Comment by guillep** [comment] 2020-03-24 09:31
Probably related to #5977

**Comment by guillep** [comment] 2020-03-24 09:32
Probably an interesting case for @StevenCostiou and @dupriezt too

**Closed as completed** 2020-03-24 11:17 UTC
Labels: Type: Bug, Project: Graphics
