### ISSUE TITLE
Sockets disconnect unexpectedly on Windows

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#10980] opened 2022-03-09 15:50 UTC
**Bug description**

We're seeing failures with Sockets on Windows 10.  There are multiple failure modes:

- The socket may be closed unexpectedly.
- The OS process may exit without any error being logged.
- The process may hang.  In this case there may be data available to read, however it appears that the `readSemaphore` in the socket hasn't been signalled.

These happen with all processes on the same machine connecting through localhost, so I don't believe that network failures are involved.

**To Reproduce**

I'll attach a fileOut which contains code to reproduce the issue.  The instructions are also in the class comments of `SocketLoadClient` and `SocketLoadServer`.

To reproduce the issue:

Create a file called `socketloadserver.st` with the following contents:

```
| readMonitor |

"Start the socket read semaphore workaround and the runner."
readMonitor := GtWindowsSocketReadMonitor new
        setLogOnly;
        start.

TranscriptLogger start.
SocketLoadServer new
        localPort: 7000;
        start.
Semaphore new wait.
```

Then start the server from a PowerShell with:

```PowerShell
pharo-vm\PharoConsole.exe --headless .\Pharo.image st .\socketloadserver.st
```

`SocketLoadClient` connects to a `SocketLoadServer` and sends buffers of random length, requesting a random length buffer back from the server.   The maximum buffer length is 20k characters (`String>>loremIpsum:`).    The socket buffer size is 4096.

The number of requests is controlled by `loopCount` in `SocketLoadClient`.

To start a client, create a file called `socketloadclient.st` with the following contents:

```
| readMonitor client signals |

"Start the socket read semaphore workaround and the runner."
readMonitor := GtWindowsSocketReadMonitor new
        setLogOnly;
        start.

TranscriptLogger start.

SocketLoadClient new
        remoteAddress: '7000';
        loopCount: 10000;
        startAndWait.
```

Then start the client from a PowerShell with:

```bash
pharo-vm\PharoConsole.exe --headless .\Pharo.image st .\socketloadclient.st --quit
```

Starting 4 clients simultaneously is normally enough to trigger the failure prior to 10,000 packets being sent.

`GtWindowsSocketReadMonitor` starts a process that periodically iterates over all the sockets and checks to see if data is available.  If it is twice in a row a message is logged flagging that the socket may be stuck (the third failure mode listed above).

**Expected behavior**

All clients complete sending and receiving random length packets without error.

**Version information:**
 - OS: Windows 10
 - Version: 10
 - Pharo Version: 
 Pharo 10.0.0
Build information: Pharo-10.0.0+build.473.sha.a073a65d1153db338c3be8764da632e2ce71d901 (64 Bit)

.\100-x64\PharoConsole.exe --version
Pharo 9.0.12 built on Feb 21 2022 08:48:35 Compiler: 4.2.1 Compatible Clang 8.0.1 (tags/RELEASE_801/final)
Built from: v9.0.12 - Commit: 87515653 - Date: 2022-02-21 14:42:01 +0100

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

Not sure what the development cost will be - happy to help. :-)

**Additional context**

This is Windows specific, the same tests run fine on Mac and Linux.

**Comment by akgrant43** [comment] 2022-03-09 15:55
[Issue10980.st.txt](https://github.com/pharo-project/pharo/files/8216147/Issue10980.st.txt)

**Comment by Ducasse** [comment] 2022-03-09 19:47
Thanks for that report!
We are chasing socket problems.
@tesonep

**Comment by tesonep** [comment] 2022-03-16 08:57
It has been fixed in the new release of the VM (https://github.com/pharo-project/opensmalltalk-vm/releases/tag/v9.0.13)
Accessible through the usual channels. 
Cheers.

<blockquote><img src="https://opengraph.githubassets.com/2690610f9e79298d50d223a253e1d5b8bb9e7a19ab17925dddf2f17a92a94af7/pharo-project/opensmalltalk-vm/releases/tag/v9.0.13" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/pharo-project/opensmalltalk-vm/releases/tag/v9.0.13">Release Version 9.0.13 · pharo-project/opensmalltalk-vm</a></strong></div><div>v9.0.13

Correct handling OOB (Out of Band Data) in Window
Blocking signals while signaling semaphores to avoid deadlocks caused by signal handlers

v9.0.12

Make MAXHOSTNAMELEN at least 256: impro...</div></blockquote>

**Closed as completed by tesonep** 2022-03-16 08:57 UTC
Labels: Type: Bug

**Comment by akgrant43** [comment] 2022-03-16 09:54
Thanks, @tesonep!

I'm just running some tests now, and so far no problems.
