### ISSUE TITLE
Adding breakpoint (in margin) saves a dirty editor without asking, and doesn't show the breakpoint.

### ISSUE THREAD

**Issue by fuhrmanator** [guillep/pharo-core#2793] opened 2019-03-11 16:40 UTC
I'm using Pharo 7.0.2 on Windows with a 32-bit image from Moose CI.

If I'm editing a method and I click the margin to insert a breakpoint, it seems the editor is saved, and I also don't see the breakpoint. 

Steps to reproduce:

1. Edit a method (making it dirty in the editor). Confirm the upper right corner of the editor is orange.
2. Insert a break point by clicking the left margin next to an instruction.
   1. Confirm that no breakpoint is visible in the margin (even though I think it was actually added and saved). 
   2. Confirm that the editor complains it has been saved elsewhere; its upper right corner is red.
3. If you try to save, you get a (scary) warning that your editor "may have been changed elsewhere."
4. If you cancel (Ctrl-L) you see the breakpoint is in the margin. 

Suggested solution: I would be happy as a developer if the system would not allow me to insert breakpoints in unsaved (dirty) methods (e.g., I would see a warning dialog saying I must save my method first).

**Comment by MarcusDenker** [comment] 2019-03-15 08:52
see https://pharo.fogbugz.com/f/cases/20343/Debugger-doesn-t-show-breakpoints-in-the-gutter-or-have-a-way-to-clear-them, too

**Comment by jecisc** [comment] 2019-09-11 09:59
Keep

**Comment by MarcusDenker** [comment] 2021-02-23 13:01
duplicate of https://github.com/pharo-project/pharo/issues/5211

**Closed as completed by MarcusDenker** 2021-02-23 13:01 UTC
Labels: Type: Bug, Project: Debugger
