### ISSUE TITLE
Cmd , is a bad idea

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11378] opened 2022-06-15 18:24 UTC
Hi

When you mistype cmd . and press cmd , you get that you killed all the processes.
This is the worse API I could see. 

We should remove this feature!!!

**Comment by Ducasse** [comment] 2022-06-15 18:25
So you get a system that you could stop and you killed it.
Superb feature!

**Comment by MarcusDenker** [comment] 2022-06-21 15:39
duplicate of https://github.com/pharo-project/pharo/issues/11396

**Closed as completed by MarcusDenker** 2022-06-21 15:39 UTC
Labels: Type: Bug, Priority: Critical
