### ISSUE TITLE
Pharo-7 Saving the settings breaks local directory

### ISSUE THREAD

**Issue by macta** [guillep/pharo-core#2854] opened 2019-03-17 00:21 UTC
I don't think this problem is expressed clearly enough in #2646 - simply saving the settings file in an image will cause all future images to use/share the iceberg-local directory for the image who's settings were saved. 

This causes terrible and confusing issues when using iceberg, as you don't actually get a clean copy of your repo, and loading things like master - can leave you many pull requests behind when you load a baseline (and hence, you will inadvertently have the wrong code).

**Comment by noha** [comment] 2019-03-17 08:00
So you think it needs more than one ticket for the same issue? You generating noise which unnecessary IMHo

**Comment by noha** [comment] 2019-03-17 08:01
And if it is important to clarify the error more you can just comment on the other issue

**Comment by macta** [comment] 2019-03-17 09:13
@noha - normally I would - but I felt this issue is so severe (and several people have lost lots of time on it) that I felt this warranted its own entry. #2646 seems more like a nice to have, as maybe I don't want to save extra setting unnecessarily. This issue is meant to highlight a big bug - save your settings (easily done - just open the code formatter sub settings, and think you are saving those) and then you may not be loading the code you think you are when in other projects/image - so your testing might be invalidated.

But sure @jecisc - do you want to merge them, are they the same thing?

**Comment by fuhrmanator** [comment] 2019-04-06 21:59
See https://github.com/pharo-vcs/iceberg/issues/1226

**Comment by fuhrmanator** [comment] 2019-04-06 22:31
I needed to "store settings" because I use 2FA on GitHub and the only sane way to use Iceberg in that case is with SSH keys (the token is too long to type as a password that can't be memorized for all images). Therefore I wanted to have all (future) images to have the "use SSH keys" settings. But, storing the path of the local git repo to the same directory is a big problem. There doesn't seem to be a workaround to this, apart from storing settings with my own scripts I load on startup. This bug made me lose a lot of time and put my whole understanding of git into question ;-)

**Comment by guillep** [comment] 2019-04-12 15:38
This is not necessarily an Iceberg bug but a Pharo bug.
Iceberg calculates the directory where it will clone using Pharo's local directory.
The same will happen with Monticello's package-cache, the gt playground cache, and ombu's session directory. They are all stored in the local directory.

```smalltalk
FileLocator localDirectory resolve
```

The problem is that going to settings, and clicking on "Store settings" will store the local directory of the current image and make it the local directory of all other images loading settings at startup.

To reproduce:
 - create an image A with Pharo Launcher
 - Go to settings and click on Store Settings
 - close image A and create a new image B
 - then `FileLocator localDirectory resolve` will wrongly resolve to image A's path.

To workaround this, people can launch images without settings, for example, using the launcher's second option:

![](https://cdn.discordapp.com/attachments/345132530585829377/565807653423415296/unknown.png)

**Comment by jvalteren** [comment] 2019-06-10 10:47
A came across this issue as well and I agree with @macta that this is a severe issue. I created an issue in the pharo-launcher project initially, because I thought that was where the problem was. Have a look at: https://github.com/pharo-project/pharo-launcher/issues/340. As you can see in my comments there, I discovered that it indeed had to do with saving Pharo settings.

@guillep Yes, you can work around this issue in this way. However, I can tell you from experience that the 'Launch without setting' option is very non-intuitive. The name 'Launch without setting' is not understood by novice users or users that have no knowledge or experience with the way Pharo uses and saves its settings.

IMO the aggravating fact here is that it can potentially result in the destruction of data, like forgetting an Iceberg repository can result in the deletion of a local working copy.

Also, I find the method name localDirectory misleading, because depending on the settings, there might be nothing local about it.

I'm happy to discuss options to resolve this and put in the work for a pull request.

**Comment by Bajger** [comment] 2019-12-19 08:59
Hi guys, I've faced same issue in my P7 image and looked why there is the issue with resolving Local directory. I found following:
- when there are no settings stored before (fresh image), localDirectory setting is initialized with directory, where image is located (see: SystemResolver class>>userLocalDirectory). Stored variable is instance of FileReference.
- when you change setting of local directory setting in Settings browser by choosing directory from dialog, it writes to same variable string that is passed by dialog. And this causes a problems, since SystemResolver expects instance of FileReference and not string.

So in short: SystemResolver>>userLocalDirectory expects instanse of file reference. Instead of this, dialog (in method  PragmaSetting>>chooseFileDirectory) sends instance of string and that causes a problem.

I've fixed this by changing following method and added conversion (by sending `asFileReference`) and it works. 
```
PragmaSetting>>chooseFileDirectory
	| result |
	result := self theme chooseDirectoryIn: World title: 'Choose a file' path: nil.
	result ifNotNil: [ self realValue: result fullName asFileReference ].
```
Question is, if setting itself shouldn't store string path instead of FileReference instance (I'm not sure). You can see in Setting browser print string of FileReference instance (e.g. 'File @ C:\P7') now, after choosing some directory from dialog window. In any case, `#chooseFileDirectory` fix brings consistency for SystemResolver variable, so resolving of directory will work (by applying fix). I wasn't able to find other places in system, where string would be expected instead of file reference instance (No senders of inputWidgetForDirectory, but method seems to be pretty generic). 
Should I raise PR with that fix? Other option would be to change setter to have implicit conversion like:
``` 
SystemResolver>>userLocalDirectory: aFileReference
	UserLocalDirectory := aFileReference asFileReference
```

**Comment by Ducasse** [comment] 2019-12-21 13:05
Do you know if your issue is solved in P8?

**Comment by Bajger** [comment] 2019-12-22 07:56
Issue is still relevant it seems. I've reproduced on latest image. 
Pharo 8.0.0
Build information: Pharo-8.0.0+build.1089.sha.066c290a0c204d91dbfcff16c9c7f61e5c7a10f2 (64 Bit)

![image](https://user-images.githubusercontent.com/45875448/71319026-daa38580-2498-11ea-9368-4e885635caed.png)

**Comment by Ducasse** [comment] 2019-12-22 08:58
Thanks!

**Closed as completed** 2020-01-10 09:33 UTC

**Comment by Ducasse** [comment] 2020-01-11 16:08
Thanks Pablo is this is cool to have you on board.
