### ISSUE TITLE
Browse and refs for sharedPools based fluid class definition

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7216] opened 2020-08-30 15:19 UTC
We should support shared pools navigation from the class definition
For example browsing sharedPools: of 

```
ArrayedCollection << #Text
	slots: { #string . #runs };
	sharedPools: { TextConstants };
	tag: 'Base';
	package: 'Text-Core'
```

**Comment by MarcusDenker** [comment] 2022-06-13 08:39
Duplicate of https://github.com/pharo-project/pharo/issues/11348

**Closed as completed by MarcusDenker** 2022-06-13 08:39 UTC
Labels: Type: Enhancement, Easy, sprint
