### ISSUE TITLE
Model unsubscribe support

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#11410] opened 2022-06-26 08:33 UTC
**Problem description**
Class `Model` uses `Announcer` and has getter `announcer` and `whenChangedDo:`.
What I am missing is support for `unsubscribe: aSubscriber`. If I directly use `aModel announcer unsubscribe: aSubscriber`, it does not work, because the original block (that has info about the receiver) is replaced by different one in `Model>>#whenChangedDo:`, so the model acts as the subscriber even if the real original subscriber is different.

Note that I actually noticed this issue when using NewValueHolder, not the generic Model.

**Possible test**
```
testUnsubscribe

| hasBeenAnnounced |
hasBeenAnnounced := false.
aModel whenChangedDo: [ hasBeenAnnounced := true ].
aModel unsubscribe: self.
aModel valueChanged.
self deny: hasBeenAnnounced.
```

**Version**
All recent versions of Pharo (8-11), all OS

**Comment by kasperosterbye** [comment] 2022-11-13 11:07
Hmm, this is maybe not a bug, but just surprising behaviour :-)

The subscriber of `aModel whenChangedDo: [ hasBeenAnnounced := true ]` is not `self` but actually the model itself.
One might argue that `Model>>#whenChangedDo:` should return the announcement produced so you can keep it around to remove that specific announcement, but alas, it does not.

**Comment by kasperosterbye** [comment] 2022-11-13 14:08
I suggest this issue to be closed as there cannot be a self binding as Jan suggest.

**Closed as completed** 2022-11-17 12:13 UTC
Labels: Type: Enhancement
