### ISSUE TITLE
Browse this version is broken

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15931] opened 2024-01-07 13:29 UTC
The external browser uses it.
Did not have the time to check more.

**Comment by hernanmd** [comment] 2024-01-08 11:31
I could not reproduce a bug with protocolNames but I've found multiple issues using the  "Browse this version in Calypso":

<img width="517" alt="Screenshot 2024-01-08 at 12 30 51" src="https://github.com/pharo-project/pharo/assets/4825959/782e3276-092f-4ab2-a22e-1aa448bb9230">

Trying to browse unloaded packages:

<img width="1186" alt="Screenshot 2024-01-08 at 12 28 37" src="https://github.com/pharo-project/pharo/assets/4825959/cfa47973-faa6-46b8-9f2e-2724a10dc226">

Trying to browse loaded packages:

<img width="955" alt="Screenshot 2024-01-08 at 12 29 10" src="https://github.com/pharo-project/pharo/assets/4825959/e4d169b2-5ca8-44a9-b6a3-8bc9c21fced0">

**Comment by hernanmd** [comment] 2024-02-14 19:31
Fixed in #16009

**Closed as completed by hernanmd** 2024-02-14 19:31 UTC
Labels: Project: Calypso
