### ISSUE TITLE
"MorphicDraw open." will not execute due #rectangleIcon being deprecated

### ISSUE THREAD

**Issue by nikosk84** [guillep/pharo-core#7330] opened 2020-09-18 06:24 UTC
**Describe the bug**
Having followed the installation process of MorphicDraw [here](https://github.com/StephanEggermont/MorphicDraw), when we attempt to execute MorphicDraw open from the playground we get the message:

"The method Base64MimeConverter class>>#mimeDecodeToBytes: called from MDIcons>>#rectangleIcon has been deprecated. Please use #base64Decoded now. See issue #21937"

Issue #21937 is also nowhere to be found.

**To Reproduce**
1. Open a playground
2. DoIt on MorphicDraw open.
3. See error

**Expected behavior**
We expect a MorphicDraw window to open.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/22572652/93563468-9cd47e80-f990-11ea-8211-f37468c82905.PNG)

**Version information:**
 - OS: [e.g. Windows 10 Pro]
- Pharo Version 8.0 64 bit

**Comment by Ducasse** [comment] 2020-09-18 06:38
Hi nikos 

this is not a bug of Pharo. This is the code of stephan that should be migrated to Pharo 80.

S.

**Comment by Ducasse** [comment] 2020-09-18 06:40
I passed the issue to stephan and I will close it here.

**Comment by Ducasse** [comment] 2020-09-18 06:40
Btw you can press continue.

**Comment by nikosk84** [comment] 2020-09-18 06:41
> 
> 
> I passed the issue to stephan and I will close it here.

Oh, I apologize for the inconvenience. Thank you. I pressed continue once and it reproduced the same message but when I click continue a second time, the window appears. Thanks again.

**Closed as completed** 2020-09-18 06:41 UTC
Labels: Type: Bug

**Comment by Ducasse** [comment] 2020-09-18 06:52
There is no problem :)
Better submit in the wrong place that nowhere. 
There is a setting to control the deprecation. YOu can disable it or you can ask it (if it is a rewrtiting deprecation) to automatically rewrite the code.

**Comment by nikosk84** [comment] 2020-09-18 06:59
> 
> 
> There is no problem :)
> Better submit in the wrong place that nowhere.
> There is a setting to control the deprecation. YOu can disable it or you can ask it (if it is a rewrtiting deprecation) to automatically rewrite the code.

OK. I'm not sure how to disable it but I'll leave it. I think it's better for me to have the system yell at me so I become aware.
Thanks for the heads up.

**Comment by StephanEggermont** [comment] 2020-09-18 07:33
Thanks for the report. Indeed, I need to migrate the code. If you want to play with it now, PharoLauncher allows you to install an older version of Pharo where the code works well. I will not be able to migrate the code this week

**Comment by StephanEggermont** [comment] 2020-09-18 07:36
https://github.com/StephanEggermont/MorphicDraw/issues/5

**Comment by nikosk84** [comment] 2020-09-18 07:39
> 
> 
> Thanks for the report. Indeed, I need to migrate the code. If you want to play with it now, PharoLauncher allows you to install an older version of Pharo where the code works well. I will not be able to migrate the code this week

No problem, Stephan. It's my pleasure and I've saved this website so if I do come across anything I can report it and help where I can. I'll stick with the 8.0 version because I'm following the MOOC. There's no rush on my side to use MorphicDraw. Thanks for the information though.
