### ISSUE TITLE
[Tools][Rubric]Cannot open the Profiler....

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2964] opened 2019-03-21 18:32 UTC
I just missed a button and clicked unfortunately on the profiler menu item. And guess what: I received an exception (that I cannot fuel out because it not working too: See #2963).
![ur5Yh7UPhu](https://user-images.githubusercontent.com/4706329/54776280-0e066a80-4c10-11e9-9114-9eee66d3dd54.gif)

**Comment by StephanEggermont** [comment] 2019-03-22 14:11
Seems connected to #2980. There is probably no test for the missing styler though

**Comment by StephanEggermont** [comment] 2019-03-26 10:22
Caused by #2789

**Comment by plantec** [comment] 2019-04-14 18:28
I've dug a little bit. How a styles is plugged is different from how it is implemented in PluggableTextMorph. Rubric uses EditingMode and to edit smalltalk from a Rubric morph one to send #beForSmalltalkCode to it. 
ok, it works but after a new problem arise with the #interactionModel that was introduced when we wanted to improve Nautilus.
The question is: does #interactionModel still make sense  in Pharo 8 ?

**Comment by StephanEggermont** [comment] 2019-04-15 14:28
Are there other users that need it? Would it be difficult to modify Spec?

**Comment by MarcusDenker** [comment] 2019-06-06 06:42
this is now fixed: one can open it

**Closed as completed by MarcusDenker** 2019-06-06 06:42 UTC
