### ISSUE TITLE
Finder does not find copyFrom: to: 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14650] opened 2023-09-13 09:05 UTC
```
#($a $b $c $d) . 2 . 3 . #($b . $c)
```

while 

```
#($a $b $c $d) copyFrom: 2 to: 3
> #($b $c)
```

**Comment by hernanmd** [comment] 2023-09-14 22:30
> ```
> #($a $b $c $d) . 2 . 3 . #($b . $c)
> ```
> 
> while
> 
> ```
> #($a $b $c $d) copyFrom: 2 to: 3
> > #($b $c)
> ```

It is because takes the $. as an element of the expected result, since there is a #() instead of braces {}.

Using

```smalltalk
#($a $b $c $d) . 2 . 3 . #($b $c)
```

or

```smalltalk
#($a $b $c $d) . 2 . 3 . {$b . $c}
```

Finds the copyFrom:to:

```smalltalk
MethodFinder new 
	findMethodsByExampleInput: { 
		RBLiteralArrayNode value: #( $a $b $c $d ) .
		RBLiteralValueNode value: 2 .
		RBLiteralValueNode value: 3 
	 }
	andExpectedResult: (RBLiteralArrayNode value: #( $b $c ))
 "an OrderedCollection(#($a $b $c $d) copyFrom: 2 to: 3)"
```

**Comment by jecisc** [comment] 2023-09-15 06:22
Nice catch Hernan. Since this is not a bug in the end I’ll close the issue

**Closed as not planned by jecisc** 2023-09-15 06:22 UTC
Labels: Type: Bug
