### ISSUE TITLE
Error when doing an Screenshot >>  "Instance of True did not understand #vanishDelay"

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#6103] opened 2020-04-01 20:13 UTC
**Describe the bug**
When doing an screenshot an error "Instance of True did not understand #vanishDelay" is raised.

**To Reproduce**
1. Go to System Menu 
2. Select Screenshot option
4. A window with the error is raised

**Expected behavior**
Don't raise the error window

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7849541/78182164-f0e0ba80-7465-11ea-9ea5-23dadea8bbc3.png)

**Version information (please complete the following information, you can get it from Help->about):**
 - OS: Windows 10
 - Version: Pharo 9.0
 - Commit info: Pharo-9.0.0+build.202.sha.2799b9114f70ce3931612334575cd42509315882 (64 Bit)

**Comment by Ducasse** [comment] 2020-04-18 12:25
Thanks!

**Comment by Ducasse** [comment] 2020-04-18 12:27
I could not reproduce the error. I tried both world and specific area.

**Comment by Ducasse** [comment] 2020-04-18 12:32
Now I'm trying with latest pharo90 version.
Pharo 9.0.0
Build information: Pharo-9.0.0+build.245.sha.7879085069137a15da1d2c5dce284589963f3032 (64 Bit)
And I could not reproduce it. 

So I will close the issue. Now if you succeed to reproduce it with the latest version please let us know.

**Closed as completed by Ducasse** 2020-04-18 12:32 UTC

**Comment by David5i6** [comment] 2020-04-19 11:09
In newer version seem fixed
