### ISSUE TITLE
Rotation Halo is broken

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4458] opened 2019-08-31 20:09 UTC
When I pass the mouse on the rotation halo I get degrees sent to nil. 
Because angleOffset is nil

**Comment by Ducasse** [comment] 2019-08-31 20:26
Apparently 
    angleOffset is only accessed in

dotRot:with:
and 
startRot:with:

And it seems that startRot: is not executed. It looks normal since startRot:with: is not executed when we pass the mouse without a mouseDown.
The bug appears when we pass the mouse on the halo.


The following code show how to the halo is created.

addRotateHandle: haloSpec
	(self addHandle: haloSpec on: #mouseDown send: #startRot:with: to: self)
		on: #mouseMove send: #doRot:with: to: self

**Comment by Ducasse** [comment] 2019-08-31 20:28
The rotation is working in for example Pharo 50 and 70.
There, the methods startRot:with: and doRot:with: are the same than in Pharo80.

**Comment by Ducasse** [comment] 2019-08-31 20:29
The code of 

addRotateHandle: haloSpec
	(self addHandle: haloSpec on: #mouseDown send: #startRot:with: to: self)
		on: #mouseMove send: #doRot:with: to: self

looks the same in both.

**Comment by Ducasse** [comment] 2019-08-31 20:31
The behavior worked in P70.

**Comment by Ducasse** [comment] 2019-08-31 20:32
addSimpleHandlesTo: aHaloMorph box: aBox seems to be the same in both system

**Comment by Ducasse** [comment] 2019-08-31 20:48
The differences I found are that: 
on P70 doRot:with: is not invoked on mouseOver while it is on P80.

**Comment by dupriezt** [comment] 2019-08-31 21:29
What is the rotation halo?

**Comment by Ducasse** [comment] 2019-09-01 08:21
Did you read the first entry:
"When I pass the mouse on the rotation halo I get degrees sent to nil.
Because angleOffset is nil"

**Comment by Ducasse** [comment] 2019-09-01 08:22
And you see this is again a scenario with one execution working and one failing.

**Comment by dupriezt** [comment] 2019-09-01 09:18
> 
> 
> Did you read the first entry:
> "When I pass the mouse on the rotation halo I get degrees sent to nil.
> Because angleOffset is nil"

I read it, and it didn't say what "the rotation halo" is, so I don't know where to place my mouse to reproduce the bug.

**Comment by Ducasse** [comment] 2019-09-01 13:08
ahhhh

Halo are positionable menu for direct manipulation of graphical objects.
Halo = HaloMorph 
The code is a bit old. 
To get the halos: 
for example, you click on an icon for example while pressing Option-Command+shift

![Screenshot 2019-09-01 at 15 07 28](https://user-images.githubusercontent.com/432549/64076836-3bc90280-ccca-11e9-97c5-7dd67ecc8558.png)

**Comment by dupriezt** [comment] 2019-09-02 09:55
I wrote a test for this bug on the MorphTest class. It creates a morph, simulates a shift-alt-click to spawn the halos, simulates a mouse move on the rotation halo, and asserts that it does not signal a MessageNotUnderstood exception.  
This test had to be tweaked to make it run on Pharo7 because of an instance variable having an accessor method in P8 but not in P7.  
The test passes on Pharo 7, but fails on Pharo 8.  
I also had to add the creation and deletion of a CircleMorph in the setUp/tearDown:
```Smalltalk
setUp
	super setUp.
	morph := Morph new.
	circleMorph := CircleMorph new.
```

```Smalltalk
tearDown
	morph delete.
	circleMorph delete.
	super tearDown
```

**Pharo 8 version**
```Smalltalk
testMouseOverRotationHandleShouldNotSignalMessageNotUnderstood
	"Mousing hover the rotation handle of a morph should not raise '#degrees was sent to nil'"

	"This test is performed on @circleMorph and not just @morph because the morph used needs to want to generate a rotation halo (see method #wantsHaloHandleWithSelector:inHalo:). Instances of Morph do not want that, but instances of CircleMorph do."
	| mouseDownEventToCreateHalos handMorph halo pos mouseMoveEvent |
	handMorph := WorldMorph cursorOwnerWorld worldState hands first.
	mouseDownEventToCreateHalos := MouseButtonEvent new setType: #mouseDown position: circleMorph position buttons: 73 hand: handMorph.
	circleMorph openInWorld.
	halo := circleMorph addHalo: mouseDownEventToCreateHalos.
	"Specifically finding the rotation halo does not seem easy to do in a robust way (you could always search for the name of the icon or some other characteristic like that, but what if the icon is changed in the future?). So we'll send a mouse hover event to each submorph. "
	halo submorphs do: [ :subMorph |
		pos := subMorph position.
		mouseMoveEvent := MouseMoveEvent new setType: #mouseMove startPoint: pos endPoint: pos trail: nil buttons: 0 hand: handMorph stamp: 0.
		self flag: #improvement. "Is there a way to be more precise in the following assertion: to say that the block shouldn't raise a MessageNotUnderstood **for the #degrees selector**?"
		self shouldnt: [subMorph handleEvent: mouseMoveEvent] raise: MessageNotUnderstood.
	].
```

**Pharo 7 version**
```Smalltalk
testMouseOverRotationHandleShouldNotSignalMessageNotUnderstood
	"Mousing hover the rotation handle of a morph should not raise '#degrees was sent to nil'"

	"This test is performed on @circleMorph and not just @morph because the morph used needs to want to generate a rotation halo (see method #wantsHaloHandleWithSelector:inHalo:). Instances of Morph do not want that, but instances of CircleMorph do."
	| mouseDownEventToCreateHalos handMorph halo pos mouseMoveEvent |
	handMorph := (WorldMorph cursorOwnerWorld instVarNamed: #worldState) hands first.
	mouseDownEventToCreateHalos := MouseButtonEvent new setType: #mouseDown position: circleMorph position buttons: 73 hand: handMorph.
	circleMorph openInWorld.
	halo := circleMorph addHalo: mouseDownEventToCreateHalos.
	"Specifically finding the rotation halo does not seem easy to do in a robust way (you could always search for the name of the icon or some other characteristic like that, but what if the icon is changed in the future?). So we'll send a mouse hover event to each submorph. "
	halo submorphs do: [ :subMorph |
		pos := subMorph position.
		mouseMoveEvent := MouseMoveEvent new setType: #mouseMove startPoint: pos endPoint: pos trail: nil buttons: 0 hand: handMorph stamp: 0.
		self flag: #improvement. "Is there a way to be more precise in the following assertion: to say that the block shouldn't raise a MessageNotUnderstood **for the #degrees selector**?"
		self shouldnt: [subMorph handleEvent: mouseMoveEvent] raise: MessageNotUnderstood.
	].
```
**Difference between Pharo 7 and 8 versions**
**P8** `handMorph := WorldMorph cursorOwnerWorld worldState hands first.`  
**P7** `handMorph := (WorldMorph cursorOwnerWorld instVarNamed: #worldState) hands first.`

**Comment by dupriezt** [comment] 2019-09-27 14:10
We (@StevenCostiou @Alisu) tracked the issue down to a change in the `Morph>>#handlesMouseMove: ` method.
In pharo 8, a bit of code was added by PR #3382. The Pharo 7 behaviour of this method is to send a MouseMove event to a morph if and only if
- the hand is not dragging anything
- and some button is down
- and the morph is the current mouse focus

The bit that was added makes it so that even if a morph does not satisfy these conditions, it will receive the MouseMove event if it explicitly subscribed to it.

And the handle morph has a direct subscription to MouseMove, as can be seen in `HaloMorph>>#addRotateHandle:`

**HaloMorph>>#addRotateHandle:**
```Smalltalk
addRotateHandle: haloSpec
	(self addHandle: haloSpec on: #mouseDown send: #startRot:with: to: self)
		on: #mouseMove send: #doRot:with: to: self
```

**Morph>>#handlesMouseMove: (Pharo 8)**
```Smalltalk
handlesMouseMove: anEvent
	"Rules say that by default a morph gets #mouseMove if
		* the hand is not dragging anything,
			+ and some button is down,
			+ and the receiver is the current mouse focus."
			
	self eventHandler ifNotNil: [ :handler | 
		(handler handlesMouseMove: anEvent) ifTrue: [ 
			^ true ] ].
				
	^anEvent hand submorphs isEmpty and: [ 	 
		(anEvent anyButtonPressed and:[
			anEvent hand mouseFocus == self
		])]
```
**Morph>>#handlesMouseMove: (Pharo 7)**
```Smalltalk
handlesMouseMove: anEvent
	"Rules say that by default a morph gets #mouseMove iff
		* the hand is not dragging anything,
			+ and some button is down,
			+ and the receiver is the current mouse focus."
			
	"self eventHandler ifNotNil: [:handler | ^handler handlesMouseMove: anEvent ]."
				
	^anEvent hand submorphs isEmpty and: [ 	 
		(anEvent anyButtonPressed and:[
			anEvent hand mouseFocus == self
		])]
```

**Comment by eliohernanph** [comment] 2020-04-01 03:05
Should #3382 be reverted and revisited?

**Comment by guillep** [comment] 2020-04-03 17:29
This seems to be fixed in Pharo 9. Can you confirm?

![image](https://user-images.githubusercontent.com/708322/78388425-455c7500-75e1-11ea-8bc7-8adebf29aa5c.png)

If so, somebody has an idea of what fixed it? I'll check...

**Comment by guillep** [comment] 2020-04-03 17:43
I've checked:
 - build 100 works
 - build 50  broken
 - build 75 works
 - build 62 broken
 - build 68 broken
 - build 72 broken
 - build 74 broken => so it was fixed in 75

Build 75 => 1b765cee67553167feb92d2c9873e35304600c77
https://github.com/pharo-project/pharo/pull/5446

So this was actually fixed by @ericbrandwein :) Thanks a lot, I can close a couple of issues now

**Closed as completed by guillep** 2020-04-03 17:43 UTC
