### ISSUE TITLE
Rubric race-conditions

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2447] opened 2019-02-06 09:30 UTC
Pharo 7 build 143

When using the STCommandLineHandler>>installSourceFile:
ThreadSafeTranscript open seems to have a race-condition
I get a subscriptOutOfBounds in the beForSmalltalkScripting
In RubSmalltalkScriptingMode>>updateTextAreaWhenPlugged

self textArea updateTextWith: '' manages to get confused about selection boundaries and tries to use those of the original text

'
Fetched -> BaselineOfTaskIt-CompatibleUserName.1543957602 --- https://github.com/sbragagnolo/taskit.git[v1.0.1] --- https://github.com/sbragagnolo/taskit.git[v1.0.1]'
is the text that was in there.

**Comment by StephanEggermont** [comment] 2019-09-12 06:32
Reopen

**Comment by Ducasse** [comment] 2019-09-17 09:06
Stephan do you have a way to reproduce it?

**Comment by StephanEggermont** [comment] 2019-09-17 10:29
@VincentBlondeau is that still reliably happening?

**Comment by VincentBlondeau** [comment] 2019-09-18 08:36
I do not use Pharo 7 anymore so I do not know

**Comment by guillep** [comment] 2020-03-27 10:40
Hi @StephanEggermont could you check if this is the same case as in https://github.com/pharo-project/pharo/issues/5966?

Thanks!

**Comment by StephanEggermont** [comment] 2020-03-29 18:05
That could be the same case indeed. Reliably reproducing it is difficult, this one used your proprietary code, @VincentBlondeau

**Comment by VincentBlondeau** [comment] 2020-04-03 14:16
I cannot tell anymore. I do not know how to reproduce it.

**Comment by MarcusDenker** [comment] 2020-10-06 10:41
i close this as a duplicate of  #5966

**Closed as completed by MarcusDenker** 2020-10-06 10:41 UTC
Labels: Type: Bug, Project: Graphics
