### ISSUE TITLE
Pharo 8 (stable) opens unresponsive image

### ISSUE THREAD

**Issue by LizaChambi** [guillep/pharo-core#5575] opened 2020-01-24 17:48 UTC
Hello,  I have an issue with a  Pharo 8 (stable) image this morning. I saved&quit that image yesterday, I didn't change the image name. Now it opens blank (no background nor menues) and it accepts no imput from mouse or keyboard. I started with PharoLauncher. Image: Pharo8.0.0 [Build information: Pharo-8.0.0+build.1122.sha.bbcdf9770748d12e2c1b84f168f0232e4f918d20 (64 Bit)] .
I also tried running the image from the terminal (linux) and It reports no errors or warnings.
The windows was unresponsive and the only way to close it was by means of "kill -9..." .

![Screenshot from 2020-01-24 09-59-52](https://user-images.githubusercontent.com/12850748/73091092-72412d00-3eb8-11ea-862e-d795c991c2e9.png)

**Comment by astares** [comment] 2020-01-26 16:19
Can you please retry by download a fresh Pharo 8 image using Launcher and tell us if it works or if you have a reproducible case? Thanks!

**Comment by Ducasse** [comment] 2020-01-26 17:09
+1 I imagine that liza is following our lecture (so we will see if we get an answer before next friday).

**Comment by LizaChambi** [comment] 2020-01-27 13:52
I downloaded a new image of Pharo 8 (stable) with Launcher that same day and it worked fine, then I installed PetitParser2 and GToolkit with Metacello to work with them, but soon after, as I was writing, the image suddenly closed. Now when I try to open the image with Launcher, it closes immediately and with the terminal it only says 'Aborted (core dumped)' I have generated a crash.dmp file, I attach them as .txt.
[crash.txt](https://github.com/pharo-project/pharo/files/4117352/crash.txt)
.

**Comment by Ducasse** [comment] 2020-01-27 14:25
Can you tell us exactly how you installed PetitParser2 ?

**Comment by Ducasse** [comment] 2020-01-27 14:26
Because it should not be loaded via monticello.

**Comment by LizaChambi** [comment] 2020-01-27 14:41
I downloaded PetitParser2 with a guide from https://github.com/kursjan/petitparser2.

Metacello new
    baseline: 'PetitParser2';
    repository: 'github://kursjan/petitparser2';
    load.

Metacello new
    baseline: 'PetitParser2Gui';
    repository: 'github://kursjan/petitparser2';
    load.

<blockquote><img src="https://avatars1.githubusercontent.com/u/4191369?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/kursjan/petitparser2">kursjan/petitparser2</a></strong></div><div>A high-performance top-down parser. Contribute to kursjan/petitparser2 development by creating an account on GitHub.</div></blockquote>

**Comment by Ducasse** [comment] 2020-01-27 16:13
Thanks!
We saw that some other people have the same problem and we cannot reproduce it. 
I tried with Pharo 80, 70 and it worked. :(

**Comment by Ducasse** [comment] 2020-01-27 16:15
Pablo I tried to reproduce it because serge reported this problem with kendrick and I could not.
Now I will retry with the latest stable VM.

**Comment by Alisu** [comment] 2020-01-31 09:36
You gave the metacello scripts for PetitParser2 but can you also give the one you used for GToolkit please ? 
Oh and also the version of your OS ?

It seems this happens during the GC and may be a vm problem. You should try the new VM.

**Comment by LizaChambi** [comment] 2020-01-31 13:48
I use Ubuntu 19.10, and downloaded GToolkit from https://github.com/feenkcom/gtoolkit:

EpMonitor current disable.
[ 
  Metacello new
    baseline: 'GToolkit';
    repository: 'github://feenkcom/gtoolkit/src';
    load
] ensure: [ EpMonitor current enable ].
#GtWorld asClass open.

This week I used the Image: Pharo8.0.0 [Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)] with PetitParser2, and Its working fine. I recently installed GToolkit, if I have any problem I will inform them.

<blockquote><img src="https://repository-images.githubusercontent.com/100369621/42e49a80-9d85-11e9-854a-05e390fffd19" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/feenkcom/gtoolkit">feenkcom/gtoolkit</a></strong></div><div>Glamorous Toolkit is the moldable development environment. - feenkcom/gtoolkit</div></blockquote>

**Comment by akgrant43** [comment] 2020-02-01 07:35
> I downloaded a new image of Pharo 8 (stable) with Launcher that same day and it worked fine, then I installed PetitParser2 and GToolkit with Metacello to work with them, but soon after, as I was writing, the image suddenly closed. Now when I try to open the image with Launcher, it closes immediately and with the terminal it only says 'Aborted (core dumped)' I have generated a crash.dmp file, I attach them as .txt.
> [crash.txt](https://github.com/pharo-project/pharo/files/4117352/crash.txt)
> .

This looks more like a known GC issue in the VM than a PP2 or Gtoolkit issue.

There's a new VM available, see http://forum.world.st/New-Latest-VM-Please-Test-td5110167.html
(it has issues with earlier versions of Ubuntu, but if you're on 19.04 you should be OK)

<blockquote><div><strong><a href="http://forum.world.st/New-Latest-VM-Please-Test-td5110167.html">Pharo Smalltalk Developers - New Latest VM - Please Test</a></strong></div><div>New Latest VM - Please Test. Hello, I have just uploaded a new version of the VM as the latest. This version is the one to be intended for Pharo 8 release. Please feel free to test...</div></blockquote>

**Comment by LizaChambi** [comment] 2020-02-05 19:02
Today the Image: Pharo8.0.0 [Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)] suddenly closed while working. When I try to open the image with Launcher, it closes immediately, and from terminal report an Error: 'Segmentation fault'.
I didn't use the new VM, but I will use it now.

**Comment by MarcusDenker** [comment] 2021-07-23 12:36
Can we close this issue?

**Comment by LizaChambi** [comment] 2021-07-23 14:43
Yes, they can close it.

**Closed as completed** 2021-07-23 14:49 UTC
