### ISSUE TITLE
Skew selection boxes in the help

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7614] opened 2020-10-29 09:55 UTC
**Describe the bug**
In some special cases, the selection box in the class comment view can have skew border.

**To Reproduce**
Create a class with this comment:
<pre>
To open me, evaluate:

```language=Pharo
ApedFormEditor openWithGtk.
```
</pre>

Try to do selection like this:
![ko5dPZh8pR](https://user-images.githubusercontent.com/572494/97553000-330ab400-19d5-11eb-810c-9fd5fcc483f4.gif)

**Comment by astares** [comment] 2020-10-29 10:14
Bug or feature?

**Comment by MarcusDenker** [comment] 2020-11-05 14:24
Duplicate of https://github.com/pharo-project/pharo/issues/7361

**Comment by MarcusDenker** [comment] 2022-12-13 07:21
This now works!

**Closed as completed by MarcusDenker** 2022-12-13 07:21 UTC
Labels: Type: Bug
