### ISSUE TITLE
[Refactoring] Rename refactoring is not working anymore

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#15523] opened 2023-11-23 02:33 UTC
I just tried to rename a method in calypso by using the shortcut `cmd + r` and when I gave the new selector name it fails with this error: `Symbol does not define #nameOfTheOriginalMethodToRename`.

Maybe this is the same kind of bug that we found on the remove method refactoring @Ducasse?

<img width="851" alt="image" src="https://github.com/pharo-project/pharo/assets/9519971/52375581-8e55-4ba5-ba84-1634b80ddea6">

**Comment by jecisc** [comment] 2023-11-23 02:34
Note: If I select the method in the method column and do cmd + r it does not work.
If I click on the method name in the method edition pane at the bottom of Calypso and do the shortcut it works. Are we using two different refactorings?

**Comment by Ducasse** [comment] 2023-11-23 09:29
May be who knows. When people reinvent refactoring in the command then you may have different refactoring.

**Comment by Ducasse** [comment] 2023-11-23 09:31
In my image (latest) I can rename without problem a method just using the menu.
I cannot reproduce the problem.
I will remove the double entry.

**Comment by Ducasse** [comment] 2023-11-23 09:32
I checked and it works with the menu or the cmd + r

**Comment by MarcusDenker** [comment] 2023-11-27 17:36
PR was merged

**Closed as completed by MarcusDenker** 2023-11-27 17:36 UTC
Labels: Type: Bug, Project: Refactorings
