### ISSUE TITLE
Why do we have BaselineOfTelePharo support in P8 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4593] opened 2019-09-13 17:38 UTC
baseline: spec 
    
	<baseline>

	| repository | 
	
	repository := self packageRepositoryURL.

	spec for: #common do: [
		spec baseline: 'SUnit' with: [spec repository: repository].
		spec baseline: 'Display' with: [spec repository: repository].

		spec package: 'SortFunctions-Core'.
		spec package: 'Tool-Registry'.
	].

**Comment by MarcusDenker** [comment] 2021-05-12 07:50
duplicate of https://github.com/pharo-project/pharo/issues/5084

**Closed as completed by MarcusDenker** 2021-05-12 07:50 UTC
