### ISSUE TITLE
[CI] StOpenFilePresenterTest>>testSelectedEntriesMultipleSelection faling

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16911] opened 2024-07-17 06:00 UTC
**Bug description**
A PR was merged that now makes 

StOpenFilePresenterTest>>testSelectedEntriesMultipleSelection

fail on the CI

(I wonder if we should not better stop merging *anything* before the tests are green?)

**Comment by jecisc** [comment] 2024-07-17 12:14
I found that the problem is that when we select the entries we use a identity comparison to find the indexes of the elements in the table, but here we have objects that are equals but that are not identical

**Comment by MarcusDenker** [comment] 2024-07-18 11:21
Do we know the PR that made this fail? This was for sure due to a PR added after we broke the tests three weeks ago

**Comment by MarcusDenker** [comment] 2024-07-22 13:15
This might be related to: https://github.com/pharo-spec/Spec/pull/1568

**Comment by MarcusDenker** [comment] 2024-07-24 12:32
This is fixed

**Comment by jecisc** [comment] 2024-07-24 13:02
Not yet, only a half of the fix got integrated

**Comment by jecisc** [comment] 2024-07-24 13:10
I was able to merge the PR fixing this so I'll close it again now

**Closed as completed by jecisc** 2024-07-24 13:10 UTC
Labels: Type: Bug
