### ISSUE TITLE
DoubleWordArray is not usable...

### ISSUE THREAD

**Issue by stacksmith** [guillep/pharo-core#6318] opened 2020-05-07 21:50 UTC
DoubleWordArray is not capable of storing DoubleWords - only 32-bit values work.    It appears to allocate and read, but to store, primitive 61 expects a SmallInteger.

Looking at Squeak (which has no such issues), DoubleWordArray class is defined ass `ArrayedCollection variableDoubleWordSubclass: #DoubleWordArray...` while Pharo defines it as `ArrayedCollection variableWordSubclass: #DoubleWordArray`.  

Is there a plan to fix this?    This was reported a while back: [related issue 5956](https://github.com/pharo-project/pharo/issues/5956).   There is even a proposed patch there.  It seems fairly essential to store 64-bit arrayed data on 64-bit machines.

Example:
`{1<<32} as: DoubleWordArray `

**Comment by svenvc** [comment] 2020-05-08 07:24
Could you provide changes/fixes with tests ?

**Comment by stacksmith** [comment] 2020-05-08 17:01
@svenvc   I am slightly out of my comfort zone, but the file (by  leves@caesar.elte.hu ) you linked from issue 5956 contained among other things 3 definitions (see below) that **apparently** fix the problem.   

After filing in I had no issues storing larger ints.  I have reservations, because it looks like the fix introduces `variableDoubleWordSubclass:..` and redefines `DoubleWordArray`, but looking at DoubleWordArray with a browser still shows `variableWordSubclass`.  It acts as if it uses the new layout correctly, and seems stable.

**I will therefore respectfully ask for someone who really understands the VM and the object layout and creation mechanism to look it over and integrate into Pharo.**  It seems like a trivial fix.

Here is the snippet I am using:
```
!Class methodsFor: 'subclass creation - variableWord' stamp: 'ul 3/28/2020 15:44'!
variableDoubleWordSubclass: className instanceVariableNames: instVarNameList classVariableNames: classVarNames package: cat

	^ self
		variableDoubleWordSubclass: className
		instanceVariableNames: instVarNameList
		classVariableNames: classVarNames
		poolDictionaries: ''
		package: cat! !

!Class methodsFor: 'subclass creation - variableWord' stamp: 'ul 3/28/2020 15:43'!
variableDoubleWordSubclass: t instanceVariableNames: f classVariableNames: d poolDictionaries: s package: cat

	^ self classInstaller
		make: [ :builder | 
			builder
				superclass: self;
				name: t;
				layoutClass: DoubleWordLayout;
				slots: f asSlotCollection;
				sharedVariablesFromString: d;
				sharedPools: s;
				category: cat;
				environment: self environment ]! !

ArrayedCollection variableDoubleWordSubclass: #DoubleWordArray
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Collections-Native-Base'!```

**Comment by stacksmith** [comment] 2020-05-19 18:53
A possible explanation: there is no problem with the fix above, but Calypso shows a stale version.  I've had a lot of issues with Calypso that smell like this.

**Comment by MarcusDenker** [comment] 2020-10-07 10:54
This seems to be a duplicate of #5956, I close it so that all the discussion is at one place

**Closed as completed by MarcusDenker** 2020-10-07 10:54 UTC
Labels: Type: Bug
