### ISSUE TITLE
Stack in the new debugger isn't automatically filled

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6940] opened 2020-07-21 15:06 UTC
**Describe the bug**
The stack in the debugger should add more contents whether the pane is extended or the lift progresses.

**To Reproduce**
1. Open a debugger on a large stack
2. enlarge the window
2. scroll without clicking on the last item of the stack
3.the next items are not loaded

**Expected behavior**
3. the items load

**Screenshots**
![image](https://user-images.githubusercontent.com/4706329/88071720-7d79ca80-cb74-11ea-8f8a-95d699fa40fa.png)

**Version information:**
 - OS: win 10
 - Version: Pharo9.0.0 build: 523, commit: 56bc82a

**Comment by Ducasse** [comment] 2020-07-21 16:39
Hi steven
Can you have a look? I did not understand really the problem. Now I would love to see the arguments
of the message. May be we should have configuration. Because having to expand all the time is a pain.

**Comment by StevenCostiou** [comment] 2020-07-21 16:48
Hi @VincentBlondeau @Ducasse there seems to be two things there.
The stack: yes, for now it only expands when the last stack item is clicked. I will look at that.
The arguments: I do not understand the question :/

**Comment by StevenCostiou** [comment] 2020-07-21 17:40
Ok, by default previous debuggers showed the whole stack with a maximum size of 9999 (by default when calling `stack` in contexts).
I will try that, I have no idea of the impact on performances.

**Comment by StevenCostiou** [comment] 2020-07-21 17:44
> I will try that, I have no idea of the impact on performances.

So, a lot of impact :p stepping has a latency... I'll work on that.

**Comment by StevenCostiou** [comment] 2020-07-23 12:52
@VincentBlondeau hi, could you give a number for "big stacks"?
I'm benchmarking a bit because when too much elements are in the stack there is a performance hole in the debugger while stepping. 
How deep could be a stack for you?

**Comment by VincentBlondeau** [comment] 2020-08-11 09:45
Hi Steven,

The stack could be limited at 4500 (the limit of stack execution in Gemstone is 4000). But, local image calls could be larger than that, you never know what can happen. After, it is acceptable to wait for the load of the stack if it is more than 1000 since it should not arrive that often.

Hope this helps,

**Comment by martinmcclure** [comment] 2020-09-13 00:01
I'm glad to see this discussion. The current number of contexts initially shown (19 or something?) is too few. Thanks for working on this.

**Comment by StevenCostiou** [comment] 2020-10-07 08:57
Hi, I decided to close that issue by just providing the full stack everytime (like before) so we do not have regressions.
The slowness issue is actually another problem.
Sorry for the time it took. The fix will be included in the next NewTools merge.

**Closed as completed** 2020-10-07 12:54 UTC
Labels: Type: Bug
