### ISSUE TITLE
Renaming a class raises a DNU

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3993] opened 2019-07-17 17:37 UTC
handleClassRenamed: anAnnouncement
	| items selectedIndex |
	items := self messages
		collect: [ :rgMethod | 
			| interestedClassName interestedClass |
			interestedClassName := anAnnouncement oldName.
			interestedClass := anAnnouncement classRenamed.
			rgMethod isMetaSide
                               ^^^^^^^^^^^^^^^^^^^^^^^^ 

				ifTrue: [ interestedClassName := interestedClassName , ' class'.
					interestedClass := interestedClass classSide ].
			rgMethod parentName = interestedClassName
				ifTrue: [ (interestedClass >> rgMethod selector) asFullRingDefinition ]
				ifFalse: [ rgMethod ] ].
	selectedIndex := messageList selectedIndex.
	self messages: items.
	self setSelectedIndex: selectedIndex

**Comment by Ducasse** [comment] 2019-07-17 17:40
Apparently isMetaSide is not polymorphic between compiled method and RGElementDefinition.
Only RGElementDefinition defines isMetaSide. 
I suggest to deprecate isMetaSide and use isClassSide.

Now I do not understand why this bug shows up now.

**Comment by gcotelli** [comment] 2019-07-17 18:07
There are other senders of #isMetaSide , so probably them are broken too.

**Comment by MarcusDenker** [comment] 2020-10-14 11:32
duplicate of https://github.com/pharo-project/pharo/issues/4268

**Closed as completed by MarcusDenker** 2020-10-14 11:32 UTC
