### ISSUE TITLE
Method selection does not show the correct method when copied by renaming

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#13932] opened 2023-06-07 10:34 UTC
**Bug description**
In Calypso, if the method contains a pragma and the method selector is changed to create a copy of the method, the original method still displays the copied method.

**To Reproduce**
1. create some class
2. create and save a method 
```smalltalk
msg1
<somePragma>
```
3. in the method code pane, change the selector to `msg2`, a new method is created
4. click on the method `msg1`, it will still display content of `msg2`

![Pharo_Mj3zlmq15F](https://github.com/pharo-project/pharo/assets/572494/d9109b11-5304-4308-9a26-850f5b45e00e)

**Version information:**
- Pharo Version: 12

**Comment by Ducasse** [comment] 2023-06-07 20:02
Hi pavel
I tried to understand your problem but I could not understand it. 
When I create a method just changing the selector then I get a method with the same body. 
I imagine that this is not what you mean. 
So could you re-explain?

Tx

**Comment by pavel-krivanek** [comment] 2023-06-08 06:39
- create a method with a pragma and selector `msg1`, save it
- then, edit the method, keep the body and just change the selector to `msg2`. That creates a new method so we have now `msg1` and `msg2` with the same body. So far so good.
- but then, if you switch in the browser to the original method `msg1`, you will see the source code of `msg2`. The two compiled methods are somehow linked.

**Comment by Ducasse** [comment] 2023-06-08 20:54
Ok I see the method msg is selected but the pane displays msg2.

**Comment by Ducasse** [comment] 2023-06-08 20:57
To me the title should be "method selection does not show the correct method when defined"

**Comment by Ducasse** [comment] 2023-11-13 14:08
In a recent image I tried all possible combination of edition and I could not reproduce it - and this is not linked to refactorings so I propose to close this issue.

**Closed as completed by Ducasse** 2023-11-13 14:08 UTC
Labels: Type: Bug
