### ISSUE TITLE
RBMethodNode>>tempnames is used in the build

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#3432] opened 2019-05-28 16:23 UTC
So should not be deprecated

**Comment by jecisc** [comment] 2019-05-28 17:06
Can you indicate where it is used? Maybe it’s code that should be cleaned.

**Comment by StephanEggermont** [comment] 2019-05-28 17:17
See the build log of e.g. build 301. 
https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo8.0/301/consoleFull

**Comment by MarcusDenker** [comment] 2019-05-28 18:06
the problem is that on the level of the CompiledMethod, temps include arguments. On the level of the AST they do not. 

Maybe the better change would be to change CompiledMethod>>#tempNames to call the right method on the AST and document it there

**Comment by StephanEggermont** [comment] 2019-05-29 10:33
I have no idea of the consequences of that. I know the consequences of a dirty build. Please come up with a proposal or integrate the PR

**Comment by MarcusDenker** [comment] 2019-05-29 10:34
Yes, I will do another PR

**Comment by MarcusDenker** [comment] 2019-05-30 10:46
merged https://github.com/pharo-project/pharo/pull/3436

**Closed as completed by MarcusDenker** 2019-05-30 10:46 UTC
