### ISSUE TITLE
The Tool-FileList throws an exception when selecting non user-accesible folders on windows.

### ISSUE THREAD

**Issue by lopezca** [guillep/pharo-core#9787] opened 2021-08-19 03:27 UTC
When selecting a non user-accesible folder on windows, such as 'System Volume Information', the FileBrowser tool throws an exception (In this case, it's can't open dir, error = -9).
![image](https://user-images.githubusercontent.com/27969022/130001834-bb2468f6-861d-4ec5-b790-2e43d4dfa422.png)

The File class is the one that tries to read the files from the directory and throws here:
![image](https://user-images.githubusercontent.com/27969022/130002139-f1e69df9-02f0-4c05-8ec5-71475de57de7.png)

the `File>>signalError:for:` method creates exceptions that belong to the `FileSystemError` and `FileException` classes.

When building the file list, the tool handles only the case `DirectoryDoesNotExist`  which is a subclass of `FileSystemError` as is seen here:

![image](https://user-images.githubusercontent.com/27969022/130002487-39952d28-2d97-431e-a406-404c0b73530f.png)

I suggest changing the following line to return the empty array (as it does) on both `FileSystemError` and `FileException` classes.

```st
files :=  [self directory files] 
		on: FileException, FileSystemError
		do:[#()].
```

https://github.com/pharo-project/pharo/blob/ae0e2bfd3468c1cfad5b036a6d5bc7d7ce9866ea/src/Tool-FileList/FileList.class.st#L681

With that change, the offending folder appears empty.

**Comment by guillep** [comment] 2024-12-20 16:03
Duplicate of https://github.com/pharo-project/pharo/issues/9787

**Closed as completed by guillep** 2024-12-20 16:03 UTC
Labels: NewTools: FileList

**Comment by astares** [comment] 2024-12-20 19:45
@guillep 9787 a duplicate of itself (9787)?

**Comment by lopezca** [comment] 2024-12-28 19:31
The problem persists in p12, but is no longer present in p13 with the new tools implementation; maybe it's ok to keep closed.
p12:
![image](https://github.com/user-attachments/assets/8913f561-2fdc-49c3-a0cc-137bed93b83a)

P13:
![image](https://github.com/user-attachments/assets/1eb94869-149c-496b-bf53-01790e81b4e2)
