### ISSUE TITLE
Scope of refactorings do not work anymore

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#10777] opened 2022-01-20 18:26 UTC
**Bug description**
I tried to do some refactoring in Pharo 9 but I found out that the scopes do not work anymore. When I apply a scope it does not update the list of changes to apply.

**To Reproduce**
1. Got to `MCMczWriter>>#format` for example
2. Rename it to #format2
3. Click Yes when Pharo tells you there are 13 implementors in the image
4. Select the scope package to rename only the implementors in the package

**Expected behavior**
I would expect only methods in the current package to appear but all the changes are still here. 

This makes it difficult to rename methods with common names.

**Version information:**
 - OS: Windows
 - Version: 11
 - Pharo Version 9, I also tried in 10

**Comment by VincentBlondeau** [comment] 2022-01-20 18:36
Reproduceable in Pharo-9.0.0+build.1574.sha.6f28d0ac49d81e9de393a2be456ec92a7ede327f (64 Bit)

**Comment by jecisc** [comment] 2022-01-23 19:56
I have the impression it comes from https://github.com/pharo-project/pharo/commit/2c070314b1cca9e66817754914e949578fe31c71 

But I don't have the knowledge of refactorings nor the time to fix it :(

**Comment by Ducasse** [comment] 2022-01-24 08:23
Thanks cyril I checked and the scope browser was not introduced because evelyn left to work on IA :(
so I'm not sure that it is that change but we will have a look. I asked Carolina to have a look at the scope browser because we need it. 


```
TRefactoringCommandSupport >> setUpModelFromContext: aContext [
 	| browser scope |
 	browser := aContext browser.
 	scope := browser defaultNavigationScope.
 	scope description = 'current image' ifTrue: [
 		(UIManager default confirm: 'Do you want select another scope?') ifTrue: [ |scopes choosenScope|
 			scopes := browser allNavigationScopes.
 			choosenScope := UIManager default
 				chooseFrom: ( scopes collect: #description)
 				values: scopes
 				title: 'Choose the scope'.
 			choosenScope ifNil: [ 
 				self inform: 'Command aborted, you must select a scope.'.
 			CmdCommandAborted signal ].
 		scope := choosenScope.
 		]
 	].
 	model := RBClassModelFactory rbNamespace onEnvironment: scope asRBEnvironment
 ]
```

**Comment by carolahp** [comment] 2022-03-25 16:21
Together with @jordanmontt we have proposed a PR to make the scope drop list functional. 
Integrating Evelyn's work on custom scopes is ongoing work by me.

**Comment by jecisc** [comment] 2022-03-26 11:45
Thank you!

**Comment by jordanmontt** [comment] 2022-05-20 12:16
There is an PR that has been merged. Should we close this? @MarcusDenker

**Comment by MarcusDenker** [comment] 2022-05-20 12:17
Yes!

**Closed as completed by MarcusDenker** 2022-05-20 12:17 UTC
Labels: Type: Bug
