### ISSUE TITLE
On monterey opening the image does not show anything ( no ui)

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11158] opened 2022-04-25 13:24 UTC
Here is the log 

```
 bash -c 'cd "/Users/ducasse/Documents/Pharo/images/P10-MathTests" && "/Users/ducasse/Documents/Pharo/vms/100-x64/Pharo.app/Contents/MacOS/Pharo" "/Users/ducasse/Documents/Pharo/images/P10-MathTests/P10-MathTests.image"'
primitive #setPinnedInMemory: in Bitmap failed
Bitmap(ProtoObject)>>primitiveFailed:
Bitmap(ProtoObject)>>primitiveFailed
Bitmap(Object)>>setPinnedInMemory:
Bitmap(Object)>>pinInMemory
Bitmap>>tfPointerAddress
SDL2 class>>createRGBSurfaceFromPixels:width:height:depth:pitch:rmask:gmask:bmask:amask:
TFCalloutAPI(FFICalloutAPI)>>function:library:
SDL2 class(Object)>>ffiCall:library:options:fixedArgumentCount:
SDL2 class(Object)>>ffiCall:library:options:
SDL2 class(Object)>>ffiCall:
SDL2 class>>createRGBSurfaceFromPixels:width:height:depth:pitch:rmask:gmask:bmask:amask:
OSSDL2BackendWindow>>icon:
OSWindowAttributes>>applyTo:
OSSDL2BackendWindow>>initWithHandle:attributes:
OSSDL2BackendWindow class>>newWithHandle:attributes:
[
		handle := SDL2 createWindow: attributes title
			x: x
			y: y
			width: attributes width
			height: attributes height
			flags: flags.

		aBackendWindow := OSSDL2BackendWindow newWithHandle: handle attributes: attributes.
		aBackendWindow osWindow: osWindow.
		self registerWindow: aBackendWindow.

		"The OSWindow handle has to be set inside of this critical section to avoid losing some events such as expose."
		osWindow setJustCreatedHandle: aBackendWindow.
	] in OSSDL2Driver>>createWindowWithAttributes:osWindow: in Block: [ ...
[
		caught := true.
		self wait.
		blockValue := mutuallyExcludedBlock value
	] in Semaphore>>critical: in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
Semaphore>>critical:
OSSDL2Driver>>createWindowWithAttributes:osWindow:
OSWindowAttributes>>createWindowHandleFor:
OSWindow>>createWindow
OSWindow>>initWithAttributes:eventHandler:
OSWindow class>>createWithAttributes:eventHandler:
OSWorldRenderer>>doActivate
OSWorldRenderer(AbstractWorldRenderer)>>activate
WorldState>>worldRenderer:
MorphicUIManager>>activate
UIManager class>>default:
UIManagerSessionHandler>>startup:
PrimitiveFailed: primitive #setPinnedInMemory: in Bitmap failed
Bitmap(ProtoObject)>>primitiveFailed:
Bitmap(ProtoObject)>>primitiveFailed
Bitmap(Object)>>setPinnedInMemory:
Bitmap(Object)>>pinInMemory
Bitmap>>tfPointerAddress
SDL2 class>>createRGBSurfaceFromPixels:width:height:depth:pitch:rmask:gmask:bmask:amask:
TFCalloutAPI(FFICalloutAPI)>>function:library:
SDL2 class(Object)>>ffiCall:library:options:fixedArgumentCount:
SDL2 class(Object)>>ffiCall:library:options:
SDL2 class(Object)>>ffiCall:
SDL2 class>>createRGBSurfaceFromPixels:width:height:depth:pitch:rmask:gmask:bmask:amask:
OSSDL2BackendWindow>>icon:
OSWindowAttributes>>applyTo:
OSSDL2BackendWindow>>initWithHandle:attributes:
OSSDL2BackendWindow class>>newWithHandle:attributes:
[
		handle := SDL2 createWindow: attributes title
			x: x
			y: y
			width: attributes width
			height: attributes height
			flags: flags.

		aBackendWindow := OSSDL2BackendWindow newWithHandle: handle attributes: attributes.
		aBackendWindow osWindow: osWindow.
		self registerWindow: aBackendWindow.

		"The OSWindow handle has to be set inside of this critical section to avoid losing some events such as expose."
		osWindow setJustCreatedHandle: aBackendWindow.
	] in OSSDL2Driver>>createWindowWithAttributes:osWindow: in Block: [ ...
[
		caught := true.
		self wait.
		blockValue := mutuallyExcludedBlock value
	] in Semaphore>>critical: in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
Semaphore>>critical:
OSSDL2Driver>>createWindowWithAttributes:osWindow:
OSWindowAttributes>>createWindowHandleFor:
OSWindow>>createWindow
OSWindow>>initWithAttributes:eventHandler:
OSWindow class>>createWithAttributes:eventHandler:
OSWorldRenderer>>doActivate
OSWorldRenderer(AbstractWorldRenderer)>>activate
WorldState>>worldRenderer:
MorphicUIManager>>activate
UIManager class>>default:
UIManagerSessionHandler>>startup:
```

**Comment by guillep** [comment] 2022-04-26 09:13
I was not able to reproduce it on my machine and the image that you shared to me.
I'm on a MacBook Pro (Retina, 13-inch, Early 2015), 2,9 GHz Intel Core i5, and still on Mojave.

We should probably debug it locally and see if it's not a problem with Monterey

**Comment by jordanmontt** [comment] 2022-05-20 12:13
I try to reproduce it and I couldn't neither. I am using Monterrey 12.4

**Comment by guillep** [comment] 2023-02-24 13:37
I think we can close this for now

**Closed as completed by guillep** 2023-02-24 13:37 UTC
Labels: Type: Bug
