### ISSUE TITLE
Bad compilation when creating a method in the debugger

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#5838] opened 2020-03-04 11:53 UTC
I am able to reproduce it, but only on a specific case. 
I'm currently trying to find a smaller reproducible case.

I'm using an unknown selector
it triggers a DNU on run
I create the method for this selector
I save it
(I don't think the rest is relevant but:)
re start it
another error
close the debugger

The initial method critique browser show errors of running the critics:
![Screenshot 2020-03-04 at 12 39 15](https://user-images.githubusercontent.com/21278554/75876044-384b3b00-5e15-11ea-8694-33d84681d5bc.png)
This error is because they encounter a variable node that was not semantically analysed.
Hence its binding is nil.

initial line: 
(self inlineIfMultipleNodeIntoSequence: nodesToInline insteadOf: aMessageNode) ifTrue: [ ^ self ].
actual line in the ast: 
(self	inlineIfMultipleNodeIntoSequence: nodesToInline insteadOf: aMessageNode)
       ifTrue: [ ThisContext home return: self ].

This is to be coming from : 
Object >> #mustBeBooleanCompileExpression:andCache:

I did not go further on this.

Recompiling the method (the code being actually right) clears the issue.

**Comment by StevenCostiou** [comment] 2020-03-27 21:41
How can I reproduce?
ThisContext is a temp generated when doing "debugIt" on code from the debugger.
I'm not sure it has any relation with the semantic analysis.
If I could reproduce I could investigate a bit.

**Comment by hogoww** [comment] 2020-03-28 15:34
I was not able to reproduce it last time, but I was this time, when playing around with the image I kept with it.
It was actually error related, so, mybad.

-Create a randomClass
put a method that calls an UNKNOWN method (here doSomething)
aMethod
	self doSomething ifTrue:[ ^ self ]

- run it.
- in the debugger, on the DNU, create doSomething
doSomething
     ^ self
proceed.

The execution will proceed with an error, and a deoptimized boolean; which will in turn do a doIt.
Close the debugger.
The code will be correct in Calypso, but not in the cached ast as shown by the critic browser :)

**Comment by hogoww** [comment] 2020-03-28 16:27
I forgot to mention that I was able to reproduce this on a fresh P9 image

**Comment by StevenCostiou** [comment] 2021-01-13 07:19
I cannot reproduce it. I am closing it, reopen it if you find a way to reproduce (please make a gif or a video so that I can see).

**Closed as completed by StevenCostiou** 2021-01-13 07:19 UTC
Labels: Project: Debugger

**Comment by hogoww** [comment] 2021-01-13 14:51
I just checked, this is not reproducible anymore.
At least not with my case.
(tried with spec and gt debuggers).
Guess it has been fixed then :)
P9 is currently fine !

**Comment by hogoww** [comment] 2021-01-13 14:54
Just checked on P8 for the sake of curiosity.
This is still happening on P8.
I do not think that deserves a fix though.
