### ISSUE TITLE
When FluidClass on Epicea Tests break

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8179] opened 2020-12-26 09:40 UTC
So I will fix them :)

**Comment by Ducasse** [comment] 2021-01-03 14:10
So far I failed to fix them :(
I published in my repo what I found

**Comment by Ducasse** [comment] 2021-10-18 20:59
Notes with Pablo in the train

For the fluid class builder on class side

We should return a builder prefilled with information from the instance side. 

For this we should 

Object << #Point

=> 

Object class << #Point class
	slots: {#uniqueInstance}
	traits: {TFlying + }
	package: ....
The steps to get there are:

- grab the instance (Point)
- create a class side builder to prefilled itself from the instance side
- then fill up the slots

**Comment by MarcusDenker** [comment] 2022-02-10 13:26
After https://github.com/pharo-project/pharo/pull/10882 is merged, we have just two failing tests:

EpRevertTest>>#testClassRemoval
EpRevertTest>>#testTraitRemoval

The mechanism to create a revertion of a removal (class and trait), which would be an adding of that class, is not working.

**Comment by MarcusDenker** [comment] 2023-03-09 09:58
I tracked down the cause: EpMonitor>>#behaviorRemoved: has workarounds that do not work for Fluid

- for Obsolete classes, the code after "Fix class name (remove AnObsolete prefix)
- for the category, see the code after "Fix category"

**Closed as completed** 2023-03-10 19:04 UTC
Labels: Type: Bug
