### ISSUE TITLE
there are 1 selectors with messages sent but not implemented in Opal Compiler

### ISSUE THREAD

**Issue by vonbecmann** [guillep/pharo-core#14929] opened 2023-10-09 00:34 UTC
```
| selectors |
selectors := SystemNavigation new allSentNotImplementedSelectors.
selectors select: [ :each | each package name beginsWith: 'Opal' ].
```

**Comment by MarcusDenker** [comment] 2023-10-17 11:24
duplicate of https://github.com/pharo-project/pharo/issues/10834

**Closed as completed by MarcusDenker** 2023-10-17 11:24 UTC
Labels: Type: Enhancement
