### ISSUE TITLE
Cleanup: use #isNotEmpty instead of #notEmpty

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#11309] opened 2022-05-30 17:58 UTC
We have many implementors of #isNotEmpty:

![image](https://user-images.githubusercontent.com/5980033/171041319-66760ba6-2676-4c5f-b7c4-6e0add9eafdf.png)

but we have also implementors of #notEmpty

![image](https://user-images.githubusercontent.com/5980033/171041378-89a34330-de1a-4582-bb23-9370c6f6d77a.png)

The "isSomething" or "isNotSomething" is usually the better style within the method category "testing".

So we should 
 - convert all #notEmpty into #isNotEmpty
 - deprecate the #notEmpty methods
 - write a rule to check method selectors to point the user to the fact that it is better to prefix "notSomething" into "isNotSomething"

**Comment by MarcusDenker** [comment] 2023-10-26 06:37
Duplicate of https://github.com/pharo-project/pharo/issues/15120

**Closed as completed by MarcusDenker** 2023-10-26 06:37 UTC
Labels: Status: Duplicate, Type: Cleanup
