### ISSUE TITLE
Undo works incorrectly in the Playground

### ISSUE THREAD

**Issue by mrakgr** [guillep/pharo-core#2814] opened 2019-03-14 09:54 UTC
I've checked this bug in Pharo 7 and Pharo 8. Here is how to replicate it.

```
1.
2.
3.
4
```

First write out the above or paste it into the Playground. Then delete the second line like so.

```
1.

3.
4
```

Then `Do it all and Go` using the button or `Ctrl+Shift+g`. Do not select all + right click. Then press `Ctrl+z` to undo.

For me what happens is this.

```
1.
```

Everything past the second line gets erased rather than the second line being undone..

**Comment by VincentBlondeau** [comment] 2019-10-10 12:59
Still happening

**Comment by VincentBlondeau** [comment] 2019-10-10 12:59
What is the process to reopen closed issues? Should we copy to another one are reference this one?

**Comment by MarcusDenker** [comment] 2019-10-10 13:07
sadly the right management of GitHub is quite limited, so only people with commit access to the repo can re-open, I think.

**Comment by VincentBlondeau** [comment] 2019-10-10 13:19
ok... Thanks Marcus!

**Comment by hogoww** [comment] 2020-04-06 07:33
I can be slightly more precise, 
present in the Calypso/debugger as well

- use a doIt/print it or whatever (from what I've seen) on something that triggers a parse error (such as do it on a collumn ':')
- echap
- ctrl + z several time
Text becomes incoherent.

**Comment by MarcusDenker** [comment] 2021-02-03 14:38
I close this as a duplicate of #7133

**Closed as completed by MarcusDenker** 2021-02-03 14:38 UTC
Labels: Type: Bug, Project: Tools
