### ISSUE TITLE
Debugger gives no indication the stack is not displayed fully

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#7451] opened 2020-10-09 08:11 UTC
**Describe the request**
Debugger gives no indication the stack is not displayed fully. You have to click on the last frame to trigger the load of missing frames. Even doing that, the scrollbar is not refreshed and it is difficult to see the new frames added.

**Expected behavior**
We should see clearly that new frames are available in the list.
When the last frame is selected, maybe scroll the last frame to the middle of the visible frames window so that new frames become visible (and scrollbar updated).

**Screenshots**
![bug-debbugger-stack-display](https://user-images.githubusercontent.com/2494203/95559186-a7c28200-0a17-11eb-9b5d-0ad46f1055ae.gif)

**Version information:**
Pharo 9

**Comment by StevenCostiou** [comment] 2020-10-12 07:39
This is a duplicate of https://github.com/pharo-project/pharo/issues/6940
This is fixed in NewTools and will be present in the next merge.

**Closed as completed** 2020-10-28 15:45 UTC
Labels: Type: Enhancement, Project: Debugger
